### ISSUE TITLE
ctrld failed install openwrt

### ISSUE THREAD

**Issue by Mathmxp** [Control-D-Inc/ctrld#105]
Using automatic installer for openwrt device from the devices website
installer stops at 

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : openwrt
OS Version   : 23.05.0
Arch         : x86_64
CPU          : Common KVM processor
Free RAM     : 166 MB / 231 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : ********
Binary URL   : https://assets.controld.com/ctrld/linux/amd64/ctrld
Install Path : /usr/sbin
---------------------
 - Starting download
 - Making binary executable
 - Launching /usr/sbin/ctrld
---------------------

nothing happens after that and controld device doesn't recognize the install.
Using an openwrt vm from Proxmox

**Comment by cuonglm** [comment]
Could you please do:

```
$ ctrld uninstall -vv
$ ctrld start --cd=<your UID> -vv --log=<your log file>
```

Then give me the content of log file when the command hangs.

Thank you.

**Comment by yegors** [comment]
As no additional info is provided, closing this.
