### ISSUE TITLE
GL.iNet MT6000 (Flint2) running ctrld service with 123% of memory usage

### ISSUE THREAD

**Issue by 4R3B3LatH34R7** [Control-D-Inc/ctrld#107]
I am just a new user and still learning my way around. Not very proficient with Linux and all.
So, forgive me if I made ridiculous assumptions or statements.
I just started running GL.iNet MT6000 (Flint2) since yesterday. And I'm a paid user of ControlD service.
Please see the attached photos to better understand the situation.
Before stopping service.
![Screenshot 2023-11-28 at 18-31-02 GL-MT6000 - LuCI](https://github.com/Control-D-Inc/ctrld/assets/53028471/d71290a2-e57b-407e-8078-238ca26a31d7)
After stopping service.
![Screenshot 2023-11-28 at 18-46-55 GL-MT6000 - LuCI](https://github.com/Control-D-Inc/ctrld/assets/53028471/d3ced904-d253-492d-a338-4d447aa0fe52)
However, in the normal non-Luci GUI, the Memory usage drops only from around 95% to 90% upon stopping the service. Not much different actually.
![Screenshot 2023-11-28 at 18-45-34 GL iNet Admin Panel](https://github.com/Control-D-Inc/ctrld/assets/53028471/5868146e-c8f6-443a-8982-2b6a7101ca92)

Is this expected behaviour?
Is this because, of all the total processes using RAM, CtrlD service is using 123% because there's not much running at that time?
I mean it is showing up like 123% because of relative number of running processes or absolute 123%, I'm not sure.
I am running WireGuard server on the router but no device is using VPN service during this time.
Thanks in advance.

**Comment by yegors** [comment]
It's not actually using this much memory, as the router doesn't even have that much to begin with. This is showing virtual memory: https://go.dev/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory

There is no real problem here.

**Comment by 4R3B3LatH34R7** [comment]
Thanks for explaining. I will study further.
