### ISSUE TITLE
Version 1.3.2 availability

### ISSUE THREAD

**Issue by photomme** [Control-D-Inc/ctrld#108]
Good day,

Congratulations on pushing v1.3.2.

When will it be available for the public?  Tried to update and I am still getting v1.3.1.  

Thanks

**Comment by cuonglm** [comment]
Related: https://github.com/Control-D-Inc/ctrld/issues/97

We are going to have a better release process, so once thing is available on Github, the installer will download the same version.

cc @yegors

**Comment by yegors** [comment]
Binaries are available on Github, installer is a separate system from Github.

**Comment by gniting** [comment]
OPs question remains unanswered, so I am pinging again. Understood that the installer follows a diff system, but when can we (those who use the installer) expect to see v1.3.2?

Agree that the release process needs to be revamped to be uniform across the board.

**Comment by domy86** [comment]
Be patient or update it manually.

**Comment by maghuro** [comment]
So when will be the installer updated?
