### ISSUE TITLE
More details about using newly added features

### ISSUE THREAD

**Issue by gniting** [Control-D-Inc/ctrld#110]
The release notes for v1.3.2 mention the following new features:
* Add a config option to enable an upstream to be used for LAN/PTR queries.
* Add a config option to specify how the client ID is generated.
* Add a config option to enable/disable answering queries from WAN clients.

These sound great and thanks for the work on them, but I cannot locate any documentation about how to go about setting these up, what are the various allowed parameters, etc. Can you point me to the right direction?

**Comment by cuonglm** [comment]
Here are list of those:

- For client ID generated: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#client_id_preference

- For LAN/PTR query: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#discoverable

For Wan clients answering: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#allow_wan_clients

**Comment by gniting** [comment]
Thanks!

**Comment by yegors** [comment]
@cuonglm Should probably link to those from the release notes

**Comment by cuonglm** [comment]
> @cuonglm Should probably link to those from the release notes

Done, also added link to MAC based policy.
