### ISSUE TITLE
Determine cache usage

### ISSUE THREAD

**Issue by gniting** [Control-D-Inc/ctrld#112]
How can I find out if a client DNS query is being served from the `ctrld` cache vs using upstream servers? Trying to run some optimizations on my network.

**Comment by cuonglm** [comment]
At this moment, there's no cache statistic manipulation yet.

You can enable DEBUG log, then see if there's `hit cached response` message in log when you make the query.

**Comment by gniting** [comment]
Sounds good and thanks (again) for the super fast response!
