### ISSUE TITLE
ControlD site is not synced with GitHub 

### ISSUE THREAD

**Issue by emhvoy** [Control-D-Inc/ctrld#114]
Hi all, 

it is not possible doing an upgrade by using sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)"' as the link still refers to ctrld version v1.3.1.  

Do you mind looking into this, please?

Thanks.

**Comment by cuonglm** [comment]
Duplicated of https://github.com/Control-D-Inc/ctrld/issues/108#issuecomment-1854192457

FYI, the link may be updated today.

**Comment by emhvoy** [comment]
Thank you so much for getting back to me promptly.
