### ISSUE TITLE
ctrld installer for Windows arm64 still installs version 1.3.0

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#115]
Hi,
The ctrld installer for Windows arm64 still installs version 1.3.0.
Please update the binary for this platform.
Thanks.

**Comment by yegors** [comment]
That seems unlikely. What POP is it using next to "Using Control D"?

**Comment by pmcarrion** [comment]
SCL for DNS and JNB for Proxy.

**Comment by yegors** [comment]
That's not what I asked. Its printed next to "Using Control D".

**Comment by pmcarrion** [comment]
I don't see "Using Control D" anywhere. Where is it supposed to be?

**Comment by yegors** [comment]
3rd line.

**Comment by pmcarrion** [comment]
```
PS C:\Windows\System32> powershell -Command "(Invoke-WebRequest -Uri 'https://api.controld.com/dl' -UseBasicParsing).Content | Set-Content 'ctrld_install.bat'" && ctrld_install.bat $DID forced
        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Name      : Microsoft Windows 11 Pro
OS Version   : 10.0.22000 N/A Build 22000
Arch         : ARM64
CPU          : Apple Silicon
Free RAM     : 3,215 MB / 8,187 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : $DID
Binary URL   : https://assets.controld.com/ctrld/windows/arm64/ctrld.exe
Install Path : "C:\ControlD"
---------------------
- ctrld is already running, this is an upgrade.
- Starting download
- Stopping the running ctrld process
- Replacing the existing binary with the new version
- Checking if ctrld is already in system path
- Launching "C:\ControlD\ctrld.exe
---------------------
Dec 20 06:09:26.000 NTC Reading config: C:\ControlD\ctrld.toml
Dec 20 06:09:26.470 NTC Starting service
Dec 20 06:09:26.501 NTC Generating controld config: C:\ControlD\ctrld.toml
Dec 20 06:09:32.670 NTC Service started
PS C:\Windows\System32> ctrld --version
ctrld version v1.3.0
```

As you can see, "Using Control D" isn't anywhere in the installer output.

**Comment by cuonglm** [comment]
What happen if you call `C:\ControlD\ctrld.exe` directly?

```
C:\ControlD\ctrld.exe --version
```

**Comment by pmcarrion** [comment]
It shows the expected version when called directly.
```
PS C:\Windows\System32> C:\ControlD\ctrld.exe --version
ctrld version v1.3.3
```
That’s odd.

**Comment by cuonglm** [comment]
> It shows the expected version when called directly.
> 
> ```
> PS C:\Windows\System32> C:\ControlD\ctrld.exe --version
> ctrld version v1.3.3
> ```
> 
> That’s odd.

Nope, it's normal. I think you may have old `ctrld` somewhere in your system path, so typing `ctrld` simply using that binary.

If you use powershell, try:

```
where.exe ctrld
```

If you use cmd, try:

```
where ctrld
```

**Comment by pmcarrion** [comment]
From cmd:
```
Microsoft Windows [Version 10.0.22000.2538]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>where ctrld
C:\Users\pmcarrion\ctrld.exe

C:\Windows\system32>
```

From powershell:
```
PowerShell 7.4.0
PS C:\Windows\System32> where.exe ctrld
C:\Users\pmcarrion\ctrld.exe
PS C:\Windows\System32>
```

They have the same file path.

**Comment by cuonglm** [comment]
> From cmd:
> 
> ```
> 
> Microsoft Windows [Version 10.0.22000.2538]
> 
> (c) Microsoft Corporation. All rights reserved.
> 
> 
> 
> C:\Windows\system32>where ctrld
> 
> C:\Users\pmcarrion\ctrld.exe
> 
> 
> 
> C:\Windows\system32>
> 
> ```
> 
> 
> 
> From powershell:
> 
> ```
> 
> PowerShell 7.4.0
> 
> PS C:\Windows\System32> where.exe ctrld
> 
> C:\Users\pmcarrion\ctrld.exe
> 
> PS C:\Windows\System32>
> 
> ```
> 
> 
> 
> They have the same file path.

Yes, and it's different with the actual binary runs by the installer.

Please removing that file and use the one by the installer instead.

**Comment by pmcarrion** [comment]
I removed both and ran the installer again. The issue was solved.
However, I get this message when fetching the version info:
```
PS C:\Windows\System32> ctrld --version
ctrld: The term 'ctrld' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

It does work by invoking it directly.
```
PS C:\Windows\System32> C:\ControlD\ctrld.exe --version
ctrld version v1.3.3
```

Is this expected?

Finally, where do I find the info Yegor requested? It's not in the installer output... 3rd line of what?
https://github.com/Control-D-Inc/ctrld/issues/115#issuecomment-1863520143

**Comment by cuonglm** [comment]
> I removed both and ran the installer again. The issue was solved.
> 
> However, I get this message when fetching the version info:
> 
> ```
> 
> PS C:\Windows\System32> ctrld --version
> 
> ctrld: The term 'ctrld' is not recognized as a name of a cmdlet, function, script file, or executable program.
> 
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> 
> ```
> 
> 
> 
> It does work by invoking it directly.
> 
> ```
> 
> PS C:\Windows\System32> C:\ControlD\ctrld.exe --version
> 
> ctrld version v1.3.3
> 
> ```
> 
> 
> 
> Is this expected?
> 
> 
> 
> Finally, where do I find the info Yegor requested? It's not in the installer output... 3rd line of what?
> 
> https://github.com/Control-D-Inc/ctrld/issues/115#issuecomment-1863520143

Unless you put ctrld binary in your system PATH, invoking with name alone wont work. You have to use full path instead.

I think Yegor mention something else, not the installer output. Probably it's ControlD status page.

**Comment by domy86** [comment]
You may edit an environment variable to use that path `C:\ControlD`...

![image](https://github.com/Control-D-Inc/ctrld/assets/84593035/c11460be-60c3-4312-ab0b-b16e5df53807)

![image](https://github.com/Control-D-Inc/ctrld/assets/84593035/eb567c3c-2a79-4102-8d69-af05ea2f8a81)

![image](https://github.com/Control-D-Inc/ctrld/assets/84593035/72d9a36a-0951-4b65-b04f-6815bc5ee309)

**Comment by yegors** [comment]
Status page is not irrelevant, as the above is the issue. 

The installer was modified a few months ago to write to a common path: C:\ControlD and add this to system path. Old installer used the user directory, so if there is a binary at the old path, WIndows may preference it randomly. Just delete it from the user directory.

After installer runs, and new system path is added, you need to re-open cmd for it to reference it.
