### ISSUE TITLE
How to use ctrld with Synology

### ISSUE THREAD

**Issue by linaspurinis** [Control-D-Inc/ctrld#117]
I installed ctrld on Synology and it runs on port 5354, while Synology DNS runs on 53 port. How to force Synology to use ctrld running on the 5354 port?

root@DS:~# nslookup verify.controld.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
*** Can't find verify.controld.com: No answer

**Comment by domy86** [comment]
You can change a port number in `/etc/controld/ctrld.toml` file or use an automatic setup `sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s xxxxxxxxxx forced'`.

**Comment by yegors** [comment]
@linaspurinis How did you install ctrld? If you use the installer, this shouldn't happen.

**Comment by linaspurinis** [comment]
Hi, @yegors @domy86 I did installed with installer: 

`root@DS:~# sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s xxxxxxxxxx forced'

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : Synology
Arch         : x86_64
CPU          : Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
Free RAM     : 200 MB / 11822 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : 2gffnp45oio
Binary URL   : https://assets.controld.com/ctrld/linux/amd64/ctrld
Install Path : /usr/sbin
---------------------
 - Starting download
 - Making binary executable
 - Launching /usr/sbin/ctrld
---------------------
Dec 20 20:36:31.000 NTC Reading config: /etc/controld/ctrld.toml
Dec 20 20:36:31.305 NTC Starting service
Dec 20 20:36:34.500 NTC Generating controld config: /etc/controld/ctrld.toml
Dec 20 20:36:40.336 NTC Service started
root@DS:~# nslookup verify.controld.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
*** Can't find verify.controld.com: No answer`

**Comment by domy86** [comment]
Hm, I have installed it yesterday on my Synology and everything went fine. Try:

```
rm -f /etc/controld/ctrld.toml
sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s xxxxxxxxxx forced'
```

Have you put some custom toml in control panel? Can you paste the output of:

```
cat /etc/controld/ctrld.toml
ctrld --version
```

**Comment by linaspurinis** [comment]
```
root@DS:~# cat /etc/controld/ctrld.toml
# AUTO-GENERATED VIA CD FLAG - DO NOT MODIFY

[listener]
  [listener.0]
    ip = '0.0.0.0'
    port = 5354

    [listener.0.policy]
      name = 'My Policy'
      rules = [
        {        'captive.apple.com' = []},
        {        'aircanadawifi.com' = []},
        {        'gogoinflight.com' = []},
        {        'southwestwifi.com' = []},
        {        'singaporeair-krisworld.com' = []},
        {        'airborne.gogoinflight.com' = []},
        {        'aainflight.com' = []},
        {        'aa.viasat.com' = []},
        {        'deltawifi.com' = []},
        {        'wifi.delta.com' = []},
        {        'unitedwifi.com' = []},
        {        'shop.ba.com' = []},
        {        'alaskawifi.com' = []},
        {        'flyfi.com' = []},
        {        'wifi.airasia.com' = []},
        {        'wifi.sncf' = []},
        {        'wifi.tgv-lyria.com' = []},
        {        'freewlan.sbb.ch' = []},
        {        'register.onboard.eurostar.com' = []},
        {        'thalysnet.com' = []},
        {        'iceportal.de' = []},
        {        'vvm.mstore.msg.t-mobile.com' = []},
        {        'wifi.inflightinternet.com' = []},
        {        'captive.inflightinternet.com' = []},
        {        'airbornesecure.inflightinternet.com' = []},
        {        'ip.videotron.ca' = []},
        {        'wifi.united.com' = []}
      ]

[network]
  [network.0]
    name = 'Network 0'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    type = 'doh'
    endpoint = 'https://dns.controld.com/2gffnp45oio'
    timeout = 5000
root@DS:~# ctrld --version
ctrld version v1.3.3
```

**Comment by linaspurinis** [comment]
I have Synology DNS running on port 53, so it ok for ctrld  to run on 5354. But how to configure the upstream server for port 5453?

**Comment by domy86** [comment]
NSLOOKUP uses port 53 by default. Try:

```
nslookup -port=5354 google.com
ping google.com
```

**Comment by linaspurinis** [comment]
This do work:
```
root@DS:~# nslookup -port=5354 verify.controld.com
Server:		127.0.0.1
Address:	127.0.0.1#5354

Non-authoritative answer:
verify.controld.com	canonical name = api.controld.com.
Name:	api.controld.com
Address: 147.185.34.1
Name:	api.controld.com
Address: 2606:1a40:3::1
```

But how can I use it with Synology as an Idefault DNS forwarder? And for DHCP?

**Comment by yegors** [comment]
The port appears to be wrong. Do you have a custom config that set it to 5354?  Here is our test DSM, excuse the hostname. 

```
yegor@porn-storage-01:/$ sudo sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s vq7jh8c8pw forced'

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : Synology
Arch         : aarch64
CPU          : ARMv8 Processor rev 4 (v8l)
Free RAM     : 91 MB / 484 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : REDACTED
Binary URL   : https://assets.controld.com/ctrld/linux/arm64/ctrld
Install Path : /usr/sbin
---------------------
 - Detected running process, this is an upgrade
 - Starting download
 - Stopping running process
 - Replacing old binary with the new one
 - Making binary executable
 - Launching /usr/sbin/ctrld
---------------------
Dec 20 14:54:31.000 NTC Reading config: /etc/controld/ctrld.toml
Dec 20 14:54:31.494 NTC Starting service
Dec 20 14:54:34.107 NTC Generating controld config: /etc/controld/ctrld.toml
Dec 20 14:54:39.727 NTC Service started
yegor@porn-storage-01:/$ nslookup popads.net
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   popads.net
Address: 0.0.0.0
Name:   popads.net
Address: ::

yegor@porn-storage-01:/$ sudo netstat -tupln | grep \:53
tcp        0      0 0.0.0.0:5357            0.0.0.0:*               LISTEN      6038/nginx: master
tcp6       0      0 :::5357                 :::*                    LISTEN      6038/nginx: master
tcp6       0      0 :::53                   :::*                    LISTEN      1020/ctrld
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1020/ctrld
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           6232/avahi-daemon:
udp6       0      0 :::5353                 :::*                                6232/avahi-daemon:
udp6       0      0 :::53                   :::*                                1020/ctrld

yegor@porn-storage-01:/$ sudo cat /etc/controld/ctrld.toml
# AUTO-GENERATED VIA CD FLAG - DO NOT MODIFY

[listener]
  [listener.0]
    ip = '0.0.0.0'
    port = 53

    [listener.0.policy]
      name = 'My Policy'
      rules = [
        {        'captive.apple.com' = []},
        {        'aircanadawifi.com' = []},
        {        'gogoinflight.com' = []},
        {        'southwestwifi.com' = []},
        {        'singaporeair-krisworld.com' = []},
        {        'airborne.gogoinflight.com' = []},
        {        'aainflight.com' = []},
        {        'aa.viasat.com' = []},
        {        'deltawifi.com' = []},
        {        'wifi.delta.com' = []},
        {        'unitedwifi.com' = []},
        {        'shop.ba.com' = []},
        {        'alaskawifi.com' = []},
        {        'flyfi.com' = []},
        {        'wifi.airasia.com' = []},
        {        'wifi.sncf' = []},
        {        'wifi.tgv-lyria.com' = []},
        {        'freewlan.sbb.ch' = []},
        {        'register.onboard.eurostar.com' = []},
        {        'thalysnet.com' = []},
        {        'iceportal.de' = []},
        {        'vvm.mstore.msg.t-mobile.com' = []},
        {        'wifi.inflightinternet.com' = []},
        {        'captive.inflightinternet.com' = []},
        {        'airbornesecure.inflightinternet.com' = []},
        {        'ip.videotron.ca' = []},
        {        'wifi.united.com' = []}
      ]

[network]
  [network.0]
    name = 'Network 0'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    type = 'doh'
    endpoint = 'https://dns.controld.com/REDACTED'
    timeout = 5000
yegor@porn-storage-01:/$
```

Installer should put this on port 53, not 5354 as thats only used if there is dnsmasq.

**Comment by domy86** [comment]
Same for me... Maybe something is using port 53?

```
netstat -alptun | grep 53
```

**Comment by linaspurinis** [comment]
Port 53 is used by Synology DNS and DHCP, and I have both. I need DHCP because Synology is my router.

![CleanShot 2023-12-20 at 22 54 56@2x](https://github.com/Control-D-Inc/ctrld/assets/26404490/325592fb-68e8-4739-8e49-e0c5dda793b9)

**Comment by yegors** [comment]
I find it rather puzzling to use a NAS as a router, but OK. 

We only tested this on a stock device, which does not operate a DNS or DHCP server on it. If you're using non-default settings you have 1 of 2 options:

1. Stop the DNS server and use ctrld instead. This is the simplest and most obvious solution. 
2. Manually configure ctrld as the upstream for `named`

**Comment by domy86** [comment]
Nice! I also think that `named` requires certificate, that's one step more.

Another option is to mix ctrld daemon and legacy DNS together. Leave ctrld daemon as it is, activate legacy DNS on that device in Control D dashboard and use provided legacy DNS servers as forwarders in Synology. Then create a scheduled task to ping Google every minute, just to be sure that source IP is being updated.

**Comment by yegors** [comment]
That is by far the worst idea and I recommend this even less than option 2. You should replace named with `ctrld` and call it a day. They do exactly the same thing, except ctrld does it better.

**Comment by domy86** [comment]
I know, we gave him all options, he can choose what suits him the best...

**Comment by linaspurinis** [comment]
Thank you all for helping me to understand how it all works :) I followed post on reddit to disable Synology DHCP port 53:
```
/usr/local/lib/systemd/system/pkg-dhcpserver.service and adding -p 0 to the exec line to disable DNS when dnsmasq starts. 
```
https://www.reddit.com/r/synology/comments/njwdao/comment/j2d23qr/?utm_source=share&utm_medium=web2x&context=3

P.S. I also stopped the Synology DNS service.

Now everything working as expected. Thank you for your help!

**Comment by yegors** [comment]
DHCP wouldn't matter here, as thats a totally separate protocol. You just need to stop the DNS server.

**Comment by linaspurinis** [comment]
@yegors Unfortunately Synology implementation use 53 port with dnsmasq. Before opening this issue I did try to stop DNS service but it didn't help.
