### ISSUE TITLE
Autofill endpoint line | Intune deployment

### ISSUE THREAD

**Issue by domy86** [Control-D-Inc/ctrld#119]
Hi,

In scenario where I would like to use custom toml with more clients, would it be possible to use something like auto filling the endpoint line? I have tried to drop it from a config in control panel but it won't start the service due to an misconfiguration...

```
ctrld start --cd xxxxxxxxxx
Dec 20 17:10:14.000 NTC Reading config: C:\Windows\system32\ctrld.toml
Dec 20 17:10:14.236 NTC Starting service
Dec 20 17:10:14.328 NTC Generating controld config: C:\Windows\system32\ctrld.toml
Dec 20 17:10:15.105 ERR ctrld service may not have started due to an error or misconfiguration, service log:
Dec 20 17:10:15.105 ??? ================================
Dec 20 17:10:15.105 ??? ================================
Dec 20 17:10:15.269 NTC Service uninstalled
```

I know that toml doesn't support variables, so something on a backend side has to be changed to autofill either an endpoint line or a whole upstream section.

The final idea is to create an Intune deployment to switch more clients from legacy DNS to ctrld daemon. With this setup, I'm not sure if it's possible or not.

**Comment by yegors** [comment]
Hi,

If you're using inTune, that suggests you have a business use case, which requires an Organization account. These accounts have the ability to generate provision codes, as per this guide: https://docs.controld.com/docs/microsoft-intune-controld-tutorial

Such codes will auto-create Devices when used.

**Comment by domy86** [comment]
Nice, I will play then, didn't see that tutorial yet, thanks!

But in case of a home use, I have to configure each device manually?

**Comment by yegors** [comment]
Do you use inTune at home? If so, yes. Consumer accounts were not designed for automation.

**Comment by domy86** [comment]
Not at home.

OK, will reply back to your email in case of some problems with business automation.
