### ISSUE TITLE
RT-AC68U support?

### ISSUE THREAD

**Issue by i486** [Control-D-Inc/ctrld#12]
Looks like this utility crashes on RT-AC68U

https://www.snbforums.com/threads/does-dnsfilter-support-dot.82859/post-819409

**Comment by RouterCFW** [comment]
it's a feature coming in march

**Comment by yegors** [comment]
Arm v5 build will work on this router, we're investigating why armv7 does not.

**Comment by cuonglm** [comment]
@i486 It seems that the router does not support hard floating, which is enforced by the go compiler for armv6/armv7: https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/cmd/compile/internal/arm/galign.go;l=18

For example:

```
admin@RT-AC68U-EB18:/tmp/home/root# readelf -a /usr/lib/libpanel.so.6 | grep FP
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
```

If your router supports hard floating, you would see `Tag_ABI_VFP_args: VFP registers ` in the output.

Ref: https://www.cnx-software.com/2013/04/22/how-to-detect-if-an-arm-elf-binary-is-hard-float-armhf-or-soft-float-armel/
