### ISSUE TITLE
Feature request: Cache Flush query

### ISSUE THREAD

**Issue by chr-lei** [Control-D-Inc/ctrld#120]
I'd like to suggest adding a cache flush query feature for ctrld, where sending a query for a specific domain would cause ctrld to flush its cache (either globally or, for maximum cool-ness, just for the querying device's upstream as determined by policies).

A similar feature exists in routedns, where you can specify a domain (like flush.cache) that will then trigger a cache flush without having to connect via SSH and restart the service. See this section of the routedns config guide for more info/possibly better explanation: https://github.com/folbricht/routedns/blob/master/doc/configuration.md#configuration

This would be a nice timesaver in cases where profile rules are changed but ctrld has cached some records with long TTLs, etc.

(Transplanted this suggestion from Discord: https://discord.com/channels/1035992466203099147/1187065927771095151/1187065927771095151)

**Comment by yegors** [comment]
I suppose we can add that.

**Comment by BourbonCrow** [comment]
Yes this would be great this is something I actually miss from nextdns, if I add a item to the white list  the cache gets flushed and I only have to flushdns on my pc and it takes effect right away. Not sure how that works but  it seems to bypass the TTL.
I was using nextdns+nextdns cli on router when this was working.

And now that om on ctrlD instead this is prolly the only thing I'm missing

**Comment by Fail-Safe** [comment]
> Not sure how that works but it seems to bypass the TTL.
> I was using nextdns+nextdns cli on router when this was working.

This was implemented in NextDNS per a request I submitted a while back: https://github.com/nextdns/nextdns/issues/131. This commit is the change that allows for this behavior: https://github.com/nextdns/nextdns/commit/b0a96545cf1538f36f1cdfcc9ee5a84e82eba97d.

**Comment by gniting** [comment]
@yegors is there a way to manually flush the cache?

**Comment by yegors** [comment]
Currently, only using the `restart` command. 

We will add an explicit sub-command when we implement the above.

**Comment by yegors** [comment]
Added in https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.6

**Comment by gniting** [comment]
Is there an example anywhere? The latest release has some interesting new features but no docs or examples that show how to use them.

**Comment by yegors** [comment]
Its in the docs :) 

https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#cache_flush_domains

**Comment by gniting** [comment]
Amazing! Thx!
