### ISSUE TITLE
Some questions about this robust CLI

### ISSUE THREAD

**Issue by viniribeirossa** [Control-D-Inc/ctrld#121]
Hi, guys!

Since I started using the Control D CLI, I've been loving it. It's a very robust CLI!

Thanks again to the Control D developers!!!

I have a few questions because I couldn't find enough information.

**1. Changing Listener Value:**
   If I modify the "listener" value from "0.0.0.0/5354" to another IP address, like "10.10.10.1/5354," my main question is: What's the relationship between "listener" and "network"? If I alter the "listener" values, what purpose does "network" serve?

**2. MAC Isolation on Different Networks:**
   I added my phone's MAC to my profile, but my router has multiple VLANs, including one for guests. When connecting to the guest network, my profile remains active. Is there a way to isolate my MAC only to a preferred network?

**3. CLI Cache:**
   Does the CLI have its cache? Does it utilize Dnsmasq's cache, or does it operate with its own cache server? If it has its own cache server, is it active by default, or do I need to activate it?

**Comment by yegors** [comment]
1. Listener is what receives DNS queries. "network" is used for steering DNS queries FROM different networks. https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#network
2. If your phones MAC address is static, it shouldn't matter which vlan/SSID you're on. Be mindful that Android randomizes the MAC by default, so you should disable this for your SSIDs in order for it to remain static. Otherwise MAC based policies won't work. 
3. It has an internal cache, which is OFF by default: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#cache_enable

**Comment by viniribeirossa** [comment]
I use the MAC address of the device on my main network. Could I isolate these rules for this IP address when connecting to the guest network?

Out of curiosity: Can I disable CLI logging? I use OpenWrt and would like to turn off the logs. Is that possible?

**Comment by yegors** [comment]
Yes, you can. See docs: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#policy

Logs: Same thing, this is in the docs:  https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#log_level

**Comment by viniribeirossa** [comment]
I think you didn't understand.

I've tried all the rules set in the policies, but when I connect to the guest network or any other, I don't want to have these rules. For example, my guest network routes to Cloudflare, but for my MAC address, it keeps redirecting to ControlD/NextDNS. I only want to have these rules within the LAN network.

Regarding the logs, I couldn't find the option to turn them off.

**Comment by viniribeirossa** [comment]
I'm using OpenWrt and have tried all log levels; however, it seems that they do not change, always the same behavior. I set it to 'fatal' or 'error,' and debug, info, notice still appear, not limited to what I selected.

Logs are spamming. Is this normal behavior?

**Comment by cuonglm** [comment]
> I'm using OpenWrt and have tried all log levels; however, it seems that they do not change, always the same behavior. I set it to 'fatal' or 'error,' and debug, info, notice still appear, not limited to what I selected.
> 
> 
> 
> Logs are spamming. Is this normal behavior?
> 
> 
> 
> ![Screenshot_2023-12-23-15-44-31-398_com android chrome](https://github.com/Control-D-Inc/ctrld/assets/57050698/aaf34425-cdcb-4dac-a3b6-14159e82a82b)
> 
> 

What command did you run after setting log level?

To disable, set `log_level` to `disabled`.

**Comment by viniribeirossa** [comment]
Then I ran the command `ctrld restart`

**Comment by viniribeirossa** [comment]
No 

I use the two log openwrt command

`logread -f ctrld` or `cat /temp/ctrld.log`

**Comment by viniribeirossa** [comment]
Any?

**Comment by yegors** [comment]
Your service is still running in debug mode somehow. You don't need to define logging params at all to disable it. 

Provide output from: `ps aux | grep ctrld` or `ps | grep ctrld` if first command doesn't return anything.

**Comment by viniribeirossa** [comment]
```
1618 root      601m S    /usr/sbin/ctrld run --lo
21778 root      1312 S    grep ctrld
```

**Comment by cuonglm** [comment]
@viniribeirossa `--log` flag implies debug level if log level is empty. Please specify log level or using `--silent`.

**Comment by viniribeirossa** [comment]
As mentioned in the conversation, even if I specify in the configuration file, it doesn't change anything. 

What command can I try using `--silence`?

**Comment by cuonglm** [comment]
> As mentioned in the conversation, even if I specify in the configuration file, it doesn't change anything. 
> 
> 
> 
> What command can I try using `--silence`?

Please show us the command and config file that you use.

It's `ctrld run --silent`

**Comment by viniribeirossa** [comment]
@cuonglm this

https://github.com/Control-D-Inc/ctrld/issues/121#issuecomment-1868486864

**Comment by viniribeirossa** [comment]
I tried the command you gave me, but the behavior didn't change

**Comment by viniribeirossa** [comment]
I believe there may be a problem with openwrt router, because I only installed it using the command you provided

**Comment by viniribeirossa** [comment]
I had to uninstall the CLI, it registered 55MB, it would take a long time and my router would always crash

**Comment by viniribeirossa** [comment]
Hello, friends and developers of this amazing CLI.

Last night, I had some time and backed up my router configurations, then reinstalled the Control D CLI calmly, and everything worked perfectly!

I apologize again to my friends!
