### ISSUE TITLE
Firewalla with NextDNS 

### ISSUE THREAD

**Issue by cirrusflyer** [Control-D-Inc/ctrld#122]
I set this up:

https://github.com/Control-D-Inc/ctrld/wiki/NextDNS-Mode

But the service seems to hang after an hour or so.  This has happened multiple times since setting it up tonight.  It works great when it's working, but then it stops working and I see a "connection refused" to the Firewalla IP message with running a dig command on the Firewalla.

I'm seeing this in the syslog:

Dec 25 23:35:31 localhost bash[2008190]: dnsmasq: illegal repeated keyword at line 6 of /home/pi/.firewalla/config/dnsmasq_local/ctrld
Dec 25 23:35:31 localhost bash[2008190]: file /home/pi/.firewalla/run/dns_proxy.strict_new.bf.data can't be opened

**Comment by cuonglm** [comment]
Thanks for reporting.

Sounds like something is triggered on Firewalla causing a conflict with the cache-size that is added by ctrld.

**Comment by cirrusflyer** [comment]
Maybe this helps:  https://www.reddit.com/r/pihole/comments/45v71b/pihole_dnsmasq_cachesize_directive/

**Comment by cuonglm** [comment]
> Maybe this helps:
> 
> 
> 
> https://www.davekb.com/browse_computer_tips:dnsmasq_illegal_repeated_keyword_at_line_n_of_etc_dnsmasq.d_caching-dns.conf:txt
> 
> 
> 
> https://www.reddit.com/r/pihole/comments/45v71b/pihole_dnsmasq_cachesize_directive/

Yes, we know that there could be a conflict. But the thing is that Firewalla only trigger "something" after ctrld running for a while, which causes the conflict happens.

We have a plan to tackle this in future releases.

**Comment by yegors** [comment]
I have a test Firewalla device on my desk, never encountered this issue after many weeks of operations.  @cirrusflyer Do you know what exactly triggers this to happen? Can you provide steps to reproduce?

In the mean time, you can also run ctrld in this mode (article is for pfsense, but its the same): https://github.com/Control-D-Inc/ctrld/wiki/pfSense-and-OPNsense-Operations-Guide#dont-touch-my-configs

**Comment by cirrusflyer** [comment]
I've removed the cache-size line from the file, and I'm seeing how long things are stable.  Maybe just coincidence as well.  Going on a couple hours now.

**Comment by cirrusflyer** [comment]
Also, see here:  https://www.reddit.com/r/firewalla/comments/udh52a/firerouter_dns_restarting_often/

Seems the restart every couple minutes is normal.

**Comment by yegors** [comment]
We'll get this addressed in the next version.

**Comment by yegors** [comment]
This is done and available in v1.3.4

**Comment by cirrusflyer** [comment]
Great.  Remind me how to update Firewalla with NextDNS?

**Comment by yegors** [comment]
Re-run the installer command from https://github.com/Control-D-Inc/ctrld/wiki/NextDNS-Mode

It will upgrade the instance.
