### ISSUE TITLE
Please add support for Netgear Orbi RBK50 (Voxel Firmware)

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#123]
Please add support for Netgear Orbi RBK50 (mesh network / 1 router + 2 satellites).

The regular firmware doesn’t support SSH, but the alternative firmware ([Voxel](https://www.voxel-firmware.com/Downloads/Voxel/html/orbi.html))) does.

Voxel Firmware supports several Negear hardware - Orbi RBK50/LBR and R7500/R7800/R9000/R8900.

When accessing the router via SSH, I see this:

```
BusyBox v1.24.1 (2023-10-19 11:35:26 UTC) built-in shell (ash)
Enter 'help' for a list of built-in commands.


  __        __   _                             _
  \ \      / /__| | ___ ___  _ __ ___   ___   | |_ ___
   \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \  | __/ _ \
    \ V  V /  __/ | (_| (_) | | | | | |  __/  | || (_) |
     \_/\_/ \___|_|\___\___/|_| |_| |_|\___|   \__\___/

    ___       _     _    ____  ____  _  ______   ___  _
   / _ \ _ __| |__ (_)  |  _ \| __ )| |/ / ___| / _ \| |
  | | | | '__| '_ \| |  | |_) |  _ \| ' /|___ \| | | | |
  | |_| | |  | |_) | |  |  _ <| |_) | . \ ___) | |_| |_|
   \___/|_|  |_.__/|_|  |_| \_\____/|_|\_\____/ \___/(_)


admin@RBR50:/$
```

BusyBox is Linux-based so it should be simple to support via the installer.

Thanks.

**Comment by yegors** [comment]
What happens when you run the installer?

**Comment by pmcarrion** [comment]
I get a sudo error when using the admin user:

```
BusyBox v1.24.1 (2023-10-19 11:35:26 UTC) built-in shell (ash)
Enter 'help' for a list of built-in commands.


  __        __   _                             _
  \ \      / /__| | ___ ___  _ __ ___   ___   | |_ ___
   \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \  | __/ _ \
    \ V  V /  __/ | (_| (_) | | | | | |  __/  | || (_) |
     \_/\_/ \___|_|\___\___/|_| |_| |_|\___|   \__\___/

    ___       _     _    ____  ____  _  ______   ___  _
   / _ \ _ __| |__ (_)  |  _ \| __ )| |/ / ___| / _ \| |
  | | | | '__| '_ \| |  | |_) |  _ \| ' /|___ \| | | | |
  | |_| | |  | |_) | |  |  _ <| |_) | . \ ___) | |_| |_|
   \___/|_|  |_.__/|_|  |_| \_\____/|_|\_\____/ \___/(_)


admin@RBR50:/$ sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s $DID forced
'

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

Please re-run this command with root/system permissions.
admin@RBR50:/$ sudo sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s $DID f
orced'
-ash: sudo: not found
admin@RBR50:/$ 
```

And this error when using the root user:

```
root@192.168.50.2's password: 


BusyBox v1.24.1 (2023-10-19 11:35:26 UTC) built-in shell (ash)
Enter 'help' for a list of built-in commands.


  __        __   _                             _
  \ \      / /__| | ___ ___  _ __ ___   ___   | |_ ___
   \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \  | __/ _ \
    \ V  V /  __/ | (_| (_) | | | | | |  __/  | || (_) |
     \_/\_/ \___|_|\___\___/|_| |_| |_|\___|   \__\___/

    ___       _     _    ____  ____  _  ______   ___  _
   / _ \ _ __| |__ (_)  |  _ \| __ )| |/ / ___| / _ \| |
  | | | | '__| '_ \| |  | |_) |  _ \| ' /|___ \| | | | |
  | |_| | |  | |_) | |  |  _ <| |_) | . \ ___) | |_| |_|
   \___/|_|  |_.__/|_|  |_| \_\____/|_|\_\____/ \___/(_)


root@RBR50:~# sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s $DID forced'

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : Linux
Arch         : armv7l
CPU          : ARMv7 Processor rev 5 (v7l)
Free RAM     : 319 MB / 495 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : $DID
Binary URL   : https://assets.controld.com/ctrld/linux/armv7/ctrld
Install Path : /usr/local/bin
---------------------
Install path /usr/local/bin does not exist. Please create it manually and try again.
root@RBR50:~# 
```

**Comment by yegors** [comment]
Download the binary manually into some persistent directory and run it manually: `./ctrld start --cd RESOLVER_ID_HERE -vv`

What happens then?

**Comment by pmcarrion** [comment]
I am not sure how to push the ctrld binary into the router. It doesn’t support SFTP.

**Comment by yegors** [comment]
wget or curl the binary from Github.

**Comment by pmcarrion** [comment]
```
root@RBR50:~# ./ctrld start --cd $DID -vv
-ash: ./ctrld: Permission denied

root@RBR50:~# sudo ./ctrld start --cd $DID -vv
-ash: sudo: not found
```

**Comment by cuonglm** [comment]
@pmcarrion You should do `chmod +x ctrld` for binary downloaded from https://assets.controld.com/ctrld/linux/armv7/ctrld first.

You are already root user, so don't have to use sudo.

@yegors Sounds like we need to update the installer script to work with busybox sh.

**Comment by yegors** [comment]
I ordered this device, I'll need to see what I can hook into to determine that this is an Orbi branded router, and set the install path to what is valid there.

**Comment by pmcarrion** [comment]
> I ordered this device, I'll need to see what I can hook into to determine that this is an Orbi branded router, and set the install path to what is valid there.

Perhaps this helps:

```
root@RBR50:~/dist/ctrld_1.3.3_linux_armv7# uname -a
Linux RBR50 3.14.77 #1 SMP PREEMPT Thu Oct 19 12:26:33 UTC 2023 armv7l IPQ4019 GNU/Linux
```

There's an issue... the router doesn’t have Internet connection after starting ctrld.
I did some ping tests:
```
root@RBR50:~/dist/ctrld_1.3.3_linux_armv7# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=115 time=37.757 ms
64 bytes from 8.8.8.8: seq=1 ttl=115 time=37.875 ms
64 bytes from 8.8.8.8: seq=2 ttl=115 time=38.028 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 37.757/37.886/38.028 ms

root@RBR50:~/dist/ctrld_1.3.3_linux_armv7# ping dns.controld.com
ping: bad address 'dns.controld.com'
root@RBR50:~/dist/ctrld_1.3.3_linux_armv7# 
```

The Internet connection returned after uninstalling ctrld:

```
root@RBR50:~/dist/ctrld_1.3.3_linux_armv7# ./ctrld uninstall -vv
Jan  3 03:12:01.000 INF loading config file from: /etc/controld/ctrld.toml
Jan  3 03:12:01.999 DBG Restoring DNS for interface iface=br0
Jan  3 03:12:02.197 DBG could not exchange DHCPv6 error="IA_NA cannot be nil in ADVERTISE when building REQUEST"
Jan  3 03:12:02.198 DBG dns: [rc=unknown ret=direct]
Jan  3 03:12:02.199 DBG dns: using "direct" mode
Jan  3 03:12:02.203 DBG start watching /etc/resolv.conf file
Jan  3 03:12:02.242 DBG Restoring DNS successfully iface=br0
Jan  3 03:12:02.242 DBG Router cleanup
Jan  3 03:12:02.243 NTC Service uninstalled
```

**Comment by yegors** [comment]
Yes, thanks. Can you tell me where the program binaries are? Are then in `/usr/sbin/`?

**Comment by pmcarrion** [comment]
> Can you tell me where the program binaries are? Are then in /usr/sbin/

There are several locations:
/usr/sbin/
/usr/bin/
/bin/
/sbin/

> is it writable and persistent between reboots?

The root home folder is writable and persistent. ctrld is installed there.
Do you have a command to test the other folders?

**Comment by yegors** [comment]
Write any random file to /usr/sbin/ and restart the router. Is the file still there?

**Comment by pmcarrion** [comment]
Both the text file in /usr/sbin/ and the Control D files from the root home folder are gone after a reboot.

I am not sure why it also disappeared from the root home folder today.

**Comment by yegors** [comment]
Then this suggests this is not a persistent place to put stuff. There must be another directory that persists across reboots. 

Could be:
- /data/
- /jffs/

Or some other one.

**Comment by pmcarrion** [comment]
I'm searching for folders that are writable and persistent between reboots.
I also asked for the firmware developer's input.

Meanwhile, here's more information about the router and the Voxel Firmware.
https://www.netgear.com/home/wifi/mesh/rbk53/
https://www.voxel-firmware.com/Downloads/Voxel/html/orbi.html
https://www.voxel-firmware.com/Downloads/Voxel/readme.pdf
https://github.com/SVoxel/ORBI-RBK50
https://www.snbforums.com/threads/custom-firmware-build-for-orbi-rbk50-rbk53-rbr50-rbs50-v-9-2-5-2-31sf-hw.87272/

**Comment by cuonglm** [comment]
@pmcarrion Thanks for helping on this.

We are able to make thing works, but currently facing the same issue with yours: there's no persistent storage after reboot, everything ctrld setup, and the ctrld binary itself was gone.

We could see the problem is `bitdefender`, which will wipe out everything and restore router to previous ctrld installed state. I could not find any documentation from Netgear Orbi for how to disable it.

**Comment by cuonglm** [comment]
> @pmcarrion Thanks for helping on this.
> 
> We are able to make thing works, but currently facing the same issue with yours: there's no persistent storage after reboot, everything ctrld setup, and the ctrld binary itself was gone.
> 
> We could see the problem is `bitdefender`, which will wipe out everything and restore router to previous ctrld installed state. I could not find any documentation from Netgear Orbi for how to disable it.

Don't mind, we figured thing out.

**Comment by yegors** [comment]
Added support in https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.6

However you have to store the binary in `/mn/bitdefender/controld/*` as all other paths don't survive reboots.
