### ISSUE TITLE
Enhancement: Allow for a shared cache among local ctrld instances

### ISSUE THREAD

**Issue by Kreeblah** [Control-D-Inc/ctrld#126]
I'm currently waiting for a few Raspberry Pis in the mail to set up to run `ctrld`, but once they arrive, I plan on setting them up with identical configurations for HA purposes.  But, it'd be nice if they shared a cache for DNS entries (particularly for situations where the option to serve stale entries is enabled, as it could yield different results depending on which host was reached).

So, I'd like to propose adding an option to allow configuring multiple local instances to share a cache.  Something like Redis could be an option, but it'd kind of be a pain to set up a separate software stack just for DNS (especially as a cluster for HA), so maybe allow a configuration option to allow the instances to identify each other by IP address and then they can elect a node to hold the cache for as long as that node continues to be available or some such?

**Comment by yegors** [comment]
I fail to see the point of adding such complexity, all for the sake of a cache. Cache is exactly that - a cache, and should not be used with TTLs higher than 3600, as it can break some sites if it's set any higher than that. Running 2 ctrld processes on the same machine is completely pointless, and having a remote Redis instance just to serve cached responses is a massive overkill, building master election mechanism is even more crazy.

**Comment by Kreeblah** [comment]
I'm not talking about two instances on the same machine, but two instances on separate machines on the same local network.  But, if it's more complexity than is desired for the project, that's fair.
