### ISSUE TITLE
Unifi UDM Pro 3.x failed startup "repeated keyword"

### ISSUE THREAD

**Issue by dpackham** [Control-D-Inc/ctrld#127]
when trying to make changes to the "legacy" DNS servers in the unifi UI I get these errors on the CLI

root@unifithe:/etc/controld# 2024 Jan  5 10:01:19 unifit illegal repeated keyword at line 6 of /tmp/dnsmasq.conf.d-95b4_645d_e193_ad42//zzzctrld.conf
2024 Jan  5 10:01:19 unifi FAILED to start up
2024 Jan  5 10:01:19 unifi illegal repeated keyword at line 6 of /tmp/dnsmasq.conf.d-24d1_928c_2810_dceb//zzzctrld.conf
2024 Jan  5 10:01:19 unifi FAILED to start up

Contents of file
# GENERATED BY ctrld - DO NOT MODIFY
no-resolv
server=127.0.0.1#5354
add-mac
add-subnet=32,128
cache-size=0

Not sure where the dupe is as its autogenerated

**Comment by dpackham** [comment]
OK cool. was just about to add that IF I stop the controlD service I can make those changes and then restart the service back up.  Ill try the dev version.

**Comment by yegors** [comment]
You can get the latest dev build that solves the above issue here (I forget which arch it uses as I'm not near the test device right now):

https://dl.controld.dev/linux-arm64/ctrld
https://dl.controld.dev/linux-amd64/ctrld

**Comment by yegors** [comment]
This issue is resolved in v1.3.4
