### ISSUE TITLE
Launching ctrld on a Raspberry Pi 5 from the installer results in a segmentation fault

### ISSUE THREAD

**Issue by Kreeblah** [Control-D-Inc/ctrld#128]
I have a new Raspberry Pi 5 that I just flashed the 64-bit Raspberry Pi OS Lite image to using the Raspberry Pi imager and then updated.  Other than that, nothing has been done to the software.  Following that, I switched to root, and did this:

```
root@dns1:~# sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)"'

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : debian
OS Version   : 12 (bookworm)
Arch         : aarch64
CPU          : Cortex-A76
Free RAM     : 7782 MB / 8053 MB
---------------------
|  Install Details  |
---------------------
Binary URL   : https://assets.controld.com/ctrld/linux/arm64/ctrld
Install Path : /usr/local/bin
---------------------
Install binary and run it? (y/n): y
 - Starting download
 - Making binary executable
 - Launching /usr/local/bin/ctrld
---------------------
Segmentation fault
root@dns1:~# ctrld
Segmentation fault
```

Building the 1.3.3 code from source (from the ZIP file of the source on the 1.3.3 release), however, results in a binary that runs fine.

Also, something I discovered while doing this is that some of the dependencies require Go 1.20, so it might make sense to list that as the minimum version for building `ctrld`.

**Comment by cuonglm** [comment]
The binary downloaded by the installer is packed with upx. It's probably the culprit.

What happen if you unpacked the binary then run it?

**Comment by cuonglm** [comment]
> Also, something I discovered while doing this is that some of the dependencies require Go 1.20, so it might make sense to list that as the minimum version for building ctrld.

The minimum go version is specified in go.mod file. But sounds like we forgot updating the README.md to reflect that.

**Comment by Kreeblah** [comment]
Ah, yeah, running it through `upx -d` results in it running.  And, yeah, I got 1.19 from the readme.

**Comment by Kreeblah** [comment]
This still seems to be an issue on the 1.3.4 release, so it doesn't appear to be unique to the 1.3.3 binary.

**Comment by cuonglm** [comment]
> This still seems to be an issue on the 1.3.4 release, so it doesn't appear to be unique to the 1.3.3 binary.

Yes, we are narrowing the problem, and it seems to be an issue with upx.

Could you please try installing using .dev domain and see if it worked? Thank you.

**Comment by Kreeblah** [comment]
Ah, yeah, I do understand that it's an issue with upx.  I wanted to mention that since it doesn't seem to be a quirk of the 1.3.3 binary that upx is running into when it tries to compress it (in case that was relevant info).

As for the .dev domain binary, that does seem to work directly from the installer.  Looks like I'm running `ctrld version dev-267a1a5` on the host I ran that installation from.

**Comment by cuonglm** [comment]
@Kreeblah Could you please try with .dev domain and see if the issue is resolved?

Thank you.

**Comment by Kreeblah** [comment]
I just updated to 1.3.5, and the release binary works just fine for me on my Raspberry Pi 5 hosts now.  I think this can be closed.

**Comment by cuonglm** [comment]
> I just updated to 1.3.5, and the release binary works just fine for me on my Raspberry Pi 5 hosts now. I think this can be closed.

Thanks for confirming.
