### ISSUE TITLE
CtrldD fails on Opnsense

### ISSUE THREAD

**Issue by kalpik** [Control-D-Inc/ctrld#129]
Since yesterday, Ctrld demon on my Opnsense firewall fails, causing Internet to go down. When I check status, it says:

root@OPNsense:~ # ctrld status
Jan  9 19:13:44.000 ERR the service is not installed

I have to then reinstall the daemon. This has happened twice already now. Any ideas why this might be happening?

Thanks

**Comment by yegors** [comment]
Sounds like something uninstalled the service on your device, you can check the state if this happens again like so: https://github.com/Control-D-Inc/ctrld/wiki/Troubleshooting-Guide

The service will self-uninstall only under a single condition: You removed the Control D device from the WEB GUI that was used on the router. Did you do that?

**Comment by kalpik** [comment]
Thanks, I'll check the guide next time this happens. And to answer your question, no, I didn't remove the device. In fact, nothing was changed at all in the web gui.

**Comment by yegors** [comment]
Then check the logs on your system and use the troubleshooting guide to check machine state if it happens again. Something killed and uninstalled the service manually, which would leave the machine in broken state as the `uninstall` command would self-cleanup and return the router to original state (working DNS).

**Comment by kalpik** [comment]
Yep, very strange indeed, considering this is my opnsense box, where I don't even login. But I will keep an eye on it and report back. Thanks!

**Comment by kalpik** [comment]
Okay, so this happened again, The troubleshooting steps didn't help, as ctrld wasn't running, which I already knew. I don't know why and how this gets uninstalled.

For now, I deleted old device from the web console, and created a new one, and configured that on OPNSense. Let's see if this works, else I'll just have to use control d directly via unbound, and not use the ctrld cli. It's a shame, but I have no idea what's happening.

**Comment by yegors** [comment]
A device swap is unlikely to have any impact. What was the output from all the suggested commands in the troubleshooting guide? 

Did you check the system logs for the router itself? It should tell you when and why the process was stopped.

**Comment by kalpik** [comment]
Well, the troubleshooting guide expects ctrld to be installed, but apparently it gets uninstalled, so the guide just doesn't help. I can only follow the guide if I install ctrld again. And if I install it again, then everything works, so the guide is not helful then.

I checked general logs of OPNsense, and I don't see anything about the ctrld service getting uninstalled. For now, I have given up on ctrld daemon, and I'm using DNS over TLS directly via unbound. Will miss client information on the web console, but it's way better than not having internet intermittently.

**Comment by gniting** [comment]
Weird indeed. I am running ctrld on opnsense for months now, no issues at all. Works like a charm.

@kalpik Let me know if you want me to share elements of my opnsense setup in case it helps nail down the issue.

**Comment by kalpik** [comment]
Thanks, that would be helpful. To be fair, I had also been using this for months without any issues. But now somehow the ctrld service gets uninstalled.

**Comment by gniting** [comment]
> Thanks, that would be helpful. To be fair, I had also been using this for months without any issues. But now somehow the ctrld service gets uninstalled.

Let me know what you need from me.

**Comment by kalpik** [comment]
> > Thanks, that would be helpful. To be fair, I had also been using this for months without any issues. But now somehow the ctrld service gets uninstalled.
> 
> Let me know what you need from me.

To be honest, I'm not sure what would help here. My issue is that the ctrld service gets uninstalled automatically somehow. The installation is using the standard way. Unless you're doing something else to install ctrld, I don't think there's anything that can help?

**Comment by kalpik** [comment]
* Check if ctrld is running: it's not, as the service is not there anymore
* Check listeners: no listeners for ctrld as the service is not there anymore
* Check service: service is not there, and therefore not responding to DNS queries
* Check resolv.conf: resolv.conf is the one generated by ctrld, but nothing is listening on port 53 as the service is uninstalled, and therefore not running.
* Debug launch: I did not try this.

**Comment by yegors** [comment]
Full debug mode with a log file being written would be very useful. End of the log especially to see what is killing the process on your box. 

I'm assuming you have more than 64MB of RAM here, and this is not an OOM condition? Such events would be in the system log as well, which you should grep for "ctrld".

**Comment by kalpik** [comment]
Hmm, I'll try to get a debug log. And no, it's not an OOM situation. It's a 16GB mini PC box running *just* OPNsense, so there's enough RAM. Also, the service is not killed, but uninstalled. That's the strange part.

**Comment by cuonglm** [comment]
@kalpik If debug log won't tell anything, could you please try these steps:

- `ctrld start --cd=<your UID> -vv --log=/path/to/your_log`.
- Waiting the command run ok.
- `ctrld start --config=/etc/controld/ctrld.toml -vv --log=/path/to/your_log`.

Then check if the problem occurs again.

**Comment by kalpik** [comment]
And as you see, ctrld restart works, but stop and start doesn't work. And if you see it's the ctrld start command that uninstalls the service.

**Comment by cuonglm** [comment]
@kalpik `ctrld start` is not what you want after `ctrld stop`, you should do `ctrld restart` to starts ctrld again with the same arguments.

**Comment by kalpik** [comment]
> @kalpik `ctrld start` is not what you want after `ctrld stop`, you should do `ctrld restart` to starts ctrld again with the same arguments.

Okay, that's a bit confusing, to be honest, but yes, you're right. After stop, restart works.

I then understood what was going wrong for me. I am using monit to restart ctrld service in case DNS resolution fails. And there, I was using stop and then start, which was probably causing this. I have now changed the command to stop and then restart. I will keep an eye on this, but thanks a lot to everyone for their help and patience with this :)

**Comment by cuonglm** [comment]
@kalpik yes, `ctrld start` does more things other than just starting ctrld like system service manager. From help:

```
./ctrld service --help
Manage ctrld service

Usage:
  ctrld service [command]

Available Commands:
  start       Install and start the ctrld service
  stop        Stop the ctrld service
  restart     Restart the ctrld service
  reload      Reload the ctrld service
  status      Show status of the ctrld service
  uninstall   Stop and uninstall the ctrld service
  interfaces  Manage network interfaces

Flags:
  -h, --help   help for service

Global Flags:
  -s, --silent          do not write any log output
  -v, --verbose count   verbose log output, "-v" basic logging, "-vv" debug level logging

Use "ctrld service [command] --help" for more information about a command.
```

You can see what `start` does: "Install and start the ctrld service".

Probably we should add a note somewhere to document this behavior.

**Comment by kalpik** [comment]
Yep, I think adding this somewhere in the documentation would help. As I would expect (without having to read the documentation) that start starts it and stop stops it :)

**Comment by kalpik** [comment]
Maybe the start command, if supplied with no arguments could start the service with existing configuration?

**Comment by cuonglm** [comment]
> Maybe the start command, if supplied with no arguments could start the service with existing configuration?

I'm not sure it's good:

- That would adds more behaviors (edge case) for start command.
- We still have to document that behavior, so users still need to read the documentation.

`ctrld` is not a system service manager, so its "start" command may not behave the same as service manager "start" command.

**Comment by yegors** [comment]
@kalpik Please download this version overwriting ctrld in the install path: https://dl.controld.dev/freebsd-amd64/ctrld

And give it a shot again. You start it with `ctrld start --cd RESOLVER_ID_HERE`

Does it randomly die now?

**Comment by cuonglm** [comment]
> I then understood what was going wrong for me. I am using monit to restart ctrld service in case DNS resolution fails. And there, I was using stop and then start, which was probably causing this. I have now changed the command to stop and then restart. I will keep an eye on this, but thanks a lot to everyone for their help and patience with this :)

@kalpik could you please give us your monit config?

We want to know whether `ctrld` is killed unexpectedly then monit starts it or something else killed ctrld.

**Comment by kalpik** [comment]
> @kalpik Please download this version overwriting ctrld in the install path: https://dl.controld.dev/freebsd-amd64/ctrld
> 
> And give it a shot again. You start it with `ctrld start --cd RESOLVER_ID_HERE`
> 
> Does it randomly die now?

So far, even with the stable version, it hasn't died on me yet.

> > I then understood what was going wrong for me. I am using monit to restart ctrld service in case DNS resolution fails. And there, I was using stop and then start, which was probably causing this. I have now changed the command to stop and then restart. I will keep an eye on this, but thanks a lot to everyone for their help and patience with this :)
> 
> @kalpik could you please give us your monit config?
> 
> We want to know whether `ctrld` is killed unexpectedly then monit starts it or something else killed ctrld.

My Monit config basically looks to see if my FW is accepting connections on port 53, and if not, it restarts ctrld. But since I fixed my restart, ctrld hasn't died on me yet (I checked monit logs to confirm this). If it dies again, I will post it here, and we can investigate more.

**Comment by cuonglm** [comment]
@kalpik thanks for confirmation!

**Comment by yegors** [comment]
New version is released - v1.3.4.

I recommend re-running the installer which should prevent the process from ever dying.

**Comment by kalpik** [comment]
Okay, ctrld failed again, monit restarted it via ctrld restart, but DNS was still down on my network. I did a service re-install, and now it works again. Next time this happens, I will troubleshoot more.

![image](https://github.com/Control-D-Inc/ctrld/assets/481869/ffe16c0d-7d00-462c-aa90-c1ffe9c39ac0)

**Comment by cuonglm** [comment]
@kalpik Did you upgrade to v1.3.4?

With new version, you don't need monit at all. Further, the test and restart seems to happen at the same time, which can explain why the Resource temporarily unavailable.

**Comment by kalpik** [comment]
> @kalpik Did you upgrade to v1.3.4?
> 
> With new version, you don't need monit at all. Further, the test and restart seems to happen at the same time, which can explain why the Resource temporarily unavailable.

Yes, I upgraded to 1.3.4 the day it was released. The restart happens after the test. The weird thing is that it continues to work for a few days, and suddenly fails. Not sure why. Could it be related to some blips on the controld network? Anyway, I will investigate more, and post back any findings.

**Comment by kalpik** [comment]
It just failed again. It seems ctrld is running, but not responding to DNS queries?

![image](https://github.com/Control-D-Inc/ctrld/assets/481869/e5fa11db-7acb-4243-95e0-58263df3e75c)

![image](https://github.com/Control-D-Inc/ctrld/assets/481869/74201973-223e-44df-af2d-48daaecff73d)

**Comment by kalpik** [comment]
I did a start with my config. Got a weird error the first time, but the second time it worked, and now I can resolve DNS.

![image](https://github.com/Control-D-Inc/ctrld/assets/481869/f55795cf-13c0-4333-8c1b-011f49a82c9c)

![image](https://github.com/Control-D-Inc/ctrld/assets/481869/92f5e84e-9d36-4300-aa75-a4cdd8ee1c2b)

**Comment by cuonglm** [comment]
Could you resolve query on OPNsense itself?

Please run `host popads.net` on OPNsense server next time when it failed.

Also could you please gather ctrld log next time?

**Comment by kalpik** [comment]
I will check, thanks. I have already started ctrld with logs enabled, so will definitely gather those as well.
