### ISSUE TITLE
IPv6 listener

### ISSUE THREAD

**Issue by ilium007** [Control-D-Inc/ctrld#131]
I have looked through the docs but couldn't find an example using an IPv6 listener? Can ctrld listen on an IPv6 interface?

**Comment by ilium007** [comment]
I tried this and it worked - now I just need to be able to specify the IPv4 as well.

```
[listener]
  [listener.0]
    ip = '::0'
    port = 53
```

**Comment by DanielSpindler83** [comment]
@ilium007 I am interested in your thoughts about https://github.com/Control-D-Inc/ctrld/issues/146
Thanks
