### ISSUE TITLE
-sh: ctrld: not found

### ISSUE THREAD

**Issue by fdfytr** [Control-D-Inc/ctrld#132]
Installed on asusmerlin via ssh

```
Install Path : /jffs/controld
---------------------
 - Detected running process, this is an upgrade
 - Starting download
 - Stopping running process
 - Replacing old binary with the new one
 - Making binary executable
 - Launching /jffs/controld/ctrld
---------------------
Jan 14 12:31:01.000 NTC Reading config: /jffs/controld/ctrld.toml
Jan 14 12:31:01.196 NTC Starting service
Jan 14 12:31:01.344 NTC Generating controld config: /jffs/controld/ctrld.toml
Jan 14 12:31:08.007 NTC Service started
```

getting this

```
PATH-AC86U-95C8:/tmp/home/root# ctrld -h
-sh: ctrld: not found
```

**Comment by fdfytr** [comment]
not sure if it is relevant but see this in systemlogs
`RT-AC86U-95C8 kernel: ctrld[11188]: syscall 439`

**Comment by yegors** [comment]
Its not in your system path, you have to use the absolute path: /jffs/controld/ctrld

**Comment by fdfytr** [comment]
i could not cd into /jffs/controld/ctrld; nextdns manages to use commands with absolute path btw

**Comment by yegors** [comment]
`/jffs/controld/ctrld` is not a directory, it's an absolute path to a binary. You have to cd into `/jffs/controld/`
