### ISSUE TITLE
Installation on OPNsense with custom config (Wiki)

### ISSUE THREAD

**Issue by dav-fr** [Control-D-Inc/ctrld#133]
Hi,
I had some trouble installing ctrld on OPNsense following the Wiki:

Quick install works fine (```# sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -- -s RESOLVER_ID forced'```)

Problem is when customizing config. As explained in the wiki, user is now responsible for listener conflicts, ```ctrld start``` won't work because unbound is running.
I disabled unbound (dnsmasq was already disabled), restarted OPNsense, and ```ctrld start```. Everything worked for a few hours.

I realized DNS addresses were not advertised by DHCP any more, which makes sense : OPNsense advertises his interface IP address if a DNS service is enabled or the configured global DNS servers. As I disabled unbound, it now uses global DNS server which is not configured.

I did enter the interface IP for each VLAN in the DHCP config. Is there a smarter way to make it work ?

This is something that might be useful to talk about in the pfSense/OPNsense wiki.

Also, the wiki clearly lists what ctrld does in "yolo" (```ctrld start --cd RESOLVER_ID_HERE```), but I find it hard to understand what happens in local config mode. I thought the only change was that user is responsible for listener conficts, but I also see, for example that ```/etc/resolv.conf```was reverted to previous version when stopping yolo mode, and is not changed with local config mode. I guess it make sense if we manually configurer the listeners.

**Comment by yegors** [comment]
Hi,

The only difference between "yolo mode" and custom config mode (ctrld start) is the fact that "yolo mode" will attempt to work around listener conflicts and kill processes. Except for that, they're identical. 

The further mentioned `ctrld service start` does a lot less, and only spawns the listener on a config defined port and makes it auto-start on reboot. You're then responsible for steering DNS traffic to your listener. 

If your listener is 0.0.0.0:53 (and there is no conflict) then ctrld listens on all interfaces and should be accessible to all vlans (unless there is an explicit firewall saying otherwise). DHCP should be unaffected, as it should keep doling out the RFC1918 address of the router (say 192.168.1.1), on which port 53 is used by ctrld. 

I know on pfsense you need to create an explicit firewall rule for this in order for LAN clients to be able to access 192.168.1.1:53.

**Comment by dav-fr** [comment]
Hi @yegors, thanks for the information.

Unfortunately I can confirm that disabling unbound/dnsmask (which needs to be done in order to ctrld start) makes OPNsense stop advertising DNS server.

There are also explicit rules to allow LAN clients to access port 53 for each VLAN interface, but this has not changed because it was already needed when using unbound.

**Comment by yegors** [comment]
Can you please provide some data related to "makes OPNsense stop advertising DNS server". How do you make this determination? 

See general troubleshooting guide: https://github.com/Control-D-Inc/ctrld/wiki/Troubleshooting-Guide

**Comment by dav-fr** [comment]
On the client side, I loose access to Internet, and the DNS servers are empty.
On OPNsense site, in the DHCP config page for each VLAN, the "DNS servers" fields have hint : " Leave blank to use the system default DNS servers: This interface IP address if a DNS service is enabled or the configured global DNS servers."

![dns_fields](https://github.com/Control-D-Inc/ctrld/assets/78509726/b5ed1dc5-10b9-4ff8-ac89-284cd5e305ec)

If I don't manually enter the interface address in the DHCP config for each VLAN as done in the screenshot, clients don't get any DNS.

If I'm not mistaken, the behaviour is similar with pfSense

**Comment by yegors** [comment]
None of this should matter. Please provide data from the above linked troubleshooting guide. Without exact data it asks to collect, there is nothing we can do to suggest a solution.

**Comment by dav-fr** [comment]
Sorry I didn't understand the question
```
# ps aux | grep ctrld
root  62019   0.0  0.0   12724    2276  -  Is   16Jan24     0:00.00 daemon: ctrld: daemon[62096] (daemon)
root  62096   0.0  0.2 1240992   26952  -  I    16Jan24    20:21.22 /usr/local/bin/ctrld run --iface=auto --homedir=/etc/controld --config=/etc/controld/ctrld.toml
root  35518   0.0  0.0   12720    2396  0  S+   20:53       0:00.00 grep ctrld


# sockstat | grep ctrld
root     ctrld      62096 3  udp4   *:5353                *:*
root     ctrld      62096 14 tcp4   xxx.xxx.xxx.xxx:12797    xxx.xxx.xxx.xxx:443
root     ctrld      62096 15 udp4   *:5353                *:*
root     ctrld      62096 16 udp4   *:5353                *:*
root     ctrld      62096 18 tcp46  *:53                  *:*
root     ctrld      62096 19 udp46  *:53                  *:*
root     ctrld      62096 20 udp4   *:5353                *:*
root     ctrld      62096 21 udp4   *:5353                *:*
root     ctrld      62096 22 udp4   *:5353                *:*
root     ctrld      62096 23 udp4   *:5353                *:*
root     ctrld      62096 24 udp4   *:5353                *:*
root     ctrld      62096 25 udp4   *:5353                *:*
root     ctrld      62096 26 udp4   *:5353                *:*
root     ctrld      62096 27 udp4   *:5353                *:*
root     ctrld      62096 28 udp4   *:5353                *:*
root     ctrld      62096 29 udp4   *:5353                *:*
root     ctrld      62096 30 udp4   *:5353                *:*
root     ctrld      62096 31 udp4   *:5353                *:*
root     ctrld      62096 32 udp4   *:5353                *:*
root     ctrld      62096 33 udp4   *:5353                *:*
root     ctrld      62096 34 udp4   *:5353                *:*
root     ctrld      62096 35 udp4   *:5353                *:*
root     ctrld      62096 36 stream /var/run/ctrld_control.sock


# host verify.controld.com 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#53
Aliases:

verify.controld.com is an alias for api.controld.com.
api.controld.com has address 147.185.34.1
api.controld.com has IPv6 address 2606:1a40:3::1


# cat /etc/resolv.conf
domain localdomain
search localdomain
```

**Comment by yegors** [comment]
ctrld is running, receiving queries and handling them correctly. 

Is that the entire contents of resolv.conf? As that's incorrect and suggests some other process modified it as there is no nameserver there.

It's supposed to look like:

```
root@OPNsense:~ # cat /etc/resolv.conf
domain localdomain
nameserver 127.0.0.1
```

The above would affect router's own DNS connectivity, but should have no impact on LAN clients as long as router's RFC1918 address is distributed via DHCP as a DNS server.

**Comment by dav-fr** [comment]
That's odd indeed. Yes that was the entire content, but I'm pretty sure I set it as your example in the past. Maybe it was modified when I updated OPNsense?

So I modified the file again, adding the nameserver. Then rebooted, and it was modified, by ctrld this time. Now it is 
```
# cat /etc/resolv.conf
# resolv.conf(5) file generated by ctrld
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 127.0.0.1
```

**Comment by yegors** [comment]
That looks accurate. Any issues with this?

**Comment by dav-fr** [comment]
I just checked, the file is back to 
```
# cat /etc/resolv.conf
domain localdomain
search localdomain
```
I have no idea what changes it. But DNS still works fine.

The original problem was having to manually enter the DNS server in the DHCP configuration for each VLAN.

**Comment by dav-fr** [comment]
I found that /etc/resolv.conf is modified when I save the System/Settings/Administration page in the GUI, even if nothing was modified on the page.

**Comment by yegors** [comment]
Sounds like another piece of software is modifying it. I recommend factory settings reset and starting fresh.

**Comment by dav-fr** [comment]
Ok, thanks. I will try that

**Comment by yegors** [comment]
@dav-fr Any updates?

**Comment by dav-fr** [comment]
Just got done with a clean reinstall of OPNsense 24.1
No plugin installed.

I can see the same behaviour as before: /etc/resolv.conf is modified when saving the System/Settings/Administration page in the GUI

**Comment by yegors** [comment]
@dav-fr Can you re-run the installer and replace `api.controld.com` with `api.controld.dev`. 

This version should address the above issue.

**Comment by yegors** [comment]
Closing due to lack of response. Let us know if there is still a problem.
