### ISSUE TITLE
QUIC protocol unsuccessful in CLI

### ISSUE THREAD

**Issue by viniribeirossa** [Control-D-Inc/ctrld#136]
Hello friends, I apologize for opening multiple tickets, but I can't find help for this.

I tried using DNS over QUIC; however, when I use this protocol, my phones don't work.

I have 5 phones at home, 4 Android 14, 1 Android 13, all Android.

Do I need to change the port? What do I need to do?

**Comment by yegors** [comment]
What country are you located in, and who is your ISP?

**Comment by viniribeirossa** [comment]
Brazil 

Ipglobe Internet Ltda

**Comment by yegors** [comment]
That suggests TCP/UDP 853 is blocked on the network. If you install the GUI app, it uses DOH which is on port 443 and cannot be blocked.

**Comment by viniribeirossa** [comment]
Thank you friend for all your patience in answering me.
