### ISSUE TITLE
Running ctrld service on port 53 and 853

### ISSUE THREAD

**Issue by gniting** [Control-D-Inc/ctrld#139]
I am using CD on pfSense (and also experimenting on opnsense). Everything is working good on pfSense and I also have a NAT rule to redirect all "rogue" DNS queries to be forwarded to CD on port 53.

I realized that unbound is still listening on port 853 and so I wanted to redirect that also to the CD service. However, CD is not running on port 853, cause it's not configured to.

How do I do that? Have CD run on both ports 53 and 853?

**Comment by yegors** [comment]
You can have as many listeners as you want: https://github.com/Control-D-Inc/ctrld/wiki/Example-Configurations#multiple-listeners

However port 853 is usually used for DNS-over-TLS, not legacy (UDP) DNS.

**Comment by gniting** [comment]
Thanks @yegors, looks simple enough to configure. I will give it a go.

**Comment by gniting** [comment]
@yegors another related question, I've configured CD to run on port 53, why does it also show as running on port 5353? More of an educational question for me, this is not causing any issues (that I know of).

Here's the output of the `sockstat -l | grep 53` command:
```
[2.7.2-RELEASE][root@router]/root: sockstat -l | grep ctrld
root     ctrld      62844 11  udp4   *:5353                *:*
root     ctrld      62844 22  tcp46  *:53                  *:*
root     ctrld      62844 23  udp46  *:53                  *:*
root     ctrld      62844 25  udp4   *:5353                *:*
```

**Comment by yegors** [comment]
This is an mDNS listener: https://www.speedguide.net/port.php?port=5353

If mdns client discovery is disabled via config flag, this listener will go away.

**Comment by gniting** [comment]
Got it, thanks again!
