### ISSUE TITLE
Include domain automatically when creating wildcard redirect rules

### ISSUE THREAD

**Issue by gniting** [Control-D-Inc/ctrld#140]
**Feature request:** 
If I make a redirect rule as follows: `*.domain.com` and route it through a specific location, then the rule works well for `anything(*).domain.com` but not for `domain.com`. A separate rule is needed to achieve that.

Can the domain also be part of such a redirect rule?

**Comment by lsthompson** [comment]
Technically, I would say that the current behaviour is correct. 

You stipulate the need for something ahead of the domain.
(anything . domain . com) != (domain . com) whatsoever.

If it takes regex/etc then you might be able to achieve it.

**Comment by gniting** [comment]
I see your point, and agree with the proposed altered line of thinking on the implementation. 

Regex support would also be welcomed.

**Comment by yegors** [comment]
This issue tracker is for the ctrld utility only, this discussion appears to be related to the Control D service and redirect rules you create there. Such discussion should be moved here: https://docs.controld.com/discuss

**Comment by gniting** [comment]
You are right, closing.
