### ISSUE TITLE
Local network hostnames not being resolved

### ISSUE THREAD

**Issue by gniting** [Control-D-Inc/ctrld#141]
As the title says, I noticed that the hostnames of local network hosts are not being resolved despite my CD config having a rule for the local network name resolution. CD is running on pfSense and all other CD functions are working properly.

My expectation is that if I ping `hostname.localnet.lan`, CD should send that query to the local unbound server running on port 5555 on pfSense and get the IP.

Any ideas?

`/etc/controld/ctrld.toml` file contents:
```
[service]
  log_level = 'info'
  log_path = '/root/logs/ctrld.log'
  cache_enable = 'true'
  cache_size = 6144
  cache_serve_stale = 'false'
  dhcp_lease_file_path = '/var/dhcpd/var/db/dhcpd.leases'
  dhcp_lease_file_format = 'isc-dhcp'
  discover_mdns = 'true'
  discover_dhcp = 'true'
  discover_ptr = 'true'
  discover_arp = 'true'
  client_id_preference = 'mac'

[listener]
  [listener.0]
    ip = '0.0.0.0'
    port = 53
    [listener.0.policy]
      name = 'MyNetwork'
      networks = [
            {'network.0' = ['upstream.0']},
      ]
      rules = [
            {'*.localnet.lan' = ['upstream.1']},
      ]
      macs =  [
            {'xx:xx:xx:xx:xx:xx' = ['upstream.2']},
            {'xx:xx:xx:xx:xx:xx' = ['upstream.2']},
      ]

[network]
  [network.0]
    name = 'Any Network'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    type = 'doh'
    endpoint = 'https://dns.controld.com/xxxxxxxxxx'
    bootstrap_ip = ''
    ip_stack = 'v4'
    send_client_info = 'true'

  [upstream.1]
    type = 'legacy'
    endpoint = '192.168.7.1:5555'
    ip_stack = 'v4'
    send_client_info = 'true'
    discoverable = 'true'

  [upstream.2]
    type = 'doh'
    endpoint = 'https://dns.controld.com/xxxxxxxxxx'
    bootstrap_ip = ''
    ip_stack = 'v4'
    send_client_info = 'true'
```

**Comment by yegors** [comment]
According to this config, it should indeed do that as hostname rules would match first. I recommend enabling debug level logging, which will print all the policy decisions into the log, so you can see what's wrong. 

Also, you can simplify your config by getting rid of `network.0` and the associated network policy, as this is already default behavior.

**Comment by gniting** [comment]
Here's what debug log shows when I `ping unifi.localnet.lan` from the machine `mb-air-nitin-wifi`
The query is being sent to the right upstream server, but not getting a reply back. The IP for `unifi` should be `192.168.7.7`
```
{"level":"info","time":"2024-02-23T21:33:45+01:00.481","message":"[3ee2f5] QUERY: 192.168.7.24:63304 (mb-air-nitin-wifi) -> listener.0: A unifi.localnet.lan"}
{"level":"debug","time":"2024-02-23T21:33:45+01:00.481","message":"[3ee2f5] Synapse, network.0 (unenforced), *.localnet.lan -> [upstream.1]"}
{"level":"debug","time":"2024-02-23T21:33:45+01:00.481","message":"[3ee2f5] including client info with the request"}
{"level":"debug","time":"2024-02-23T21:33:45+01:00.481","message":"[3ee2f5] sending query to upstream.1: "}
{"level":"debug","time":"2024-02-23T21:33:45+01:00.481","message":"[3ee2f5] add cached response"}
{"level":"info","time":"2024-02-23T21:33:45+01:00.481","message":"[3ee2f5] REPLY: upstream.1 -> 192.168.7.24:63304 (mb-air-nitin-wifi): NXDOMAIN"}
```

Regarding the simplification recommendation, could I bug you to show me the modified version? I am unable to grok how to remove `upstream.0` and `network.0` without breaking things.

**Comment by gniting** [comment]
Found the issue. I was using the "new" Kea DHCP server on pfSense and their implementation does not support the option to "Register DHCP static mappings in the DNS Resolver" 🙄

Moved back to ISC DHCP (for the time being) and local hostnames resolve nicely again.

**Comment by yegors** [comment]
Okay, thx for the feedback. `ctrld` policy wise, it's doing what's expected according to the debug log.

**Comment by cuonglm** [comment]
@gniting So should we close this issue, since it's not ctrld problem?
