### ISSUE TITLE
ControlD mode on OPNSense - Unbound and DNSMasq should not always start when shutting down/restarting ctrld

### ISSUE THREAD

**Issue by jaydeethree** [Control-D-Inc/ctrld#143]
I'm using ControlD on OPNSense and have been really happy with it - thanks for making such an awesome DNS daemon!

One thing I noticed is that when you restart or stop the ctrld service while using ControlD mode (flag `--cd=resolver_id`), Unbound and DNSMasq will be started:

https://github.com/Control-D-Inc/ctrld/blob/main/internal/router/os_freebsd.go#L113-L116

Always starting these services feels like a bug to me - it would be better to check if they're running when ctrld starts, set a boolean for each of them, and then only restart them if they were already running when ctrld was started. Alternatively you could check the OPNSense/PFSense config files to see if the services are enabled or disabled, and then only start them if they are enabled. Personally I **never** want Unbound or DNSMasq to be running and I have them disabled in OPNSense, but when I restart the ctrld daemon (e.g. to pull down a new config version), ctrld starts them anyway.

**Comment by yegors** [comment]
Fair point. @cuonglm ^

**Comment by cuonglm** [comment]
> Alternatively you could check the OPNSense/PFSense config files to see if the services are enabled or disabled, and then only start them if they are enabled.

@jaydeethree Are you refering to `/etc/rc.conf` file, for checking unbound/dnsmasq enabled/disabled?

**Comment by cuonglm** [comment]
> > Alternatively you could check the OPNSense/PFSense config files to see if the services are enabled or disabled, and then only start them if they are enabled.
> 
> @jaydeethree Are you refering to `/etc/rc.conf` file, for checking unbound/dnsmasq enabled/disabled?

Nevermind, I think it should be `/conf/config.xml`.

**Comment by jaydeethree** [comment]
>Nevermind, I think it should be /conf/config.xml.

Yes, that's what I meant - sorry for not being more clear! For example, this is the relevant part of my Unbound config in that file:

```
    <unboundplus version="1.0.9">
      <general>
        <enabled>0</enabled>
```

**Comment by jsimcina** [comment]
I didn't realize this was happening, but now things are making so much sense.  Seconded on changing this functionality!

**Comment by cuonglm** [comment]
This is fixed after https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.6
