### ISSUE TITLE
IPv6 listeners

### ISSUE THREAD

**Issue by DanielSpindler83** [Control-D-Inc/ctrld#146]
Further to https://github.com/Control-D-Inc/ctrld/issues/131

:: or ::0 as the listener IP appears to work for link local IPv6 addresses.
Should we be able to specify a full public ipv6 address directly in a listener?
Should we be able to use ipv6 subnets in the CIDR range for networks?

I would like LAN clients to run fully ipv6, making DNS calls to ctrld using ipv6 and the upstream as ipv6(upstream works as ipv6). 
I can use link local addresses as a listener by using :: or ::0 but this is per subnet.
What I was trying to achieve is a public static ipv6 on an interface that can then be used for ctrld dns across multiple subnets.

Thanks for an awesome project.

**Comment by DanielSpindler83** [comment]
Sorry, I just found the listener option = allow_wan_clients [https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#allow_wan_clients](https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#allow_wan_clients)
If a call is made to a global ipv6 then the client source is a global ipv6 address.
Understand this needs caution - block all from WAN side.
ipv6 needs to use full address (no shortened syntax) - would assume this is an OS requirement.

**Comment by yegors** [comment]
Yes, the address has to be fully formed (/128), and if you use a WAN IP range you need to enable that option, which is disabled for safety to avoid people putting their DNS resolver on the open Internet. 

Feel free to close this issue if there are no other concerns.
