### ISSUE TITLE
ctrld errors on opnsense (freebsd) with mdns

### ISSUE THREAD

**Issue by planetf1** [Control-D-Inc/ctrld#148]
Running opnsense 24.1.6 / FreeBSD 13.2-RELEASE-p11, when ctrld 1.3.6 is started  (log level=warn)
a series of errors are logged:
```
{"level":"warn","error":"write udp6 [::]:5353->[ff02::fb]:5353: sendto: can't assign requested address","time":"2024-04-21T10:42:09Z.317","message":"error while probing mdns"}
{"level":"warn","error":"write udp4 0.0.0.0:5353->224.0.0.251:5353: sendto: capabilities insufficient","time":"2024-04-21T10:42:09Z.318","message":"error while probing mdns"}
```

ctrld does work correctly on linux (running a debian LXC)

**Comment by cuonglm** [comment]
Did you run ctrld with root privilege?

These does not mean ctrld was running correctly or not, it just means mdns discovery failed to run, and the reason is explained and warned to users.

**Comment by planetf1** [comment]
This is a standard opnsense install (as root).
```
root    42291   0.0  0.7 1243480  29124  -  S    16:19       0:02.32 /usr/local/bin/ctrld run --iface=auto --homedir=/etc/controld --config=/etc/controld/ctrld.toml
```

ctrld does seem to be found to 5353 ie
```
root     ctrld      42291 8  udp4   1.2.3.4:43383   76.76.2.22:53
root     ctrld      42291 14 udp46  *:60600               *:*
root     ctrld      42291 16 udp46  *:55046               *:*
root     ctrld      42291 120 tcp46 *:42069               *:*
root     ctrld      42291 131 udp46 *:53                  *:*
root     ctrld      42291 132 tcp46 *:53                  *:*
root     ctrld      42291 142 udp4  *:5353                *:*
root     ctrld      42291 145 udp4  *:5353                *:*
root     ctrld      42291 149 udp4  *:5353                *:*
```
Is this an issue with the current implementation for opnsense for freebsd specifically?

**Comment by planetf1** [comment]
Yes, this was running as root in a standard opnsense install.
Is it expected that mdns probes work on opnsense?

Repeating the same test on a default FreeBSD 14 install, and this worked fine.

**Comment by cuonglm** [comment]
Sorry to not be clear, it does not mean mdns discovery failed, just the probing part, where ctrld actively ask for known services.

The listening port 5353 of ctrld is the reading part, where ctrld will read advertising from services in local network then adding the service to its mdns table.

There is no difference between platforms in term of mdns implementation. The probing just send query to v4 and v6 multicast address if possible. Whether the probing failed or not, it does not affect the reading part.

**Comment by planetf1** [comment]
@cuonglm thanks for the explanation
