### ISSUE TITLE
Cannot do custom resolver string on macOS GUI

### ISSUE THREAD

**Issue by cixastra** [Control-D-Inc/ctrld#149]
Hello all! 

I have an apple M1 2020 macbook air. I have used Warp, and I have other VPNs installed but they were all disabled and completely shut down as I was installing controld. For some reason, when I use the custom resolver string no-ads-drugs-gambling-typo-malware-dating in the GUI mac installer, it does not allow me to submit this. I discovered that the reason it was erroring "Invalid Resolver ID" is that there was a character limit in the resolver ID field. I think that this isn't supposed to happen? PFA a video: 

https://github.com/Control-D-Inc/ctrld/assets/68437385/e7fd98a5-d749-416a-bafe-90839a054544

The resolver id p3 works so I think it is just custom ones over a certain length. I tried using the terminal and I actually got it to work. Just a GUI fix :)

**Comment by yegors** [comment]
This is not a ctrld issue, as there is no problem if you do this in ctrld itself. 

The GUI wrapper is at fault here, which is outside the scope of this issue tracker. This will be fixed.
