### ISSUE TITLE
Asus Merlin support 

### ISSUE THREAD

**Issue by RouterCFW** [Control-D-Inc/ctrld#15]
Hello just wanted to double check that asus Merlin support is planned for the future a response would be appreciated thanks :)

**Comment by yegors** [comment]
Yes, it's planned for v1.2.

**Comment by RouterCFW** [comment]
❤️ does that mean local IPs and client names from the router will be showed in the controld logs 🤔

**Comment by yegors** [comment]
Indeed, this is all part of v1.2
