### ISSUE TITLE
HTTP X headers

### ISSUE THREAD

**Issue by mschirrmeister** [Control-D-Inc/ctrld#151]
Is there a way to disable sending the `X-` headers to **ControlD** and **NextDNS**?
At least for the _upstream_ servers where the **free** version is used. Sending these has no benefit for the users, since he cannot do any analytics on it and it would reduce the overhead.

**Comment by yegors** [comment]
Those headers are only sent to premium Control D and/or NextDNS upstreams, not all DNS endpoints. You don't need to do anything.
