### ISSUE TITLE
Ctrld error in Mikrotik Log

### ISSUE THREAD

**Issue by fhirrepo** [Control-D-Inc/ctrld#159]
attached is the controld config and also errors in the mikrotik container log.

![image](https://github.com/Control-D-Inc/ctrld/assets/84551091/0f312401-6e94-4d35-ae6d-23887652fd48)
[ctrldconfig_debug.txt](https://github.com/user-attachments/files/15995812/ctrldconfig_debug.txt)

**Comment by fhirrepo** [comment]
please let me know if additional info is needed

**Comment by cuonglm** [comment]
Hi @fhirrepo, thanks for your report.

What's the DNS server run at your upstream.2, aka "ProtonVPN DNS Secure LAN main"?

Could you please also enable debug log and sent it to cuong [at] controld.com?

Thank you.

**Comment by fhirrepo** [comment]
> Hi @fhirrepo, thanks for your report.
> 
> What's the DNS server run at your upstream.2, aka "ProtonVPN DNS Secure LAN main"? If you replaced upstream.2 and upstream.7 with non-ProtonVPN DNS, does the error still occur?
>
what do you mean by DNS server run? its wireguard configured on a router. 

> Could you please also enable debug log and sent it to cuong [at] controld.com?
> 
> Thank you.
have container logging turned on for this container. let me know how to turn on any other logging. also, did not see the issue recur.

**Comment by cuonglm** [comment]
> what do you mean by DNS server run? its wireguard configured on a router.

I mean what DNS server software you are running on your upstream.2?

> have container logging turned on for this container. let me know how to turn on any other logging. also, did not see the issue recur.

You could set `log_level = 'debug'` in configuration file or passing `-vv` flag to ctrld command to enable debug log.

**Comment by fhirrepo** [comment]
> > what do you mean by DNS server run? its wireguard configured on a router.
> 
> I mean what DNS server software you are running on your upstream.2?
>
as mentioned, its a wireguard protonvpn gateway (which also serves DNS requests).

> > have container logging turned on for this container. let me know how to turn on any other logging. also, did not see the issue recur.
> 
> You could set `log_level = 'debug'` in configuration file or passing `-vv` flag to ctrld command to enable debug log.
i cannot reproduce this issue anymore. so not sure if providing additional logs would help. let me know. 
in the meantime, please check if possible what could cause this from code standpoint
