### ISSUE TITLE
problem installing ctrld on OpenWRT on r8000

### ISSUE THREAD

**Issue by Mile-Lile** [Control-D-Inc/ctrld#160]
Hi there, I need some help with installing ctrld on r8000. Upon launching ctrld I get message `illegal instruction`

![Screenshot 2024-07-03 221416](https://github.com/Control-D-Inc/ctrld/assets/12752816/f6f5d831-9c47-458c-b61d-6e631e7cdcd5)

**Comment by yegors** [comment]
It appears the CPU despite being armv7 is unable to run armv7 binaries. Manually download https://dl.controld.com/linux-armv5/ctrld and overwrite the file in the install path.

**Comment by Mile-Lile** [comment]
@yegors 
OK. Thank you... seems CPU does not provide VFP support on [r8000](https://openwrt.org/toh/netgear/r8000) on OpenWRT
![Screenshot 2024-07-04 204748](https://github.com/Control-D-Inc/ctrld/assets/12752816/49e766c9-64e5-45e4-b8b7-e24944f0e8e9)

after downloading binaries you provided with curl everythink worked so THAK YOU!

**Comment by Mile-Lile** [comment]
@yegors can you make it to fallback to armv5 if it fails with armv7
