### ISSUE TITLE
ctrld on OpnSense during internet outage

### ISSUE THREAD

**Issue by spry-salt** [Control-D-Inc/ctrld#161]
Recently I had an internet outage. As part of trying to resolve that, I rebooted the OpnSense router where ctrld is running. ctrld failed to start up, probably because of the outage.

As a side effect, ctrld stopped referring internal dns queries to another dns server running on a different port on the same router.

Have I misconfigured something, or is it possible to make ctrld continue to do internal dns referrals even when it fails to start because of an internet outage please?

Thanks for your consideration.

**Comment by yegors** [comment]
We would need to see a log + debug data at the time of the issue. https://github.com/Control-D-Inc/ctrld/wiki/Troubleshooting-Guide
