### ISSUE TITLE
cannot upgrade on ddwrt - x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by Mile-Lile** [Control-D-Inc/ctrld#162]
after trying to upgrade I get error :  FTL failed to download binary error="Get \"https://dl.controld.com/linux-armv5/ctrld\": tls: failedto verify certificate: x509: certificate signed by unknown authority". DD-WRT has self-signed certs... is there workaround?
![Screenshot 2024-07-13 134321](https://github.com/user-attachments/assets/27e4e5d1-2c48-4c5b-b49b-4744d04a0600)

**Comment by cuonglm** [comment]
Hello, is your system date/time set correctly?

**Comment by Mile-Lile** [comment]
yes... I see delta is 0
![image](https://github.com/user-attachments/assets/b801e93b-9c98-4d4a-a9d0-c6152393ea2b)

but I time is different

![image](https://github.com/user-attachments/assets/9daea793-59ef-4395-ae67-92fdd99206e8)


at the moment here is 16:35 but seems cert is 14:35... are these different timezone problem or similar? I am at gmt+1 Belgrade/EU

**Comment by Mile-Lile** [comment]
ctrld time is somehow different
![image](https://github.com/user-attachments/assets/391da075-16f5-4307-83a7-0e75a207d8b0)

**Comment by cuonglm** [comment]
Hi @Mile-Lile, What's the output of `date` command?

**Comment by Mile-Lile** [comment]
here it is

![image](https://github.com/user-attachments/assets/d9d3d995-05d9-4124-8ae0-666d0a670f10)

**Comment by Mile-Lile** [comment]
@cuonglm 
I have these in my controld logs too:

`{"level":"error","error":"read udp 192.168.0.13:36005->192.168.0.1:53: i/o timeout","time":"2024-07-25T12:51:08Z.309","message":"[2a0a5f] failed to resolve query"}`

`{"level":"error","error":"read udp 192.168.0.13:55263->192.168.0.1:53: i/o timeout","time":"2024-07-25T12:51:08Z.312","message":"[f1a40b] failed to resolve query"}`

192.168.0.13 is wan ip of my controld router and 192.168.0.1 is my ISP router. dns and ntp are disabled on my ISP router... why controld d doesn't get time on public ntp servers?

**Comment by cuonglm** [comment]
> why controld d doesn't get time on public ntp servers?

ctrld does not do anything with your system date time, it's a DNS software, not NTP.

You should enable ntp on your router to get the correct date/time.

**Comment by Mile-Lile** [comment]
@cuonglm 
I have the same situation on different OS (OpenWRT) and target (mediatek). Could it be something wrong with ctrld? I have enabled ntpd on Openwrt but clocks are not in sync:

Oct 09 **12:07:57** AX3000T ctrld Oct  9 **10:07:57**.742 ERR [516676] failed to resolve query error="could not perform request: Get \"https://dns.nextdns.io/gc6122?dns=5TIBAAABAAAAAAABBHRpY2sEdWNsYQNlZHUAAAEAAQAAKQIAAAACADEF\": Application error 0x100 (remote): idle timeout"

and what does this 0x100 error tells me... my log is full of these spam from ctrld....

`You should enable ntp on your router to get the correct date/time.`
I have it enabled and my router has correct time... but ctrld displays gmt-1 and I am gmt+1 time zone...

**Comment by Mile-Lile** [comment]
and just to add I noticed that this errors occures when router tries to resolve domains such as ntp.nasa.gov, tick.ucla.edu etc. from itself...

**Comment by cuonglm** [comment]
> I have it enabled and my router has correct time... but ctrld displays gmt-1 and I am gmt+1 time zone...

Did you restart ctrld after fixing the date time? If not, you probably have to do that.

**Comment by Mile-Lile** [comment]
I did now but there is still 2 hours gap:

![image](https://github.com/user-attachments/assets/e5f40d37-1fef-4642-ba65-57bf31ceffbc)

I get some new errors:

![image](https://github.com/user-attachments/assets/18a3aa06-fdaf-4ab4-a15a-73230393c760)
 and have to wait to see if error `Application error 0x100 (remote): idle timeout"` will occur

**Comment by cuonglm** [comment]
@Mile-Lile Could you please show me your upstream config?

**Comment by Mile-Lile** [comment]
@cuonglm  Here it is, I didn't changed anything, toml is generated during first install...

![image](https://github.com/user-attachments/assets/0ca1bdb7-dfb8-4857-b83b-4f34e63e9078)

**Comment by Mile-Lile** [comment]
but I don't see any errors for now

![image](https://github.com/user-attachments/assets/bb66b865-dd27-4e4a-8c9e-ad96ecfd7639)
