### ISSUE TITLE
IPv6/IPv4 fallback

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#163]
My ISP often has IPv4 issues and IPv6 must be used, but ctrld always uses IPv4 by default.

If IPv4 is unavailable, ctrld should fall back to IPv6.

The opposite is also true: If IPv6 is unavailable, ctrld should fall back to IPv4.

Moreover, please enable 6to4 (DNS64)and 4to6 (DNS46) connections in these cases.

Please add support for IPv6/IPv4 fallback and 6to4/4to6 tunnels.

**Comment by yegors** [comment]
It should already do that, can you provide a log that shows otherwise?

DNS64 is a Profile Option which you can enabled. It doesn't have anything to do with `ctrld`.
