### ISSUE TITLE
UDM Pro Max Install Issue - Error Test Query

### ISSUE THREAD

**Issue by CautionSentry** [Control-D-Inc/ctrld#165]
Hi all,
I am trying to install ControlD via Automatic installer and when I run the cli command while SSH'd into my Unifi Dream Machine Pro Max I am getting an error. 

Command I ran
`sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s ******* forced'`

Output:

`        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : ubios
OS Version   : 4.0.6.16512
Router Model : UniFi Dream Machine Pro Max
Arch         : aarch64
CPU          : Cortex-A57
Free RAM     : 3478 MB / 7972 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : ********
Binary URL   : https://dl.controld.com/linux-arm64/ctrld
Install Path : /data/controld
---------------------
 - Starting download
 - PATH updated - please run 'source /root/.bashrc' to update your current shell
 - Making binary executable
 - Launching /data/controld/ctrld
---------------------
Jul 26 23:10:57.000 NTC Reading config: /etc/controld/ctrld.toml
Jul 26 23:10:57.611 NTC Starting service
Jul 26 23:10:59.632 NTC Generating controld config: /etc/controld/ctrld.toml
Jul 26 23:11:49.263 ??? ================================
Jul 26 23:11:49.263 ??? An error occurred while performing test query: no answer from ctrld listener
Jul 26 23:11:49.264 ??? ================================
Jul 26 23:12:00.562 NTC Service uninstalled`

**Comment by photomme** [comment]
Hey There.

Reboot UDM PRO and then rerun the installer.  
It will work.

**Comment by CautionSentry** [comment]
Hey! Thanks for your quick reply, I reboot the UDM Pro Max and ran the command and the same error occured.

> Hey There.
> 
> Reboot UDM PRO and then rerun the installer. It will work. Just make sure you rerun the script right after the reboot.

**Comment by yegors** [comment]
This error suggests the DNS listener that ctrld spawns is not reachable for some reason, which is quite unusual, but can be caused by conflicting software or firewall rules.

Try starting ctrld manually with: `/data/controld/ctrld start --cd RESOLVER_ID_HERE --skip-self-checks`

The service will not exit, but you will likely have broken DNS. Perform the troubleshooting guide in this state, as per https://github.com/Control-D-Inc/ctrld/wiki/Troubleshooting-Guide

**Comment by CautionSentry** [comment]
I went through the troubleshooting steps and even though the last command failed, I noticed I that Endpoint is now reflecting as online, odd but if it works I guess that's good. Eitherway, here are the screenshots of the troubleshooting steps.



`netstat -tupln | grep ctrld`

![CleanShot 2024-07-27 at 13 16 31@2x](https://github.com/user-attachments/assets/721676db-83a5-41f5-adfb-6042101d2c37)


`dig verify.controld.com @127.0.0.1 -p5354`

![CleanShot 2024-07-27 at 13 15 35@2x](https://github.com/user-attachments/assets/8c5f9d03-cb48-47a0-a70a-226a7d29aa97)


`netstat -tupln | grep ":53\b"`

![CleanShot 2024-07-27 at 13 15 21@2x](https://github.com/user-attachments/assets/81d9b80d-d597-4d8f-b5cf-e698f2a16d78)


`ctrld start --log /tmp/ctrld.log -vv`
![CleanShot 2024-07-27 at 02 14 33@2x](https://github.com/user-attachments/assets/197133fe-1646-472f-be88-9dc756b792bd)

'/data/controld/ctrld start --cd **** --skip_self_checks'
![CleanShot 2024-07-27 at 13 17 15@2x](https://github.com/user-attachments/assets/9a3ad463-6134-4188-8975-867ce77c7132)


Few Questions since I moved from AdGuard and NextDNS,
Is it possible to forward the Device IDs from Unifi ? 
Do I have to re-install after every Unifi update ?

**Comment by cuonglm** [comment]
> Do I have to re-install after every Unifi update ?

No.

After starting ctrld with --skip_self_check, do `dig verify.controld.com` run ok?

The i/o timeout means something went wrong and block test query from reaching ctrld listener. But the dig command still run ok, which is weird.

**Comment by cuonglm** [comment]
Oh wait, your netstat command shows that there's no listener on port 5354 for ipv4 ...

**Comment by CautionSentry** [comment]
I reboot'd the UDM and it still functioning well, but I'm not sure what did it? I see the analytics flow but if run the command it'd still fail?
