### ISSUE TITLE
Ctrld keenetic

### ISSUE THREAD

**Issue by getelman** [Control-D-Inc/ctrld#172]
Hello, does it seem to get up in Keenetik? But you need an accurate manual) Has anyone had any experience?

**Comment by yegors** [comment]
This doesn't appear to be a standard Linux based router and runs some proprietary OS, so I don't think this is possible. 

You can however configure DOH natively: https://help.keenetic.com/hc/en-us/articles/360007687159-DNS-over-TLS-and-DNS-over-HTTPS-proxy-servers-for-DNS-requests-encryption
