### ISSUE TITLE
OPNSense resolv.conf gets whacked

### ISSUE THREAD

**Issue by hazarjast** [Control-D-Inc/ctrld#174]
Several times now I've logged into OPNSense and am greeting with an error on the dashboard asking me to submit an error report to the OPNSense devs. Here is the error:

`PHP Warning:  rename(/tmp/resolv.confKTNYWl,/etc/resolv.conf): No such file or directory in /usr/local/etc/inc/system.inc on line 200`

When this happens my clients stop being able to resolve anything through DNS and I have to reboot OPNSense as '/etc/resolv.conf' is missing entirely and restarting ctrld does not help. This only occurs a few times a month but it is problematic as you can imagine. I have no other DNS services running besides ctrld on the box so unclear why they appear to be 'fighting' in some way.

**Comment by cuonglm** [comment]
Thanks for reporting.

- What ctrld version are you using?
- When problem happens, are you able to create /etc/resolv.conf yourself?
- After rebooting OPNSense, is it working normally?

**Comment by hazarjast** [comment]
Apologies, I totally forgot to include this important info.

Originally happening on ctrld version 1.3.5. Yesterday I upgraded to the latest 1.3.7 but have not yet seen it happen again yet to say if there was something in the new version that may have fixed it. I did check closed OPNSense issues here and did not see any reports of this yet though.

When OPNSense is rebooted it will create the '/etc/resolv.conf' file again but ctrld would not make updates to it until I setup ctrld fresh again. Once I rebooted to have OPNSense recreate the file and reconfigured ctrld it, it now works properly again.

**Comment by hazarjast** [comment]
I've swapped out my OPNSense build for an upgraded pfSense build as I believe there may have been some sort of SSD issue with the OPNSense build. Closing this out but will report back if I see it crop up again in any future *BSD based builds. Thank you.
