### ISSUE TITLE
ctrld still returns upstream data for overrides in some cases

### ISSUE THREAD

**Issue by Kreeblah** [Control-D-Inc/ctrld#176]
I'm installing lancache, and I tried setting up `ctrld` to resolve the IP address of `lancache.steamcontent.com` to my lancache host.  However, it's both returning that as well as the upstream data (which appears to be a CNAME).  So, my OS is using the CNAME data instead of the A record I want it to use.

Here's the output of `nslookup`:

```
$ nslookup lancache.steamcontent.com
Server:		192.168.53.1
Address:	192.168.53.1#53

Non-authoritative answer:
Name:	lancache.steamcontent.com
Address: 192.168.2.1
lancache.steamcontent.com	canonical name = origin-tier2.steampipe.steamcontent.com.
origin-tier2.steampipe.steamcontent.com	canonical name = steampipe-origin-tier2.steamcontent.com.
steampipe-origin-tier2.steamcontent.com	canonical name = cache-origin.steampipe.steamcontent.akadns.net.
cache-origin.steampipe.steamcontent.akadns.net	canonical name = dist-sea1.discovery.steamserver.net.
Name:	dist-sea1.discovery.steamserver.net
Address: 2602:801:f00b:100::cdc4:6ae
Name:	dist-sea1.discovery.steamserver.net
Address: 2602:801:f00b:101::cdc4:690
```

As you can see, it's returning an A record of `192.168.2.1`, which is correct, but it's _also_ returning all the data from the upstream CNAME, which is what my OS is ending up using, and resolving requests to that FQDN to the public IP address.

Is it possible to have `ctrld` drop the CNAME info entirely from the response and only return the A record I have configured?

**Comment by cuonglm** [comment]
Thanks for your reporting.

It seems to me you don't set the overriding option for IPv6 for that domain. If you do:

```
$ nslookup -type=a lancache.steamcontent.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	lancache.steamcontent.com
Address: 1.1.1.1
```

you will get the correct answer.

After setting overriding rule for IPv6, you will be good to go:

```
$ nslookup lancache.steamcontent.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	lancache.steamcontent.com
Address: 1.1.1.1
Name:	lancache.steamcontent.com
Address: ::1
```

**Comment by Kreeblah** [comment]
So, you're right that I don't have IPv6 set up.  But, my ISP is unfortunately a bit behind the times and doesn't offer IPv6 connectivity just yet (they're aiming for some time in the next few months).  So, even if something resolves a AAAA record, it wouldn't be able to use it.  Because of that, I don't have IPv6 set up on my network.  Everything's just using the default link-local addresses.  Is that still likely to make a difference here?

**Comment by cuonglm** [comment]
> So, you're right that I don't have IPv6 set up.  But, my ISP is unfortunately a bit behind the times and doesn't offer IPv6 connectivity just yet (they're aiming for some time in the next few months).  So, even if something resolves a AAAA record, it wouldn't be able to use it.  Because of that, I don't have IPv6 set up on my network.  Everything's just using the default link-local addresses.  Is that still likely to make a difference here?

AAAA record is only meaningful if you are using IPv6 connectivity.

I only explain your original question that why nslookup returns CNAME.
