### ISSUE TITLE
Ctrld detected as trojan Wacatac

### ISSUE THREAD

**Issue by domy86** [Control-D-Inc/ctrld#181]
Hi,

Microsoft Defender just showed me a message about trojan Wacatac in ctrld service.

![Screenshot_20240920_111159](https://github.com/user-attachments/assets/b58258c3-f4f8-443f-b50d-0c5aa97ce402)

It killed and quarantined the file. Added to exclusion list and works fine again.

Please take a look!

EDIT:

ctrld version v1.3.8

**Comment by yegors** [comment]
This is obviously a false detection. It should clear up on its own.
