### ISSUE TITLE
"error":"fork/exec /usr/bin/mongo: permission denied"

### ISSUE THREAD

**Issue by ikolsteren** [Control-D-Inc/ctrld#185]
I am running on a Gateway Max with Network 8.6.3 

I have not been able to get the the ctrld service started

This is the full debug log
 '''
{"level":"info","time":"2024-10-21T10:46:08-04:00.245","message":"starting ctrld v1.3.9"}
{"level":"info","time":"2024-10-21T10:46:08-04:00.456","message":"os: linux Debian GNU/Linux 11 (bullseye) (5.4.213-ui-ipq5322)"}
{"level":"info","bootstrap_ip":"76.76.2.22","time":"2024-10-21T10:46:08-04:00.458","message":"using bootstrap IP for upstream.0"}
{"level":"info","time":"2024-10-21T10:46:08-04:00.465","message":"starting DNS server on listener.0: 0.0.0.0:5354"}
{"level":"error","error":"fork/exec /usr/bin/mongo: permission denied","time":"2024-10-21T10:46:08-04:00.466","message":"could not init Ubios discover"}
{"level":"info","time":"2024-10-21T10:46:59-04:00.346","message":"Service stopped"}
'''

**Comment by yegors** [comment]
Hmm this shouldn't be a fatal error. @cuonglm ?

**Comment by ikolsteren** [comment]
I just did another reboot and looks like the service is started - will try and configure other profiles and see if I continue to be successful

**Comment by cuonglm** [comment]
> Hmm this shouldn't be a fatal error. @cuonglm ?

It's not a fatal error, just an error message.

Sounds like the service was stopped because of something else. The error was emitted at `10:46:08`, the service was stopped at `10:46:59`.

**Comment by cuonglm** [comment]
Also, this is not a fatal error, but graceful shutdown since ctrld was received either SIGTERM or SIGINT, emitting stopping message and quit.

**Comment by ikolsteren** [comment]
Looks like the problem is related to having site magic enabled.  I had made sure I had all other adblocking and services turned off but as soon as I shut down site magic and rebooted then the service was able to start.  Might be a note to have in the readme as I tried that reading another closed issue

**Comment by cuonglm** [comment]
> Looks like the problem is related to having site magic enabled.  I had made sure I had all other adblocking and services turned off but as soon as I shut down site magic and rebooted then the service was able to start.  Might be a note to have in the readme as I tried that reading another closed issue

FYI, next release will make ctrld works with site magic VPN.

In the meantime, you could try dev version to experiment this support.

**Comment by cuonglm** [comment]
> Just tried this morning with the dev build. Same issue where service wouldn't start. I updated to dev, started service no issue. Created a Site VPN using Site Magic and tried to start the service again and no luck. Rebooted the gateway and no luck. Removed Site VPN and tried to start on luck. Rebooted the Gateway and Service is back enabled.

Could you please provide more details information, like logs or which steps/commands that you run?

**Comment by ikolsteren** [comment]
I have attached the log from when i tried to start with Site Magic enabled

Prior to Site magic here are my commands and replies from the Gateway

root@UXGMax:~# ctrld upgrade dev
Oct 22 06:54:45.000 NTC Upgrade successful - dev-6b1c068

Service before Site Magic turned on
root@UXGMax:~# ctrld start --log /tmp/ctrld.log -v
Oct 22 06:54:54.000 NTC Reading config: /etc/controld/ctrld.toml
Oct 22 06:54:54.000 INF loading config file from: /etc/controld/ctrld.toml
Oct 22 06:54:54.982 NTC Starting service
Oct 22 06:55:11.032 NTC Service started

When I enabled after Site magic i used ctrld start --log /tmp/ctrld.log -vv
[ctrld.log](https://github.com/user-attachments/files/17476513/ctrld.log)

**Comment by ikolsteren** [comment]
In the unifi GUI i dont see anything in the log.   I thought I saw something with a DNS on 192.168.2.0 which is the Site Magic self assigned IP range

**Comment by ikolsteren** [comment]
Looks like it was having a VPN client installed on the gateway even though I didn't have any routing polices to use that.  
Installed the latest update and working ok.  Haven't installed site magic again.
