### ISSUE TITLE
failed to start in ctrld 1.3.10

### ISSUE THREAD

**Issue by malikshi** [Control-D-Inc/ctrld#189]
Hi,
currently i am using automatic upgrade via downloading binary from release page. i have problem that 1.3.10 won't start with this error.
```
ctrld start -c /etc/controld/ctrld.toml
Oct 30 05:56:04.000 NTC Reading config: /etc/controld/ctrld.toml
Oct 30 05:56:04.393 NTC Starting service
Oct 30 05:56:04.984 DBG waiting for ctrld listener to be ready
Oct 30 05:56:15.120 DBG ctrld listener is ready
Oct 30 05:56:15.120 DBG performing self-check
Oct 30 05:56:15.131 ??? ================================
Oct 30 05:56:15.131 ??? An error occurred while performing test query: read udp 127.0.0.1:25894->127.0.0.1:53: read: connection refused
Oct 30 05:56:15.131 ??? ================================
Oct 30 05:56:15.419 DBG Restoring DNS for interface iface=eth0
Oct 30 05:56:17.428 DBG dns: [rc=resolvconf resolvconf=openresolv ret=openresolv]
Oct 30 05:56:17.428 DBG dns: using "openresolv" mode
Oct 30 05:56:17.459 DBG DNS was not set for some reason
Oct 30 05:56:17.478 DBG Restoring DNS successfully iface=eth0
Oct 30 05:56:17.478 NTC Service uninstalled
```
i tried to downgrade to 1.3.9 then upgrade with recommended command in Notes
ctrld uninstall and ctrld upgrade prod but seem still failed to start with same error.

i tried other command like ctrld run -c /etc/controld/ctrld.toml and it's work for `run` command

**Comment by cuonglm** [comment]
Thanks for reporting.

If you do `ctrld start` with `--skip_self_checks`, is ctrld running then? Are you able to send query to ctrld listener?

Sounds like something blocks query to localhost causing connection refuse error.

**Comment by NoSync** [comment]
I get the same on OpenWRT, while everything works correctly if I add `--skip_self_checks`. 1.3.9 works as expected.

**Comment by yegors** [comment]
Please try v1.3.11 and provide a full debug log (launch with --log /path/to/log.log)

**Comment by NoSync** [comment]
1.3.11 completely solves the issue for me.
