### ISSUE TITLE
[v1.1.0] MacOS could not fetch resolver config

### ISSUE THREAD

**Issue by diegoscl** [Control-D-Inc/ctrld#19]
When I try to install ctrld 1.1 I get the following error: `WRN could not fetch resolver config error="client.Do: Post \"https://api.controld.com/utility?platform=ctrld\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" mode=cd prefix=main`

### CONTEXT
Upstream of my Mac (macOS Ventura 13.2) I have my Asus router running with no problem configured with ControlD running as device "A". I am trying to configure my Mac with CtrlD as device "B" so I can have a custom profile.

### ADDITIONAL INFO
1. PING
```
PING api.controld.com (147.185.34.1): 56 data bytes
64 bytes from 147.185.34.1: icmp_seq=0 ttl=58 time=4.279 ms
64 bytes from 147.185.34.1: icmp_seq=1 ttl=58 time=7.663 ms
64 bytes from 147.185.34.1: icmp_seq=2 ttl=58 time=10.093 ms
64 bytes from 147.185.34.1: icmp_seq=3 ttl=58 time=8.426 ms
64 bytes from 147.185.34.1: icmp_seq=4 ttl=58 time=4.616 ms

--- api.controld.com ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.279/7.015/10.093/2.242 ms
```

2. TRACEROUTE
```
traceroute to api.controld.com (147.185.34.1), 64 hops max, 72 byte packets
 1  192.168.50.1 (192.168.50.1)  4.936 ms  2.264 ms  2.074 ms
 2  static.190.215.176.2.gtdinternet.com (190.215.176.2)  4.831 ms  2.540 ms  2.873 ms
 3  * * *
 4  * * *
 5  cn2.ae5.200.agre2mq.gtdinternet.com (190.196.124.214)  4.690 ms  3.966 ms  3.740 ms
 6  edgeuno-7195.scl.pitchile.cl (45.68.16.79)  4.640 ms  39.820 ms  4.250 ms
 7  ae0.0.edge1.scl1.as7195.net (200.25.51.8)  4.076 ms  5.116 ms  3.894 ms
 8  controld.com (147.185.34.1)  3.980 ms  3.937 ms  4.255 ms
```

3. As an additional test, when I activate Cloudflare WARP, to have a different interface with own DNS, CtrlD is configured and activated, but I have no connectivity. Doing `dig` to any domain I get a timeout error.

**Comment by yegors** [comment]
Hi,

This is rather odd. Without CF Warp, can you visit this URL in the browser? You should get a json response (not implemented): https://api.controld.com/utility

As for the 2nd issue, you mentioned dig timeouts, can you provide the full output when you dig verify.controld.com

Additionally, what was the exact command that you used to start the service (you can omit your resolver ID), and where there any errors printed except for one you mentioned above? When the utility starts, it starts on a listener, can you dig against that specific listener?

**Comment by yegors** [comment]
Hmm, very unusual. We never tested this with WARP, as it makes routing changes and probably not recommended to use both at the same time, but we'll test it.  

Can you try the following:

1. Disable WARP
2. Run `service uninstall` command
3. Make sure your DNS works, and is not using the 127.0.0.1 listener if thats still statically assigned on your network interface. Dig should work normally. 
4. Run ctrld just with the `start` command, no extra flags of any kind. 

Does it start normally, and spawn the listener, and have DNS work if you dig against 127.0.01?

**Comment by diegoscl** [comment]
> Hmm, very unusual. We never tested this with WARP, as it makes routing changes and probably not recommended to use both at the same time, but we'll test it.

To be honest, I used CF WARP just as a test trying to do something different because nothing was working and there I found that CtrlD does resolve the configuration using it. I come from NextDNS and when using WARP always the CF resolver has priority over the local proxy.

Ok, so I go step by step:

> 1. Disable WARP

Done ✅

> 2. Run `service uninstall` command

```
❯ sudo /Users/diego/Applications/ctrld service uninstall
Password:
Feb  9 17:48:20.421 INF Service uninstalled prefix=main
```

> 3. Make sure your DNS works, and is not using the 127.0.0.1 listener if thats still statically assigned on your network interface. Dig should work normally.

```
❯ dig verify.controld.com
; <<>> DiG 9.10.6 <<>> verify.controld.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6507
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;verify.controld.com.		IN	A

;; ANSWER SECTION:
verify.controld.com.	20	IN	CNAME	api.controld.com.
api.controld.com.	300	IN	A	147.185.34.1

;; Query time: 115 msec
;; SERVER: 192.168.50.1#53(192.168.50.1)
;; WHEN: Thu Feb 09 17:49:11 -03 2023
;; MSG SIZE  rcvd: 71
```

192.168.50.1 is my router and it has ControlD configured, so it is expected to resolve OK verify.controld.com

> 4. Run ctrld just with the `start` command, no extra flags of any kind.

```
❯ sudo /Users/diego/Applications/ctrld start
writing default config file to: /Users/diego/ctrld.toml
Feb  9 17:53:16.161 INF Service started prefix=main
```
 
> Does it start normally, and spawn the listener, and have DNS work if you dig against 127.0.01?

```
❯ dig verify.controld.com @127.0.0.1
; <<>> DiG 9.10.6 <<>> verify.controld.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36068
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;verify.controld.com.		IN	A

;; ANSWER SECTION:
verify.controld.com.	20	IN	CNAME	api.controld.com.
api.controld.com.	300	IN	A	147.185.34.1

;; Query time: 64 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Feb 09 17:54:13 -03 2023
;; MSG SIZE  rcvd: 118
```

Success! Now it works, but without identifying my device...

**Comment by diegoscl** [comment]
After the above steps and confirming that everything was working OK, I manually changed the `[upstream.0] `parameters in the `ctrld.toml` file in my user directory and now it works associated to the correct device... 

The only bad thing is that the file is in my user directory, which messes me up a bit... but I can get used to it 🤔 ...

**Comment by yegors** [comment]
You can move it anywhere and use `--config` flag when you `start` to supply the path to it.

**Comment by cuonglm** [comment]
@diegoscl Thanks for reporting.

Would you mind testing with attached binary, to see if it fixed the issue for you?
[ctrld.tar.gz](https://github.com/Control-D-Inc/ctrld/files/10709914/ctrld.tar.gz)

**Comment by diegoscl** [comment]
> You can move it anywhere and use `--config` flag when you `start` to supply the path to it.

It worked as expected! Thank you!

**Comment by cuonglm** [comment]
@diegoscl Would you mind trying attached binary to see if it fixed the fetching resolver config problem.

Thank you.

[ctrld.tar.gz](https://github.com/Control-D-Inc/ctrld/files/10710158/ctrld.tar.gz)

**Comment by diegoscl** [comment]
> @diegoscl Would you mind trying attached binary to see if it fixed the fetching resolver config problem.
> 
> Thank you.
> 
> [ctrld.tar.gz](https://github.com/Control-D-Inc/ctrld/files/10710158/ctrld.tar.gz)

I got this:

```
❯ sudo ./ctrld start --cd XXX
Password:
[1]    6270 segmentation fault  sudo ./ctrld start --cd XXX
```

**Comment by cuonglm** [comment]
> > @diegoscl Would you mind trying attached binary to see if it fixed the fetching resolver config problem.
> 
> > 
> 
> > Thank you.
> 
> > 
> 
> > [ctrld.tar.gz](https://github.com/Control-D-Inc/ctrld/files/10710158/ctrld.tar.gz)
> 
> 
> 
> I got this:
> 
> 
> 
> ```
> 
> ❯ sudo ./ctrld start --cd XXX
> 
> Password:
> 
> [1]    6270 segmentation fault  sudo ./ctrld start --cd XXX
> 
> ```

What is your Mac architecture?

**Comment by diegoscl** [comment]
Apple Silicon - ARM64 🤔

**Comment by cuonglm** [comment]
> Apple Silicon - ARM64 thinking

Please try this one, thank you.
[ctrld.tar.gz](https://github.com/Control-D-Inc/ctrld/files/10716203/ctrld.tar.gz)

**Comment by diegoscl** [comment]
Bad news...

```
❯ sudo ./ctrld start --cd XXXXXXX
loading config file from: /Users/diego/ctrld.toml
Feb 12 11:55:44.806 INF fetching Controld-D configuration mode=cd
Feb 12 11:55:54.808 WRN could not fetch resolver config error="client.Do: Post \"https://api.controld.com/utility?platform=ctrld\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" mode=cd
Feb 12 11:55:54.863 INF Service started
```

**Comment by cuonglm** [comment]
@diegoscl Would you mind trying this:

```
$ export GODEBUG=http2debug=2
$ sudo -E ./ctrld run --cd p2 -vv
```

then paste the output here/.

**Comment by yegors** [comment]
This issue is resolved in the latest release.
