### ISSUE TITLE
Image too large for openwrt 23.05.5 

### ISSUE THREAD

**Issue by viniribeirossa** [Control-D-Inc/ctrld#191]
Please provide a smaller version, equal to the previous version

https://github.com/Control-D-Inc/ctrld/releases/download/v1.3.10/ctrld_1.3.10_linux_mipsle.tar.gz

This version was very

**Comment by cuonglm** [comment]
Thanks for reporting.

It seems that some of libraries that we used increasing the size unexpectedly.

We will investigate this.

**Comment by cuonglm** [comment]
The binary size was decreasing again in v1.3.11

**Comment by viniribeirossa** [comment]
Thank you. I installed it and it worked correctly!
