### ISSUE TITLE
Errors unifi

### ISSUE THREAD

**Issue by it-can** [Control-D-Inc/ctrld#193]
I see these errors daily, is it a problem? Or can i ignore them?

`level":"error","time":"2024-11-09T17:59:46+01:00.999","message":"[6014a7] all [upstream.0] endpoints failed"}
{"level":"error","error":"deadline exceeded","time":"2024-11-09T17:59:47+01:00.004","message":"[efc5da] failed to resolve query"}
{"level":"error","time":"2024-11-09T17:59:47+01:00.005","message":"[efc5da] all [upstream.0] endpoints failed"}
{"level":"error","error":"deadline exceeded","time":"2024-11-09T17:59:47+01:00.340","message":"[d08129] failed to resolve query"}
{"level":"error","time":"2024-11-09T17:59:47+01:00.341","message":"[d08129] all [upstream.0] endpoints failed"}
{"level":"error","error":"deadline exceeded","time":"2024-11-09T17:59:47+01:00.343","message":"[ff1536] failed to resolve query"}
{"level":"error","time":"2024-11-09T17:59:47+01:00.343","message":"[ff1536] all [upstream.0] endpoints failed"}
{"level":"error","error":"deadline exceeded","time":"2024-11-09T17:59:48+01:00.052","message":"[ac396f] failed to resolve query"}
{"level":"error","time":"2024-11-09T17:59:48+01:00.053","message":"[ac396f] all [upstream.0] endpoints `failed"}`

I use a Cloud-Gateway-Max from unifi

**Comment by cuonglm** [comment]
It indicates that you cannot connect to upstream server. If you still have internet access then, you could be fine.
