### ISSUE TITLE
Local client name resolution does not work after Edgerouter restart

### ISSUE THREAD

**Issue by raufeisen** [Control-D-Inc/ctrld#196]
Steps to reproduce:
- Install ctrld via install script
- name resolution for local clients works and clients are shown in the analytics client section in controld interface with their hostnames
- restart edgerouter
- all clients have no names any more and are just reported with mac address names
- ctrld restart
- all clients are again reported with their hostnames

I had to add the dnsmasq.service in the ctrld.service file for Wants and After

https://github.com/Control-D-Inc/ctrld/blob/09495f2a7cd6c9da5b94d85c4b5c2a66bf9c4be3/cmd/cli/prog_linux.go#L29
```
Wants=dnsmasq.service
After=dnsmasq.service
```

**Comment by ericnixmd** [comment]
Also seeing this with an EFG.  Rebooting EFG has hostnames only (i.e., ericsmacstudio) but after restarting ctrld it will show properly ("Eric's Mac Studio").

**Comment by ericnixmd** [comment]
This seems to be fixed.  Not sure if it was addressed by ctrld or if something changed with UniFi gateway firmware.

**Comment by ericnixmd** [comment]
Had an issue where my cable service went out today causing need for failover WAN.  EFG did not go down.  Came home to find that clients went from what was listed in UniFi Network to netbios names instead.  Had to restart ctrld to get it back to the customized client names again.
