### ISSUE TITLE
CNAME Flattening

### ISSUE THREAD

**Issue by ExtRIELICi** [Control-D-Inc/ctrld#197]
CNAME flattening improves DNS performance primarily by reducing the number of DNS queries required to resolve a domain name. Here’s how it enhances performance:

- Reduced DNS Queries: Traditional CNAME records require multiple lookups to resolve a domain name to an IP address, as each CNAME points to another domain that must be resolved. CNAME flattening eliminates these additional queries by resolving the CNAME chain internally and returning the final IP address directly. This process can significantly speed up DNS resolution times.

- Faster Resolution Times: By reducing the need for multiple DNS lookups, CNAME flattening can decrease the time required for DNS resolution by up to 30% on average. This improvement is particularly beneficial for domains using cloud services, where IP addresses frequently change.

- Efficient Handling of Root Domains: CNAME flattening allows CNAME records to be used at the root of a domain, which is traditionally not allowed. This capability provides flexibility and efficiency in managing DNS records without violating DNS specifications.

From my understanding, ControlD does not have this feature yet. It would be really nice to see.

**Comment by yegors** [comment]
Your AI generated text is not relevant to this repo.
