### ISSUE TITLE
GUI control

### ISSUE THREAD

**Issue by ericnixmd** [Control-D-Inc/ctrld#202]
I really like the ability to edit config on Control D's website and have ctrld pull the config with a restart.

Would be cool if the ctrld daemon polled the Control D's endpoint so that other things could be possible.  In addition to having ability to update config file by polling every 5-10 mins, maybe poll it for an option to upgrade, restart, etc.  Would require collaboration with Control D to develop the GUI.

**Comment by yegors** [comment]
You can change the config polling interval using a config param: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#refetch_time

The config is also auto-fetched if you visit the status page, this triggers an immediate config re-fetch.

The GUI app bundles the CLI under the hood, so there is nothing that needs to be added to it.

**Comment by ericnixmd** [comment]
Sorry, I didn't even know that was in current builds.

So if I update the config file, I can just wait the default 3600 seconds and it will automatically pull the new config and implement it?  (I'm assuming this is 3600/on by default?)

**Comment by cuonglm** [comment]
> Sorry, I didn't even know that was in current builds.
> 
> 
> 
> So if I update the config file, I can just wait the default 3600 seconds and it will automatically pull the new config and implement it?  (I'm assuming this is 3600/on by default?)

Yes, but only if you started ctrld with "--cd" flag.
