### ISSUE TITLE
 ERR could not set DNS for interface error="setLinkDNS: Link eth0 is managed." iface=eth0 prefix=main

### ISSUE THREAD

**Issue by ProTechEx** [Control-D-Inc/ctrld#21]
How can I solve this issue ?

```
root@mpd3:~# ./ctrld start --cd xxxxxxxxxxxxx
loading config file from: /root/ctrld.toml
Feb 10 19:58:34.574 INF fetching Controld-D configuration mode=cd prefix=main
Feb 10 19:58:34.731 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
Feb 10 19:58:34.731 INF writing config file to: /root/ctrld.toml mode=cd prefix=main
Feb 10 19:58:35.674 ERR could not set DNS for interface error="setLinkDNS: Link eth0 is managed." iface=eth0 prefix=main
Feb 10 19:58:35.674 INF Service started prefix=main
```

**Comment by yegors** [comment]
Hi,

We're tracking this issue that happens on some linux installations. What you can do in the mean time is start the service without DNS assignment using `./ctrld service start --cd xxxxxxxxxxxxx` command. Then update your NIC's DNS servers manually, to the listener the utility spawned (usually 127.0.0.1).

**Comment by ProTechEx** [comment]
Sorry I didn't understand what exatly wou mean wirth "update your NIC's DNS servers manually, to the listener the utility spawned (usually 127.0.0.1)."

Can please explain more in details, how to do this part ?

**Comment by yegors** [comment]
Run the above mentioned command, which should start the service but not update the DNS on any network interface.

Then update the DNS server on the network interface you use. Looks like eth0.

**Comment by ProTechEx** [comment]
1.  When this issue will be fixed at all ?
2.  I am using Ubuntu 20.04, the cloud based VPS (Hetzner).  
    It does use /etc/netplan/50-cloud-init.yaml which looks like:

![](https://user-images.githubusercontent.com/5677301/218332411-fba5d597-d752-466d-9f9c-5ff8cec31446.png)

The ctrld.toml looks like

![](https://user-images.githubusercontent.com/5677301/218332507-19fc40af-d3f2-48aa-8e0d-0025cc7e616a.png)

I don't know, what exatly I have to change where exatly :(

**Comment by cuonglm** [comment]
@ProTechEx 

> When this issue will be fixed at all ?

This will be included in next release.

> I don't know, what exatly I have to change where exatly :(

After starting `ctrld`, just do `resolvectl dns eth0 127.0.0.1`.

**Comment by ProTechEx** [comment]
![](https://user-images.githubusercontent.com/5677301/218559384-949b6de3-8e04-4dba-b156-d918b28ccc6e.png)

**Comment by yegors** [comment]
There is something non-standard about your VM. The above error shouldn't happen under normal circumstances. Considering this is a heavily managed VM, with cloud-init, which will likely rollback all your setting son reboot.  

You can try disabling cloud-init as suggested in the config comments you posted.

**Comment by ProTechEx** [comment]
I disabling cloud-init as suggested in the config comments.  
But Still get:  
root@mpd3:~# ./ctrld start --cd xxxxxxxxxxxxxxx  
loading config file from: /root/ctrld.toml  
Feb 14 13:53:36.365 INF fetching Controld-D configuration mode=cd prefix=main  
Feb 14 13:53:36.528 INF generating ctrld config from Controld-D configuration mode=cd prefix=main  
Feb 14 13:53:36.529 INF writing config file to: /root/ctrld.toml mode=cd prefix=main  
Feb 14 13:53:37.526 **ERR could not set DNS for interface error="setLinkDNS: Link eth0 is managed."** iface=eth0 prefix=main  
Feb 14 13:53:37.527 INF Service started prefix=main

**Comment by cuonglm** [comment]
> ![](https://user-images.githubusercontent.com/5677301/218559384-949b6de3-8e04-4dba-b156-d918b28ccc6e.png)

It's `resolvectl dns eth0 127.0.0.1`, you did `resolvectl dns eth0 127.0.0.1.`

**Comment by ProTechEx** [comment]
Any date for the new update ?  
When the update will be released ?  
  
I have another concern.   
The current documentation for using the CONTROL D Control Panel is very worst.  
There is so much points and stuff that is unexplained.  
  
For example, I still didn't undersand which confgurations I have to do If want bypass the IP geostrictions if connect to a cretain country. Does CONTROL D auto detect the connected country and bypass the IP restriction or did I need do I manually ?  
And steps I need to do on the Panel if want reach the cretain country/service ?

**Comment by yegors** [comment]
Literally see 2 comments above yours, for the updates....

Other comments unrelated to ctrld do not belong in this thread, however documentation can be found here: https://docs.controld.com/docs

**Comment by yegors** [comment]
This issue should be resolved in latest release.
