### ISSUE TITLE
[New Feature] Prometheus metrics exporter

### ISSUE THREAD

**Issue by yegors** [Control-D-Inc/ctrld#29]
This feature is on the roadmap, and this issue is meant to collect feedback for useful metrics to export. 

Current scope includes:
- listener specific metrics for total queries served 
- Attach labels for triggered network and split DNS rules
- Attach label for upstream used to serve the request 
- Standard golang stack memory/threads metrics 

If there are other suggestions, please list them here.

**Comment by cuonglm** [comment]
Two on top of my head:

- Cache hits/miss
- Re-bootstrapping event

**Comment by jtovar43** [comment]
Some other useful metrics would also be
* Request per second
* Top clients
* Upstream latency (PoP and protocol as some of the labels)

**Comment by yegors** [comment]
This is now available in v1.3.4
