### ISSUE TITLE
ERR could not set DNS for interface error

### ISSUE THREAD

**Issue by ProTechEx** [Control-D-Inc/ctrld#36]
root@Ubuntu-1804-bionic-64-minimal ~ # ./ctrld start  
loading config file from: /root/ctrld.toml  
Mar 28 06:16:10.037 INF Service started  
Mar 28 06:16:10.041 ERR could not set DNS for interface error="setLinkDNS: Rejected send message, 2 matched rules; type=\\"method\_call\\", sender=\\":1.25\\" (uid=0 pid=7713 comm=\\"./ctrld start \\" label=\\"unconfined\\") interface=\\"org.freedesktop.network1.Manager\\" member=\\"SetLinkDNS\\" error name=\\"(unset)\\" requested\_reply=\\"0\\" destination=\\"org.freedesktop.network1\\" (uid=100 pid=543 comm=\\"/lib/systemd/systemd-networkd \\" label=\\"unconfined\\")" iface=enp27s0

**Comment by cuonglm** [comment]
@ProTechEx What `ctrld` version did you use?

**Comment by ProTechEx** [comment]
**v1.1.3**

**Comment by cuonglm** [comment]
> **v1.1.3**

Thanks!

Would you mind giving us more details about your OS information?

- It's cloud server or physical laptop?
- `uname -a` output
- `resolvectl` output

**Comment by ProTechEx** [comment]
root@Ubuntu-1804-bionic-64-minimal ~ # uname -a  
Linux Ubuntu-1804-bionic-64-minimal 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86\_64 x86\_64 x86\_64 GNU/Linux

root@Ubuntu-1804-bionic-64-minimal ~ # systemd-resolve  
No arguments passed.

**Comment by yegors** [comment]
As there is no movement here, closing this issue. Feel free to give the latest version a try.
