### ISSUE TITLE
when using log file, messages still sent to syslog

### ISSUE THREAD

**Issue by katchy3132** [Control-D-Inc/ctrld#49]
if I have the following setting in the ctrld.toml : 
```
log_level = 'debug'
log_path = '/var/log/controld.log'
```
or just using the command line flag` --log=/var/log/controld.log` 

output indeed goes to the log file but it does not stop it from going to syslog as well. it should be one or the other (or at least a way to turn off the syslog )

**Comment by yegors** [comment]
What OS are you running this on? What if you write it to a different directory, that's not /var/log?  

You should also be able to configure syslog to not write the log data for specific programs.

**Comment by katchy3132** [comment]
Debian and Ubuntu 20.04. changing to /tmp/varlog/controld.log  didn't change anything but I was able to configure syslog to filter out the messages. 
Still seems to me that ctrld shouldnt be producing the output in the first place.

**Comment by cuonglm** [comment]
@katchy3132 FYI, ctrld output to console and log file (when configured, aka `--log`). What's your system service manager? Is it systemd or SysV?

**Comment by katchy3132** [comment]
> @katchy3132 FYI, ctrld output to console and log file (when configured, aka `--log`). What's your system service manager? Is it systemd or SysV?

systemd

**Comment by cuonglm** [comment]
> > @katchy3132 FYI, ctrld output to console and log file (when configured, aka `--log`). What's your system service manager? Is it systemd or SysV?
> 
> systemd

Then the systemd service file will be configured to use:

```
StandardOutput=file:/var/log/ctrld.out
StandardError=file:/var/log/ctrld.err
```

Is this the syslog you mentioned?

**Comment by cuonglm** [comment]
> > > @katchy3132 FYI, ctrld output to console and log file (when configured, aka `--log`). What's your system service manager? Is it systemd or SysV?
> > 
> > 
> > systemd
> 
> Then the systemd service file will be configured to use:
> 
> ```
> StandardOutput=file:/var/log/ctrld.out
> StandardError=file:/var/log/ctrld.err
> ```
> 
> Is this the syslog you mentioned?

Ah wait, those lines aren't set with default configuration that `ctrld` uses, so probably something else.

**Comment by yegors** [comment]
Please try the latest v1.3.0 release.
