### ISSUE TITLE
Support for Unifi USG routers

### ISSUE THREAD

**Issue by sanderpleijers** [Control-D-Inc/ctrld#52]
Installing Control D on a Unifi USG fails (see: https://store.ui.com/us/en/collections/unifi-accessory-tech-hosting-and-gateways-small-scale/products/usg):

`sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)" -s *snip* forced' ` fails loading the service.

Further testing:

```
admin@Router:~$ sudo su -
root@Router:~# cd /usr/local/bin
root@Router:/usr/local/bin# ./ctrld setup auto --cd *snip*-vv
May 26 20:24:01.000 ERR Unsupported or incorrectly chosen router platform. Please open an issue and provide all relevant information: https://github.com/Control-D-Inc/ctrld/issues/new
root@Router:/usr/local/bin#
```

**Comment by yegors** [comment]
We ordered a test device, will add support for this when it arrives.

**Comment by yegors** [comment]
This is resolved in the latest release: https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.0
