### ISSUE TITLE
ctrld doesn’t detect all devices.

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#53]
I just installed a Google Home speaker, but ctrld doesn't detect it.

However, it is detected by the router where ctrld is installed.

How can I force ctrld to detect all devices on my network?

**Comment by cuonglm** [comment]
What's your router?

**Comment by cuonglm** [comment]
> How can I verify if the device is making a DNS query through another service?

I don't know much about Google Home speaker, how did you config it? Does it have an IP address in your LAN?

> Does ctrld intercept DNS queries sent to other DNS services?

No, ctrld only configures your router to send DNS query to configured upstream.

**Comment by pmcarrion** [comment]
> I don't know much about Google Home speaker, how did you config it? Does it have an IP address in your LAN?

It has an IP address and is connected to the network via Wi-Fi. I linked it to my Google account using the Google Home app. No extra config was needed.

> No, ctrld only configures your router to send DNS query to configured upstream.

DNS intercept would be a great feature for ctrld.

**Comment by pmcarrion** [comment]
Google devices (Chromecast, speakers, etc.) are hard-coded to use Google's DNS servers.

I have 2 options:
1. Block Google's DNS servers and let these devices fall back to using the router's DNS servers.
2. Redirect Google's DNS servers to ctrld, but I need the IP address of the server used by ctrld on the router. Is it 127.0.0.1 as in the computer? 

My network has IPv6 enabled, so this presents an additional challenge.

Furthermore, Asus Merlin has a feature called DNS Director, and it could help to achieve this without involving iptables.

What's the best approach to make ctrld manage DNS queries from these devices?

**Comment by yegors** [comment]
Closing this in favor of https://github.com/Control-D-Inc/ctrld/issues/56
