### ISSUE TITLE
Duplicate devices on router

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#54]
ctrld on my Asuswrt-Merlin router detects a device as expected, but is showing two devices in the clients section with the same IP and MAC addresses.
One is named correctly, and the other one has an asterisk.
Both are the same device.

Is this a known issue with some devices?

**Comment by cuonglm** [comment]
@pmcarrion Could you please give me your dnsmasq lease file (with sensitive information reducted)?

**Comment by pmcarrion** [comment]
@cuonglm Sure, please tell me how to get that file!

**Comment by cuonglm** [comment]
> @cuonglm Sure, please tell me how to get that file!

On Asus Merlin, the lease file is `/var/lib/misc/dnsmasq.leases`

**Comment by cuonglm** [comment]
@pmcarrion What appears later in your dashboard? The entry with `*` hostname or the entry with real hostname?

**Comment by pmcarrion** [comment]
@cuonglm The entry with the real name appears later.

**Comment by cuonglm** [comment]
> @cuonglm The entry with the real name appears later.

Thanks.

Client hostname will be asterisk if it does not specify the hostname when requesting DHCP lease.

Maybe related: https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=32827

So at least ctrld is working properly when changes are made to lease file:

- First, your laptop is recorded in lease file with given mac, ip, and `*` hostname.
- Then DHCP updates your laptop entry with real hostname, and ctrld updates your laptop info accordingly.

**Comment by pmcarrion** [comment]
All my devices have a hostname in the router, but I guess this information isn't always passed on as it should.

Some devices always show an asterisk of a hostname, but these are not duplicated.

Perhaps you can implement two options in ctrld and the Control D Dashboard:
1) Ability to rename devices (useful for those only named with an asterisk).
2) Ability to merge devices by MAC address in case of duplicates.

**Comment by pmcarrion** [comment]
> 1. Ability to rename devices (useful for those only named with an asterisk).
> 2. Ability to merge devices by MAC address in case of duplicates.

I see… then these suggestions for the Control D Dashboard would be very helpful.

**Comment by yegors** [comment]
1. The list should show what is known to the router, deviating from the "source of truth" is not a good idea. 
2. That could be a good UI option, we will think about this one.

**Comment by pmcarrion** [comment]
> 1. The list should show what is known to the router, deviating from the "source of truth" is not a good idea.

You can maintain the original `*` name next to the desired hostname. This is useful for identifying devices on networks with several unidentified devices.

My network currently reports 6 asterisks to Control D. It's a hassle to go back to the router's dashboard and search for the unidentified device by MAC address.

**Comment by yegors** [comment]
The `*` is as a result of WiFI Privacy being enabled on an Apple device, If you toggle it OFF for the WiFI network, a proper hostname will be shown.
