### ISSUE TITLE
EdgeOS - hangs

### ISSUE THREAD

**Issue by achmeed** [Control-D-Inc/ctrld#58]
Been trying the ctrld cmdline on EdgeOs but it crashes/hangs and cant really see any output why.
Service is running and has to be restarted.

During setup you'll also have to have your edgerouter using Ctrld DNS servers otherwise it will file if systemdns uses i.e google or cloudflare.

is there a way to specify log file location when using -vv ?

**Comment by yegors** [comment]
Yes, you can do it like so: `--log /path/to/log.log`  or using a config: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#log_path

**Comment by achmeed** [comment]
Thanks, added it and will see what it sais next time it hangs

**Comment by yegors** [comment]
Thanks, please let us know what you find. Also, what specific router model + EdgeOS version are you using?

**Comment by achmeed** [comment]
-06-15T19:04:56+02:00","time":"2023-06-15T19:04:56+02:00","message":"[40e8ff] could not resolve query on first attempt, retrying..."}
{"level":"debug","time":"2023-06-15T19:04:56+02:00","time":"2023-06-15T19:04:56+02:00","message":"[58db94] received response of 35 bytes in 23.078897355s"}
{"level":"error","time":"2023-06-15T19:04:56+02:00","time":"2023-06-15T19:04:56+02:00","message":"[a0f83a] all upstreams failed"}
{"level":"debug","time":"2023-06-15T19:04:56+02:00","time":"2023-06-15T19:04:56+02:00","message":"[a0f83a] received response of 35 bytes in 21.641610428s"}
{"level":"error","time":"2023-06-15T19:04:56+02:00","time":"2023-06-15T19:04:56+02:00","message":"[990b08] all upstreams failed"}
{"level":"debug","time":"2023-06-15T19:04:56+02:00","time":"2023-06-15T19:04:56+02:00","message":"[990b08] received response of 34 bytes in 25.091412933s"}


Running EdgeRouter X v2.0.9-hotfix.4

**Comment by yegors** [comment]
@achmeed if you can send me the complete log, it would be nice - yegor@controld.com 

Thanks

**Comment by yegors** [comment]
This is resolved in the latest release: https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.0
