### ISSUE TITLE
ctrld can't fetch service parameters

### ISSUE THREAD

**Issue by kplttdaj1494** [Control-D-Inc/ctrld#62]
ctrld 1.2.1, openwrt 22.03.5
I'm using controld.com dashboard to add [service] parameters, save them, then restart ctrld service on a router, in the dashboard I can see that parameters was fetched, but in ctrld.toml there is no [service] parameters which I add. Other parameters fetched correctly. I'm not creating config file manually, just add parameters in dashboard.
Config example in controld.com dashboard:
```
[service]
    log_level = "error"
    log_path = ""
    cache_enable = true
    cache_size = 4096
    cache_ttl_override = 60
    cache_serve_stale = true
[listener]
  [listener.0]
    ip = '127.0.0.1'
    port = 53

    [listener.0.policy]
      name = 'My Policy'

[network]
  [network.0]
    name = 'Network 0'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    type = 'doh3'
    endpoint = 'https://dns.controld.com/my_id'
    timeout = 5000
```

Created config:
```
# AUTO-GENERATED VIA CD FLAG - DO NOT MODIFY

[listener]
  [listener.0]
    ip = '127.0.0.1'
    port = 53

    [listener.0.policy]
      name = 'My Policy'

[network]
  [network.0]
    name = 'Network 0'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    type = 'doh3'
    endpoint = 'https://dns.controld.com/my_id'
    timeout = 5000
```

**Comment by yegors** [comment]
This is actually a known issue and is already fixed in a dev build. Will be part of the next update.

**Comment by kplttdaj1494** [comment]
Thanks for the info. Does cache reset if I restart service?

**Comment by yegors** [comment]
Yes, it does.

**Comment by yegors** [comment]
This is resolved in the latest release: https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.0
