### ISSUE TITLE
Queries from router itself

### ISSUE THREAD

**Issue by maghuro** [Control-D-Inc/ctrld#64]
Issue for improvement - Installed controld on router mode. All devices can be filtered, except for queries from the router itself. When excluding csv of activity log, all devices have a clientid except the router itself.

Problem - I want to create a global redirect rule for all devices, except for the router itself which I want to bypass it. It isn't possible right now.

Detailed problem - the rule I want to create is redirect all *.pool.ntp.org to routers lan ip. Except the router itself, which is needed to bypass to upstream A answer.

**Comment by yegors** [comment]
This will be addressed in future release, where the router itself will appear as a distinct "client".

**Comment by yegors** [comment]
This is resolved in the latest release: https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.0
