### ISSUE TITLE
OPnsense detection

### ISSUE THREAD

**Issue by donatom3** [Control-D-Inc/ctrld#65]
You support pfsense but not opnsense. As they're a fork wondering if it's easy to add support for opnsense for the router setup. 
I get the following error when trying to setup the opnsense router. Unsupported or incorrectly chosen router platform.
Hopefully you can boot one up in a vm to test it out. I tried setting up the toml file leaving the listener ip blank but it would not listen on all interfaces, and when I setup individual interfaces it did not list clients.

**Comment by alekslyse** [comment]
I totally agree!

**Comment by yegors** [comment]
This is resolved in the latest released: https://github.com/Control-D-Inc/ctrld/releases/tag/v1.3.0
