### ISSUE TITLE
ctrld only listens on localhost:domain but should be *:domain

### ISSUE THREAD

**Issue by jbryant705** [Control-D-Inc/ctrld#67]
I don't think I have any configuration wrong because I left everything as default. Ctrld runs as:

COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ctrld   2840 root    7u  IPv4  28673      0t0  TCP localhost:domain (LISTEN)
ctrld   2840 root   11u  IPv4  27158      0t0  UDP localhost:domain

I can't telnet to port 53 from my local machine with ctrld, and all requests fail when I set ctrld as my DNS server.

NextDNS cli and Pi-Hole both listen for any host:

COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nextdns 2974 root   11u  IPv6  23473      0t0  TCP *:domain (LISTEN)
nextdns 2974 root   12u  IPv6  23475      0t0  UDP *:domain

My configuration is default, and from my understanding the 0.0.0.0/0 should allow all sources:

[listener]
  [listener.0]
    ip = '127.0.0.1'
    port = 53

[network]
  [network.0]
    name = 'Network 0'
    cidrs = ['0.0.0.0/0']

[upstream]
  [upstream.0]
    name = 'Control D - Anti-Malware'
    type = 'doh'
    endpoint = 'https://freedns.controld.com/p1'
    bootstrap_ip = '76.76.2.11'
    timeout = 5000

  [upstream.1]
    name = 'Control D - No Ads'
    type = 'doq'
    endpoint = 'p2.freedns.controld.com'
    bootstrap_ip = '76.76.2.11'
    timeout = 3000

**Comment by yegors** [comment]
In your config, `listener.0` is configured to run on localhost, so it does exactly that. 

Change the IP to whatever you want (0.0.0.0), and restart the service. I'm not understanding what the problem is....

**Comment by jbryant705** [comment]
> In your config, `listener.0` is configured to run on localhost, so it does exactly that.
> 
> Change the IP to whatever you want (0.0.0.0), and restart the service. I'm not understanding what the problem is....

Thanks. That's likely the fix.
