### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lbouriez** [Control-D-Inc/ctrld#7]
Hello, it's unclear how to use it.
I have 2 houses, 2 routers, both only support legacy DNS. With NextDNS I was able to setup 2 ddns domain and everything was working perfectly.
With ControlD, I can just set 1 ddns url in My Ips, my other house is still plugged to NextDNS. How can this tool solve my issue ?

**Comment by yegors** [comment]
Hi,

Firstly, this is not the place to ask these questions. This is an issue/bug tracker for the ctrld utility. 

To answer your question: Currently, only a single DDNS hostname is supported, however this will change in early January and you can have multiple of them, each one associated with a specific device. 

A better solution is outlined here: https://kb.controld.com/troubleshooting/update-ip-automatically#automatic-ip-update-heartbeat-device

Finally, you can also use the utility from this Github repo, run it on your router, and this eliminates the need to use DDNS or do what was suggested in the above article. 

For all further questions you should contact support at help@controld.com
