### ISSUE TITLE
Failed to resolve query

### ISSUE THREAD

**Issue by littl3viking** [Control-D-Inc/ctrld#74]
Hello! I installed Ctrld on the NanoPi R4S (OpenWRT) using the command provided by the site:

```sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s ******* forced'```

But I am getting the following errors in the log:

```
Thu Aug 17 13:28:22 2023 daemon.info ctrld[22285]: [90mAug 17 16:28:22.000[0m [1m[31mERR[0m[0m [bc3438] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/*****************?dns=**************************************\": context deadline exceeded"[0m
Thu Aug 17 13:28:22 2023 daemon.info ctrld[22285]: [90mAug 17 16:28:22.000[0m [1m[31mERR[0m[0m [73f6f9] all upstreams failed
Thu Aug 17 13:28:43 2023 daemon.info ctrld[22285]: [90mAug 17 16:28:43.000[0m [31mWRN[0m error while probing mdns [36merror=[0m[31m"write udp4 0.0.0.0:5353->********:5353: sendto: operation not permitted"[0m
```

*Censored private information.

Can you help?
Thanks.

**Comment by cuonglm** [comment]
Could you provide full log of the installer?

**Comment by littl3viking** [comment]
> Could you provide full log of the installer?

How can I generate the complete log? Just running the default install command?

**Comment by yegors** [comment]
Full command output from `sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s ******* forced'`

**Comment by littl3viking** [comment]
```
root@NanoPiR4S:~# sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)" -s ****** forced'

        __         .__       .___
  _____/  |________|  |    __| _/
_/ ___\   __\_  __ \  |   / __ |
\  \___|  |  |  | \/  |__/ /_/ |
 \___  >__|  |__|  |____/\____ |
     \/       installer       \/

---------------------
|    System Info    |
---------------------
OS Type      : linux
OS Vendor    : openwrt
OS Version   : 23.05.0-rc2
Arch         : aarch64
CPU          : aarch64_generic
Free RAM     : 3790 MB / 3875 MB
---------------------
|  Install Details  |
---------------------
Resolver ID  : ******
Binary URL   : https://assets.controld.com/ctrld/linux/arm64/ctrld
Install Path : /usr/sbin
---------------------
 - Starting download
 - Making binary executable
 - Launching /usr/sbin/ctrld
---------------------
Aug 17 22:52:11.000 NTC Starting service
Aug 17 22:52:20.000 NTC Service started
```

**Comment by yegors** [comment]
The above suggests everything installed correctly and passed health tests. 

Can you provide output for this command after running the installer: `netstat -tupln`

**Comment by littl3viking** [comment]
Sure.

```
root@NanoPiR4S:~# netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1442/uhttpd
tcp        0      0 *****      0.0.0.0:*               LISTEN      9310/dnsmasq
tcp        0      0 192.168.1.1:7681        0.0.0.0:*               LISTEN      2657/ttyd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1442/uhttpd
tcp        0      0 192.168.1.1:53          0.0.0.0:*               LISTEN      9310/dnsmasq
tcp        0      0 192.168.1.1:22          0.0.0.0:*               LISTEN      2054/dropbear
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      9310/dnsmasq
tcp        0      0 :::443                  :::*                    LISTEN      1442/uhttpd
tcp        0      0 :::80                   :::*                    LISTEN      1442/uhttpd
tcp        0      0 f***** :::*                    LISTEN      9310/dnsmasq
tcp        0      0 ***** :::*                    LISTEN      9310/dnsmasq
tcp        0      0 :::5000                 :::*                    LISTEN      7654/miniupnpd
tcp        0      0 ::1:53                  :::*                    LISTEN      9310/dnsmasq
tcp        0      0 ***** :::*                    LISTEN      9310/dnsmasq
tcp        0      0 :::5354                 :::*                    LISTEN      1025/ctrld
tcp        0      0 *****  :::*                    LISTEN      9310/dnsmasq
tcp        0      0 *****    :::*                    LISTEN      9310/dnsmasq
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           7654/miniupnpd
udp        0      0 127.0.0.1:53            0.0.0.0:*                           9310/dnsmasq
udp        0      0 *****       0.0.0.0:*                           9310/dnsmasq
udp        0      0 192.168.1.1:53          0.0.0.0:*                           9310/dnsmasq
udp        0      0 0.0.0.0:67              0.0.0.0:*                           9310/dnsmasq
udp        0      0 0.0.0.0:49387           0.0.0.0:*                           9310/dnsmasq
udp        0      0 192.168.1.1:50134       0.0.0.0:*                           7654/miniupnpd
udp        0      0 192.168.1.1:5351        0.0.0.0:*                           7654/miniupnpd
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1025/ctrld
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1025/ctrld
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1025/ctrld
udp        0      0 *****                :::*                                7654/miniupnpd
udp        0      0 *****                :::*                                9310/dnsmasq
udp        0      0 ***** :::*                                9310/dnsmasq
udp        0      0 ***** :::*                                9310/dnsmasq
udp        0      0 ***** :::*                                9310/dnsmasq
udp        0      0 *****    :::*                                9310/dnsmasq
udp        0      0 ***** :::*                                9310/dnsmasq
udp        0      0 :::*****                  :::*                                6494/odhcp6c
udp        0      0 :::*****                  :::*                                4190/odhcpd
udp        0      0 :::*****                :::*                                7654/miniupnpd
udp        0      0 :::*****                 :::*                                7654/miniupnpd
udp        0      0 :::*****                :::*                                1025/ctrld
```

**Comment by yegors** [comment]
Everything seems fine here. At this point, Im not seeing nay issues here. Those errors you reported, do they happen all the time, and does DNS actually work?

**Comment by littl3viking** [comment]
Yes, these errors happen all the time, on average every 15 minutes.
DNS is working correctly. I did all the tests that exist in the documentation on the site.
I was using OpenWrt 22.03, now I installed version 23.05 and the same error persists.
Is there any other test I can do?

**Comment by yegors** [comment]
You said DNS worked, so other than seeing these errors, what is the actual problem here?

"https-dns-proxy" package could just be hiding the same types of errors, and you simply don't know they happen. 

Basically, is it causing any actual issues for you?

**Comment by yegors** [comment]
@littl3viking Please try a new dev build. 

```
sh -c 'sh -c "$(curl -sSL https://api.controld.com/dl)"'
```

**Comment by littl3viking** [comment]
> You said DNS worked, so other than seeing these errors, what is the actual problem here?
> 
> "https-dns-proxy" package could just be hiding the same types of errors, and you simply don't know they happen.
> 
> Basically, is it causing any actual issues for you?

No issues with internet, only errors on log.

> @littl3viking Please try a new dev build.
> 
> ```
> sh -c 'sh -c "$(curl -sSL https://api.controld.dev/dl)"'
> ```

I just tested and still the same error in the log.

**Comment by yegors** [comment]
But other than the errors in the log, are there any actual noticeable problems?

**Comment by scumball** [comment]
This looks like the same error as I have been having with my glinet mt2500. It doesn't seem to be causing issues, I have been speaking to Yegor in support over email

Tue Aug 29 07:14:55 2023 daemon.info ctrld[20548]: [90mAug 29 06:14:55.000[0m [1m[31mERR[0m[0m [266449] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/***?dns=aDUBAAABAAAAAAAAAmZ3B2dsLWluZXQDY29tAAABAAE\": stream 1276 canceled by local with error code 268"[0m
Tue Aug 29 07:14:57 2023 daemon.info ctrld[20548]: [90mAug 29 06:14:57.000[0m [1m[31mERR[0m[0m [072d06] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/***?dns=4mcBAAABAAAAAAAAAmZ3B2dsLWluZXQDY29tAAABAAE\": stream 4 canceled by local with error code 268"[0m
Tue Aug 29 07:14:57 2023 daemon.info ctrld[20548]: [90mAug 29 06:14:57.000[0m [1m[31mERR[0m[0m [741ab2] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/***?dns=5WgBAAABAAAAAAAAAmZ3B2dsLWluZXQDY29tAAAcAAE\": stream 0 canceled by local with error code 268"[0m

**Comment by planetf1** [comment]
Getting similar errors here too.

In my case I have 2 pi's on the local net, both running latest ctrld and configured with a single upstream (.net doh). The same error also occurs when run on macOS at varying intervals during the day.

Also noticed that I occasionally see ping packets being dropped to the current dns (dns.controld.net) - I *do not* see this to other major nameservers. This may align with the 'connection reset by peer'? if server having a glitch.

**Comment by planetf1** [comment]
Looking closely at my logs, I had multiple local ctrld instances report the issue at the same time. Just over a 1-2s period, so a very brief blip. Again a connection reset, failures to resolve, and all upstreams failed. No observed blips in other traffic. Using the .net resolvers it looked as if there was a blip. I presume the actual outage may have been 6-7s given a default 5s timeout on queries.

Not sure if this is specific to anycast, or the new anycast when routing changes.

In this regard, for ctrld itself this may be expected behaviour.

However I did check my 'dnsleaktest' an hour ago, plus just now when I noticed the issue. My location had changed (france->germany) so this kinda holds together, and moves the question to that network and mitigation strategies? One option might be an additional upstream - albeit at the risk of skipping ad etc checks (maybe quad9 a good option). caching, stale result serving, cache size may be others that can be done locally.

**Comment by yegors** [comment]
Are you using DOH3 or DOQ by any chance?

**Comment by scumball** [comment]
Yes, first upstream resolver is DOH3

thanks

-------- Original Message --------

**Comment by yegors** [comment]
Can you switch it do standard DOH, and see if the same issue reoccurs?

**Comment by scumball** [comment]
Switched to DOH

```
Mon Sep  4 19:02:48 2023 daemon.info ctrld[2926]: [90mSep  4 18:02:48.000[0m [1m[31mERR[0m[0m [c1515e] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/xxx?dns=bzQBAAABAAAAAAAABWFsaXZlBmdpdGh1YgNjb20AAAEAAQ\": context deadline exceeded"[0m
Mon Sep  4 19:02:49 2023 daemon.info ctrld[2926]: [90mSep  4 18:02:49.000[0m [1m[31mERR[0m[0m [73be25] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/xxx?dns=fvkBAAABAAAAAAAABWFsaXZlBmdpdGh1YgNjb20AAAEAAQ\": context deadline exceeded"[0m
```

**Comment by yegors** [comment]
Seems like random timeouts are being triggered. Can you provide an MTR/traceroute to dns.controld.com AND dns.controld.net

**Comment by scumball** [comment]
GL-MT2500 (192.168.0.1) -> dns.controld.net            2023-09-04T19:23:59+0100
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                       Packets               Pings
 Host                                Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 192.168.0.254                     0.0%   381    0.6   0.6   0.5   2.9   0.3
 2. (waiting for reply)
 3. 172.17.69.33                     46.8%   381    9.2  12.7   7.2 184.6  16.1
 4. (waiting for reply)
 5. 172.17.220.10                    19.4%   381   12.9  14.4   7.3 184.4  22.7
 6. 172.17.164.165                   60.3%   381    9.5  15.7   8.0 206.4  25.4
 7. (waiting for reply)
 8. 172.17.17.150                    47.1%   380   11.0  13.3   7.8 135.6  11.1
 9. ip4.gtt.net                      92.6%   380   13.9  19.8  10.2 178.3  31.1
10. et-0-0-71.cr11-lon1.ip4.gtt.net   0.0%   380   17.0  19.3   9.9 180.8  19.9
11. (waiting for reply)
12. 172.99.23.22                      0.0%   380   16.6  21.8  14.7 210.8  21.4

```

**Comment by yegors** [comment]
That looks fairly reasonable, shouldn't cause any issues as far as timeouts are concerned. Will discuss this internally.

**Comment by scumball** [comment]
Still seeing regular issues
Lost all connection yesterday, so will have to uninstall ctrld while so unstable for me
`Sat Sep 23 08:08:33 2023 daemon.info ctrld[2892]: [90mSep 23 07:08:33.000[0m [1m[31mERR[0m[0m [636218] all upstreams failed
Sat Sep 23 08:08:33 2023 daemon.notice procd: /etc/rc.d/S99webdav_ser: start app = /usr/bin/webdav_ser
Sat Sep 23 08:08:33 2023 daemon.info procd: - init complete -
Sat Sep 23 08:08:33 2023 daemon.info ctrld[2892]: [90mSep 23 07:08:33.000[0m [1m[31mERR[0m[0m [2cce03] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/130flvl8erw?dns=244BAAABAAAAAAABC3RoZ2ZibDZ0bXFmBnZlcmlmeQhjb250cm9sZANjb20AAAEAAQAAKQIAAAAAAAAW_ekABtQ9fpy5XwAIAAgAASAAwKgCEw\": dial tcp 76.76.2.22:443: i/o timeout"[0m
Sat Sep 23 08:08:33 2023 daemon.info ctrld[2892]: [90mSep 23 07:08:33.000[0m [1m[31mERR[0m[0m [2cce03] all upstreams failed
Sat Sep 23 08:08:33 2023 user.notice route_policy: default_policy=0 mac_list=14:DA:E9:93:E0:5A A8:51:AB:96:E7:72 00:04:4B:4B:6E:FB 90:DD:5D:AF:21:96 `

**Comment by scumball** [comment]
lost all connections again - having to uninstall now as family not happy

**Comment by yegors** [comment]
This appears to be a networking issue. At the time of the issue, can you even reach dns.controld.com? ping or load in the browser?

We need a little more details here / external troubleshooting.

**Comment by scumball** [comment]
When it happens I lose all internet access on the devices using the router, my devices with separate configs continue to work.

I think it may be due to the glinet router which seems to route all DNS queries over VPN if one is enabled, even for clients not set to use the VPN.

I have disabled the VPN and things seem more stable. Will keep an eye on it...

**Comment by yegors** [comment]
Yes, please eliminate all external variables and see if there are any issues then, otherwise these reports are not actionable.

**Comment by scumball** [comment]
the VPN does seem to be the issue in general - as the amount of errors has gone down hugely - but still getting random occurrences
`Fri Sep 29 02:15:19 2023 daemon.info ctrld[17514]: [90mSep 29 01:15:19.000[0m [1m[31mERR[0m[0m [f03449] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/****?dns=zIcBAAABAAAAAAABBGVwZGcDZXBjBm1uYzAyMAZtY2MyMzQDcHViCzNncHBuZXR3b3JrA29yZwAAAQABAAApAgAAAAAAAAr96QAGpFBG3-4d\": context deadline exceeded"[0m
Fri Sep 29 02:15:19 2023 daemon.info ctrld[17514]: [90mSep 29 01:15:19.000[0m [1m[31mERR[0m[0m [f03449] all upstreams failed
xxx
Fri Sep 29 03:15:20 2023 daemon.info ctrld[17514]: [90mSep 29 02:15:20.000[0m [1m[31mERR[0m[0m [739445] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/Fri Sep 29 03:15:20 2023 daemon.info ctrld[17514]: [90mSep 29 02:15:20.000[0m [1m[31mERR[0m[0m [739445] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/n9kfffgpfo?dns=KhIBAAABAAAAAAABBGVwZGcDZXBjBm1uYzAyMAZtY2MyMzQDcHViCzNncHBuZXR3b3JrA29yZwAAAQABAAApAgAAAAAAAAr96QAGpFBG3-4d\": context deadline exceeded"[0m
Fri Sep 29 03:15:20 2023 daemon.info ctrld[17514]: [90mSep 29 02:15:20.000[0m [1m[31mERR[0m[0m [739445] all upstreams failed?dns=KhIBAAABAAAAAAABBGVwZGcDZXBjBm1uYzAyMAZtY2MyMzQDcHViCzNncHBuZXR3b3JrA29yZwAAAQABAAApAgAAAAAAAAr96QAGpFBG3-4d\": context deadline exceeded"[0m
Fri Sep 29 03:15:20 2023 daemon.info ctrld[17514]: [90mSep 29 02:15:20.000[0m [1m[31mERR[0m[0m [739445] all upstreams failed

`

**Comment by yegors** [comment]
That may suggest your Internet drops out for a bit, which is what this error suggests. Does this cause any actual noticeable problems?

**Comment by scumball** [comment]
Without the VPN the errors are single but still happening
```
Thu Oct  5 07:55:49 2023 daemon.info ctrld[17514]: [90mOct  5 06:55:49.000[0m [1m[31mERR[0m[0m [f534f9] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/****?dns=xGEBAAABAAAAAAABBGVwZGcDZXBjBm1uYzAyMAZtY2MyMzQDcHViCzNncHBuZXR3b3JrA29yZwAAAQABAAApAgAAAAAAAAr96QAG9Nvjwk60\": context deadline exceeded"[0m
Thu Oct  5 16:18:18 2023 daemon.info ctrld[17514]: [90mOct  5 15:18:18.000[0m [1m[31mERR[0m[0m [992892] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/****?dns=3I0BAAABAAAAAAABBGVwZGcDZXBjBm1uYzAyMAZtY2MyMzQDcHViCzNncHBuZXR3b3JrA29yZwAAAQABAAApAgAAAAAAAAr96QAGLmX7tu6q\": context deadline exceeded"[0m
Thu Oct  5 18:03:27 2023 daemon.info ctrld[17514]: [90mOct  5 17:03:27.000[0m [1m[31mERR[0m[0m [e8a6cc] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/****?dns=9rABAAABAAAAAAABBGVwZGcDZXBjBm1uYzAyMAZtY2MyMzQDcHViCzNncHBuZXR3b3JrA29yZwAAAQABAAApAgAAAAAAAAr96QAG9Nvjwk60\": context deadline exceeded"[0m
```

**Comment by yegors** [comment]
@scumball What DNS Host are you using? https://controld.com/status

**Comment by scumball** [comment]
lhr-h03

**Comment by yegors** [comment]
If the status page says you're not using Control D, that means your browser has DOH configured, and not using your router at all. 
https://docs.controld.com/docs/browser-not-using-os-dns

**Comment by scumball** [comment]
Sorry I just checked and my work VPN was connected - but still the router is using lhr-h03, and the log still showed the disconnect

**Comment by scumball** [comment]
Still getting this error all the time - never happens when ctrld uninstalled and using Adguard for example

`Thu Oct 19 19:37:32 2023 daemon.info ctrld[24585]: [90mOct 19 18:37:32.000[0m [1m[31mERR[0m[0m [e28859] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/xxx?dns=DioBAAABAAAAAAABA2l4bgNsb24CdWsJc3BlZWR0ZXN0BmZhZWxpeANuZXQAAAEAAQAAKQIAAAAAAAAW_ekABqhRq4nvLQAIAAgAASAAwKgCXw\": context deadline exceeded"[0m
Thu Oct 19 19:37:32 2023 daemon.info ctrld[24585]: [90mOct 19 18:37:32.000[0m [1m[31mERR[0m[0m [e28859] all [upstream.0] endpoints failed
Thu Oct 19 19:37:33 2023 daemon.info ctrld[24585]: [90mOct 19 18:37:33.000[0m [1m[31mERR[0m[0m [3e3a6d] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/xxx?dns=1AABAAABAAAAAAABA2l4bgNsb24CdWsJc3BlZWR0ZXN0BmZhZWxpeANuZXQAAAEAAQAAKQIAAAAAAAAW_ekABqhRq4nvLQAIAAgAASAAwKgCXw\": context deadline exceeded"[0m
Thu Oct 19 19:37:33 2023 daemon.info ctrld[24585]: [90mOct 19 18:37:33.000[0m [1m[31mERR[0m[0m [3e3a6d] all [upstream.0] endpoints failed
Thu Oct 19 19:37:35 2023 daemon.info ctrld[24585]: [90mOct 19 18:37:35.000[0m [1m[31mERR[0m[0m [d175e3] failed to resolve query [36merror=[0m[31m"could not perform request: Get \"https://dns.controld.com/xxx?dns=Bb8BAAABAAAAAAABA2l4bgNsb24CdWsJc3BlZWR0ZXN0BmZhZWxpeANuZXQAAAEAAQAAKQIAAAAAAAAW_ekABqhRq4nvLQAIAAgAASAAwKgCXw\": context deadline exceeded"[0m
Thu Oct 19 19:37:35 2023 daemon.info ctrld[24585]: [90mOct 19 18:37:35.000[0m [1m[31mERR[0m[0m [d175e3] all [upstream.0] endpoints failed`

**Comment by scumball** [comment]
I reset my Glinet Brume 2 and reinstalled ctrld utility with my new fibre connection
When I install ctrld I see this - any issue?
`Sat Oct 28 10:00:57 2023 daemon.info ctrld[2972]: [90mOct 28 09:00:57.000[0m [31mWRN[0m listener.0 could not listen on address: 0.0.0.0:53, trying: 0.0.0.0:53
Sat Oct 28 10:00:57 2023 daemon.info ctrld[2972]: [90mOct 28 09:00:57.000[0m [31mWRN[0m listener.0 could not listen on address: 0.0.0.0:53, trying localhost: 127.0.0.1:53
Sat Oct 28 10:00:57 2023 daemon.info ctrld[2972]: [90mOct 28 09:00:57.000[0m [31mWRN[0m listener.0 could not listen on address: 127.0.0.1:53, trying current ip with port 5354
Sat Oct 28 10:00:57 2023 daemon.info ctrld[2972]: [90mOct 28 09:00:57.000[0m [31mWRN[0m no default route IP found`

**Comment by scumball** [comment]
I've been running AdGuard Home with my personal DNS resolver as the upstream on my Brume 2 since without a single issue

So presume it's not the resolver that has problems but the ctrld install itself for me....

I don't get nice logs or analytics this way, but a stable connection and the blocks/redirects that I need so it will do

**Comment by yegors** [comment]
@littl3viking  Please try a new dev build.

```
sh -c 'sh -c "$(curl -sSL https://api.controld.dev/dl)"'
```

Can you reproduce the issue?

**Comment by yegors** [comment]
Or try the latest v1.3.3 release.
