### ISSUE TITLE
Asuswrt-Merlin - ctrld stops working after IP address release

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#76]
ctrld on Asuswrt-Merlin stops working sometimes.

My ISP assigns a dynamic IP address via DHCP using PPPoE credentials. This IP address is renewed every 24 hours.
Upon the release of the IP address, a new one will be assigned by the ISP, but ctrld will not resolve DNS queries after this IP address renewal.

I've tried restarting the router to get DNS service back, but it doesn't work.

The only way to restore DNS service is to run the ctrld installer again.

Meanwhile, I've set the router to automatically reboot (and manually obtain a new IP address) every day at 4am.

**Comment by yegors** [comment]
We've seen such reports before, but could never reproduce them on our test devices. 

Can you provide logs from the router when this occurs? System logs, output of `top`, logs from the ctrld service if you have that enabled. 

Did any network events occur, like outages or modem reboots?

**Comment by pmcarrion** [comment]
I'll disable the automatic reboot to force this issue and get the log.

How do I get the `top` logs you mention? ctrld is enabled on my router.
There's no nothing related to ctrld on System Log > General Log.

> Did any network events occur, like outages or modem reboots?

Expired (WAN) DHCP lease.

**Comment by pmcarrion** [comment]
The issue showed up again today after a forced reboot.
I just emailed you the log.

**Comment by yegors** [comment]
@pmcarrion Please try the latest v1.3.2 version and see if you can reproduce this issue.

**Comment by yegors** [comment]
Or v1.3.3
