### ISSUE TITLE
Logging options

### ISSUE THREAD

**Issue by robdejonge** [Control-D-Inc/ctrld#79]
A random pick from the logs ... 
```
DBG [5e8d67] 10.66.11.14:51239 -> listener.0: [::]:53: received query: A www.ietf.org
INF [5e8d67] no explicit policy matched, using default routing -> [upstream.0]
DBG [5e8d67] including client info with the request
DBG [5e8d67] sending query to upstream.0: Control-D
DBG [5e8d67] sending request header header={"Accept":["application/dns-message"],"Content-Type":["application/dns-message"],"X-Cd-Host":["shikuwasa"],"X-Cd-Ip":["10.66.11.14"],"X-Cd-Mac":["64:4b:f0:01:10:5c"]}
DBG [5e8d67] received response of 73 bytes in 34.089986ms
```

I would suggest : 
```
INFO: 10.66.11.14:51239 (HOSTNAME) -> listener.0: [::]:53: received query: A www.ietf.org
DEBUG: no explicit policy matched, using default routing -> [upstream.0]
DEBUG: including client info with the request (++what client info???) 
DEBUG: sending query to upstream.0: Control-D
DEBUG: sending request header header={"Accept":["application/dns-message"],"Content-Type":["application/dns-message"],"X-Cd-Host":["shikuwasa"],"X-Cd-Ip":["10.66.11.14"],"X-Cd-Mac":["64:4b:f0:01:10:5c"]}
DEBUG: received response of 73 bytes in 34.089986ms 
INFO upstream.0 -> hostname replied: (++some information on the reply sent) 

```

To save you the comparison, I'm suggesting: 

- the 'received query' line becomes INFO level and includes the hostname maybe?
- the 'including client info' line gets added detail, which 
- the 'upstream decision line' becomes DEBUG level
- a 'replied' line (INFO) gets added which signals the upstream server used, hostname or IP address of recipient (same format as the received query line) plus the response received

Why?

- some small details added, making DEBUG level more useful 
- showing only INFO level becomes a sensible setting for normal operation that does not overwhelm

**Comment by yegors** [comment]
That's a decent idea.

**Comment by cuonglm** [comment]
@robdejonge What does `hostname` mean in:

```
INFO upstream.0 -> hostname replied: (++some information on the reply sent) 
````

Also, I think it's better to switch the order of last 2 lines to:

```
INFO: 10.66.11.14:51239 (HOSTNAME) -> listener.0: [::]:53: received query: A www.ietf.org
DEBUG: no explicit policy matched, using default routing -> [upstream.0]
DEBUG: including client info with the request (++what client info???) 
DEBUG: sending query to upstream.0: Control-D
DEBUG: sending request header header={"Accept":["application/dns-message"],"Content-Type":["application/dns-message"],"X-Cd-Host":["shikuwasa"],"X-Cd-Ip":["10.66.11.14"],"X-Cd-Mac":["64:4b:f0:01:10:5c"]}
INFO upstream.0 -> hostname replied: (++some information on the reply sent) 
DEBUG: received response of 73 bytes in 34.089986ms 
```

Because the `received response ...` line count the whole process of proxying the request to upstreams until ctrld get back a reply, not just couting for succeded one.

**Comment by cuonglm** [comment]
@robdejonge I assume this is the hostname of the machine that run ctrld?

If yes, here's an example (with time field removed):

Info mode:

```
INF [0ff7d3] 192.168.50.208:50480 (cuonglm-ThinkPad-X1-Carbon-Gen-9) -> listener.0: 127.0.0.1:53: received query: A popads.net
INF [0ff7d3] upstream.0 -> cuonglm-ThinkPad-X1-Carbon-Gen-9 replied: NOERROR
```

Debug mode:

```
INF [a3485b] 192.168.50.208:55795 (cuonglm-ThinkPad-X1-Carbon-Gen-9) -> listener.0: 127.0.0.1:53: received query: A popads.net
DBG [a3485b] no explicit policy matched, using default routing -> [upstream.0]
DBG [a3485b] including client info with the request
DBG [a3485b] sending query to upstream.0: 
DBG [a3485b] sending request header header={"Accept":["application/dns-message"],"Content-Type":["application/dns-message"],"X-Cd-Host":["cuonglm-ThinkPad-X1-Carbon-Gen-9"],"X-Cd-Ip":["192.168.50.208"],"X-Cd-Mac":["REDUCTED"],"X-Cd-Os":["3-1-Ubuntu 22.04.3 LTS"]}
INF [a3485b] upstream.0 -> cuonglm-ThinkPad-X1-Carbon-Gen-9 replied: NOERROR
DBG [a3485b] received response of 44 bytes in 68.481009ms
```

Sounds good to you?

**Comment by robdejonge** [comment]
@cuonglm Yes, that is what I meant with hostname indeed. And indeed, I think the info mode would be much more usable by showing only the query and reply and moving all the other stuff to the debug mode .Thanks for looking at this. 

I may be pushing it a little bit here, but is it worth considering trying to align the two info lined so that the query and reply show up in the same horizontal location of the line?

```
INF [0ff7d3] QUERY: 192.168.50.208:50480 (cuonglm-ThinkPad-X1-Carbon-Gen-9) -> listener.0: A popads.net
INF [0ff7d3] REPLY: upstream.0 -> 192.168.50.208:50480 (cuonglm-ThinkPad-X1-Carbon-Gen-9): NOERROR
```

This would mean removing the IP address of listener.0 from the line (maybe add it in a debug line?) but my gut feel says that is in the config file and so needn't be transmitted in every log entry of a query. It may make monitoring the log file as a human a bit easier to process? Just a thought.

**Comment by cuonglm** [comment]
@robdejonge That sounds reasonable:

```
Dec 18 16:54:18.882 INF [11f73c] QUERY: 192.168.50.208:42109 (cuonglm-ThinkPad-X1-Carbon-Gen-9) -> listener.0: A popads.net
Dec 18 16:54:18.939 INF [11f73c] REPLY: upstream.0 -> 192.168.50.208:42109 (cuonglm-ThinkPad-X1-Carbon-Gen-9): NOERROR
```

Though note that `cuonglm-ThinkPad-X1-Carbon-Gen-9` is the hostname of the client which sends request to `ctrld`, not the machine that `ctrld` is running.

**Comment by robdejonge** [comment]
@cuonglm That is actually what I meant ...apologies for my mistake a few days ago, I meant to say that the hostname was that of the client. Right now it only shows the IP address the query originated from, but having the hostname in there makes monitoring the log a lot easier. 

As an aside ... the little slug between brackets, is an id unique to each query, right?

**Comment by cuonglm** [comment]
> As an aside ... the little slug between brackets, is an id unique to each query, right?

Yes.

v1.3.3 will adopt new changes, see #113

**Comment by robdejonge** [comment]
Fantastic. Thanks very much!
