### ISSUE TITLE
Docker format error

### ISSUE THREAD

**Issue by cohortcw179** [Control-D-Inc/ctrld#81]
I compiled my own Docker to work on my Mirotik for the earlier versions of ctrld utility. I could not run versions from 1.20 since the inclusion of upx compression as Mikrotik does not have the necessary libraries required in its container. Now it doesn't work even after I compiled my own container with the latest source .e.g. 1.30. Any way to know what are the changes done from 1.20 to 1.30? 

Symptoms: Container starts and stop almost within 1sec.

I tried pulling the image from docker links but to no avail. It reported a execv formt error message.

P.S. To keep containers in Mikrotik small, only the key libraries are included during the compilation. Not sure what libraries are required to make the latest version run.

**Comment by cuonglm** [comment]
What's exactly the error you got?

What's architecture of your router?

**Comment by cohortcw** [comment]
Got mixed up by the error msgs. execv format error was actually from my own go build. I did a build for arm64 as your release uses upx compression which requires the necessary dependencies in order to work in Mikrotik routers.

On a seperate note, the latest build requires to write to the config.toml which the container does not have the right permissions. Can I know what is the ctrld utility trying to write to the config.toml on first start? The previous 1.21 build works (self build binary) only treats config.toml as a read-only file.

**Comment by cuonglm** [comment]
@cohortcw Here's it: https://github.com/Control-D-Inc/ctrld/issues/75#issuecomment-1696692865

**Comment by JManch** [comment]
@cohortcw Do you mind sharing what you did to make it work on Mikrotik? I'm currently getting the same issue where the container instantly stops after starting it.

**Comment by cohortcw** [comment]
@JManch , Sure. I haven't got time to do a detail writeup but below are some brief steps on how I managed to get it up and running in my CCR2004 which only have 128MB. (still have 64% free space after setting up ctrld utility)

1. Clone ctrld github site into my Ubuntu 20.04 server.
2. Recompile ctrld utility using the following code:
>> env GOOS=linux GOARCH=arm64 go build -a -gcflags=all"-l -B" -ldflags="-w -s" ./cmd/ctrld
3. The I compile into Docker container with only 3 files in my directory, a. ctrld utility, b. Dockerfile c. custom config file
4. I placed my custom config file in a subfolder, named "config".
5. run the folllowing in docker build
> docker buildx build --no-cache --platform=linux/arm64 -t ctrld130:debian .
> docker save ctrld130 > ctrld130_arm64.tar
6. Export ctrld130_arm64.tar to your PC/Mac and you can then import into your Mikrotik.
7. Create subfolder "config" in your Mikrotik and place your custom config into this folder. 
8. You should then be able to run ctrld utility in your Mikrotik.
