### ISSUE TITLE
AAAA queries sent to a 'v4' upstream 

### ISSUE THREAD

**Issue by robdejonge** [Control-D-Inc/ctrld#85]
My ctrld is configured with one upstream provider only, pointing at Control D. However, this is set as a `v4` upstream. According to the documentation, this means no v6 queries should ever be sent there. However, I am seeing AAAA queries in the Activity Log on the Control D dashboard. That seems a bug.

**Comment by cuonglm** [comment]
This is documented here: https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#ip_stack

**Comment by robdejonge** [comment]
Pardon my ignorance, but thats what I mean by "set as v4" ... `ip_stack = v4` ... so I would expect there to only be A record queries going to that destination.

**Comment by cuonglm** [comment]
> Pardon my ignorance, but thats what I mean by "set as v4" ... `ip_stack = v4` ... so I would expect there to only be A record queries going to that destination.

Nope, `ip_stack = v4` means `ctrld` will connect to upstream server using ipv4 only, regardless of DNS record type.

**Comment by robdejonge** [comment]
Ah, ok. Understood. There is no way to avoid AAAA queries from being forwarded?

**Comment by cuonglm** [comment]
> Ah, ok. Understood. There is no way to avoid AAAA queries from being forwarded?

At this moment, no.

**Comment by robdejonge** [comment]
Ok, understood.
