### ISSUE TITLE
PTR queries do not adhere to policy

### ISSUE THREAD

**Issue by robdejonge** [Control-D-Inc/ctrld#86]
When I add a policy for `*.*.168.192.in-addr.arpa` to be forwarded to an internal server for resolution, this does not happen. These PTR queries seem to always go to the default route. Do policies only apply to A / AAAA queries? Is there a way to adjust this?

**Comment by cuonglm** [comment]
Could you provide what exactly rules you set in your config file?

**Comment by robdejonge** [comment]
Sure! Thanks for your help ... 
```
    [listener.0.policy]
      name = 'Local'
      rules = [
        {        '*.lan' = ['upstream.1']},
        {        '*.*.168.192.in-addr.arpa' = ['upstream.1']}
      ]
```

**Comment by cuonglm** [comment]
> Sure! Thanks for your help ...
> 
> ```
> [listener.0.policy]
>   name = 'Local'
>   rules = [
>     {        '*.lan' = ['upstream.1']},
>     {        '*.*.168.192.in-addr.arpa' = ['upstream.1']}
>   ]
> ```

The rules looks ok.

Could you check ctrld log to see what exactly query and policy matched?

**Comment by robdejonge** [comment]
Query 
```
% dig -x 192.168.1.4 @192.168.1.3

; <<>> DiG 9.10.6 <<>> -x 192.168.1.4 @192.168.1.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35225
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;4.1.168.192.in-addr.arpa.	IN	PTR

;; Query time: 39 msec
;; SERVER: 192.168.1.3#53(192.168.1.3)
;; WHEN: Wed Sep 06 15:53:47 +07 2023
;; MSG SIZE  rcvd: 41
```
Log file 
```
Sep  6 08:53:47.000 DBG [1ed7e8] 192.168.1.14:55598 -> listener.0: [::]:53: received query: PTR 4.1.168.192.in-addr.arpa
Sep  6 08:53:47.000 INF [1ed7e8] no explicit policy matched, using default routing -> [upstream.0]
Sep  6 08:53:47.000 DBG [1ed7e8] including client info with the request
Sep  6 08:53:47.000 DBG [1ed7e8] sending query to upstream.0: Control-D
Sep  6 08:53:47.000 DBG [1ed7e8] sending request header header={--cut--}
Sep  6 08:53:47.000 DBG [1ed7e8] received response of 41 bytes in 38.739979ms
```

**Comment by robdejonge** [comment]
I guess I should have tried that, as it's quite the obvious solution. 
That works!

Thanks very much for your help.

**Comment by cuonglm** [comment]
@robdejonge It's my fault, forgot that ctrld only supports [wildcard domain](https://en.wikipedia.org/wiki/Wildcard_DNS_record): https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#rules
