### ISSUE TITLE
cannot git pull or push when github redirected

### ISSUE THREAD

**Issue by lzumot** [Control-D-Inc/ctrld#87]
simple, redirect github in services to any location, attemnpt to pull or push private repo using ssh keys fails
connection closed by remote host kex exchange identification. 
restarting ssh service, checking firewall locally, doing ssh -vvv git@github shows the same output with no further explanation.
remoivign redirect and setting ot bypass things work fine.

**Comment by yegors** [comment]
This issue has nothing to do with ctrld. You should contact Control D support.
