### ISSUE TITLE
Feature request - ctrld “devices” feature for apps/processes

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#89]
Following up on this feedback [post](https://feedback.controld.com/posts/2051/feature-request-ctrld-clients-for-computers).

Please enable an option to assign apps/processes to other profiles on computers where ctrld is installed.

Here’s an example:
1) Computer runs ctrld - Assigned to Profile 1
2) Email client on that computer also uses Profile 1 as expected, but I want it to use Profile 2.

**Comment by yegors** [comment]
What would be the use case for this?

**Comment by pmcarrion** [comment]
Enable services, filters, or Block/Redirect/Bypass custom rules for each app.

My computer profile has the Hagezi Pro filter enabled. I also bypass certain domains that are broken by this filter via a custom rule. No service is enabled to avoid latency increases.

I want my email client to use a certain service without having to enable it systemwide in the computer profile.

**Comment by yegors** [comment]
Your email client likely only makes connections to SMTP and IMAP servers, I'm not sure I see the point here....

**Comment by yegors** [comment]
I don't think we'll do this, as this is outside the scope and will make ctrld a lot more complicated and we want to keep it simple.
