### ISSUE TITLE
macos - problems connecting reliably with ctrld via ipv6

### ISSUE THREAD

**Issue by planetf1** [Control-D-Inc/ctrld#91]
I have a controlD account,  this is being used on a number of (apple) mobile devices via profiles (typically doT, though doH also setup and working). Additionally my home router is using control-D via doT, and it typically does report if there are ongoing issues (for example in recent weeks) - which it hasn't

macOS is Sonama RC (23A339)

ctrld below is from a download just now:
```
sudo sh -c 'sh -c "$(curl -sL https://api.controld.dev/dl)"'
```
but also appeared to be the same yesterday using the github version.

When using doh, the errors are typically some combination of 
```
{"level":"error","error":"could not perform request: Get \"https://dns.controld.net/idididid?dns=BLAH\": dial tcp [2606:1a40::22]:443: connect: connection reset by peer","time":"2023-09-15T07:58:10+01:00","time":"2023-09-15T07:58:10+01:00","message":"[bf4421] failed to resolve query"}
{"level":"error","error":"read tcp6 [me:me:me]:64098->[2606:1a40::22]:853: read: connection reset by peer","time":"2023-09-15T07:58:10+01:00","time":"2023-09-15T07:58:10+01:00","message":"[c570c0] failed to resolve query"}
```

with less frequent:
```
{"level":"error","error":"write tcp6 [me:me:me]:64001->[2606:1a40::22]:853: write: broken pipe","time":"2023-09-15T07:58:10+01:00","time":"2023-09-15T07:58:10+01:00","message":"[cb17f3] failed to resolve query"}
{"level":"error","time":"2023-09-15T07:58:10+01:00","time":"2023-09-15T07:58:10+01:00","message":"[cb17f3] all upstreams failed"}
``` 

The second upstream (after 5s) is quad9 doh

When using DoT the errors have less info ie

{"level":"error","error":"read tcp6 [me:me:me]:65021->[2606:1a40::22]:853: read: connection reset by peer","time":"2023-09-15T08:08:09+01:00","time":"2023-09-15T08:08:09+01:00","message":"[89cf9f] failed to resolve query"}
{"level":"error","error":"write tcp6 [me:me:me]:65060->[2606:1a40::22]:853: write: broken pipe","time":"2023-09-15T08:08:32+01:00","time":"2023-09-15T08:08:32+01:00","time":"2023-09-15T08:08:32+01:00","message":"[67da8a] failed to resolve query"}

The ctrld server does seem able to do some resolution ok. Perhaps this is due to the additional upstream - and the fact that in most cases 'all upstreams failed' does not occur. 

A simple configuration with no fallbacks/network definitions fails in the same way - but with many more 'all upstreams failed', unsurprisingly. It does manage to resolve some names however, so it obviously isn't every request that fails

I did notice that the above errors are all ipv6

I then added `ip_stack='v4'` into the upstream and resolution worked without error

I then used `'ip_stack='v6'` instead and got loads of errors

Thus, my conclusion is that ctrld is failing on macos with ipv6

Whether this affects other devices it's harder to say. My router has a mind of it's own deciding which to use. Currently it's reporting it's using 76.76.2.22 ie ipv4 doT encrypted, and similarly the iOS devices are just using a profile .

**Comment by planetf1** [comment]
Update - tried with quad9 pinned to ipv6. Seems to work. so could be service issue (let me know if I should move over to that reporting channel - when opened I felt it was an appllication issue)

**Comment by yegors** [comment]
Are you able to ping 2606:1a40::22 from this machine?

**Comment by planetf1** [comment]
@yegors 

Connectivity seems fine

```
➜  ~ ping6 2606:1a40::22
PING6(56=40+8+8 bytes) BLAHBLAHBLAH --> 2606:1a40::22
16 bytes from 2606:1a40::22, icmp_seq=0 hlim=54 time=7.116 ms
16 bytes from 2606:1a40::22, icmp_seq=1 hlim=54 time=6.138 ms
16 bytes from 2606:1a40::22, icmp_seq=2 hlim=54 time=5.527 ms
16 bytes from 2606:1a40::22, icmp_seq=3 hlim=54 time=5.560 ms
16 bytes from 2606:1a40::22, icmp_seq=4 hlim=54 time=5.829 ms
16 bytes from 2606:1a40::22, icmp_seq=5 hlim=54 time=5.612 ms
16 bytes from 2606:1a40::22, icmp_seq=6 hlim=54 time=6.436 ms
^C
--- 2606:1a40::22 ping6 statistics ---
7 packets transmitted, 7 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 5.527/6.031/7.116/0.540 ms
```

I can't seem to totally decode the hostname from after 'dns=' until the backslash - I assume there's more than the hostname, but it looks like they might all be odd hostnames

```
 _dns-push-tls_tcp!?G_uscans_tcp1921681781
 v�_remotepairing_tcp1921681781
 ݿ_uscan_tcp1921681781
 �:_ippusb_tcp1921681781
 ׉_ipps_tcp1921681781
 ��_ipp_tcp1921681781
 �_printer_tcp1921681781
 ```
Maybe this isn't a real issue. Perhaps it always occurs, just isn't causing an issue

Is there a proper way to decode the dns= string ?

**Comment by planetf1** [comment]
will run with debug log level. May provide some extra info, and help understand if this is expected behaviour.

**Comment by planetf1** [comment]
Here's an example with debug logging - had less this afternoon

```
{"level":"debug","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] 192.168.4.55:51351 -> listener.0: [::]:53: received query: AAAA
 news-edge.apple.com"}
{"level":"info","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] no explicit policy matched, using default routing -> [upstream.0
]"}
{"level":"debug","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] including client info with the request"}
{"level":"debug","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] sending query to upstream.0: "}
{"level":"debug","header":{"Accept":["application/dns-message"],"Content-Type":["application/dns-message"],"X-Cd-Host":["machine"],"X-Cd-Ip":["192.168.4.55"],"X-Cd-Mac":["00:e0:4c:99:99:99"]},"time":"
2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] sending request header"}
{"level":"error","error":"could not perform request: Get \"https://dns.controld.com/aaaaaaaa?dns=cbsBAAABAAAAAAAACW5ld3MtZWRnZQVhcHBsZQNjb20AABwAAQ\": read tcp [blah:blah:blah]:53275->[2606:1a40::22]:443: read: connection reset by peer","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] failed to resolve query"}
{"level":"error","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] all upstreams failed"}
{"level":"debug","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","time":"2023-09-15T14:54:53+01:00","message":"[e0b2ef] received response of 37 bytes in 7.019417ms"}
```

It looks like this was a query for 'news-edge.apple.com' but hit a 'read: connection reset by peer'

**Comment by yegors** [comment]
Hmm, that's rather puzzling. You're saying this only happens with IPv6, and never with Ipv4? Can you provide 2 traceroutes for both IP stacks, to dns.controld.com?

**Comment by yegors** [comment]
As no additional info is provided, closing this.
