### ISSUE TITLE
Config tool no longer working for my Windows 10 PC

### ISSUE THREAD

**Issue by wezaa101** [Control-D-Inc/ctrld#92]
I have this config tool install on several PCs at home. I have a windows 10 machine where when i use any of the resolvers i have setup, it will only enter 127.0.0.1 in the DNS for the network.
If i try to enter one of the DNS address manually, the network settings wont allow me to save them.
I guess this is an issue with my machine and not ControlD, the resolvers work fine on my Windows 11 PC and android phone.
The windows 10 machine will allow me to enter 1.1.1.1 and 1.1.2.2 but not the controlD addresses i have setup.
All was working fine on the Windows 10 machine 2 weeks ago. Nothing new has been installed on that PC recently. 
Do you have any advice please?

**Comment by cuonglm** [comment]
Am I right that you have problem with the desktop application, not the `ctrld` binary itself?

**Comment by yegors** [comment]
Closing this issue as no useful data was provided.
