### ISSUE TITLE
Too many listening udp ports

### ISSUE THREAD

**Issue by malikshi** [Control-D-Inc/ctrld#94]
I was curious about ctrld using many ports udp whenever I am checking ntlp -nulp at my raspberry
![Screenshot_2023-09-23-23-14-37-844-edit_com.sonelli.juicessh.jpg](https://github.com/Control-D-Inc/ctrld/assets/9080737/975f94e1-e959-4283-9d30-4ae2860a0bf0)

**Comment by yegors** [comment]
Hi,

Are you using DOH3? What is the total count of these ports?

**Comment by yegors** [comment]
Can you try standard DOH (you won't see much performance difference) and see if the same issue occurs?

**Comment by cuonglm** [comment]
> > Can you try standard DOH (you won't see much performance difference) and see if the same issue occurs?
> 
> 
> 
> ok. i am removing doh3 also doq just in case. been running 10 minutes, no spam udp port.

quic use UDP, so those connections are expected. They are opened so ctrld dont have to establish new connection for each request.

**Comment by cuonglm** [comment]
@malikshi What ctrld version do you use?

**Comment by cuonglm** [comment]
@malikshi Do you have Discord account? We could chat in more details there.

Thank you.

**Comment by yegors** [comment]
This issue appears to be resolved in the beta build, based on feedback from another person who had this issue.

**Comment by cuonglm** [comment]
v1.3.1 will fix this issue.
