### ISSUE TITLE
Systemd service hangs

### ISSUE THREAD

**Issue by AlfaSierra92** [Control-D-Inc/ctrld#95]
When the service starts, for example when the PC boots, it freezes and closes, forcing me to wait a couple of minutes before it starts again on its own. In the meantime it is not possible to resolve the names.
This is the systemd log:
`ott 05 21:21:27 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: Started ctrld.service.
ott 05 21:21:28 antonio-VivoBook-ASUSLaptop-X531FL-S531FL ctrld[7215]: Oct  5 21:21:28.000 WRN listener.0 could not listen on address: 0.0.0.0:53, trying: 0.0.0.0:53
ott 05 21:21:28 antonio-VivoBook-ASUSLaptop-X531FL-S531FL ctrld[7215]: Oct  5 21:21:28.000 WRN listener.0 could not listen on address: 0.0.0.0:53, trying localhost: 127.0.0.1:53
ott 05 21:21:28 antonio-VivoBook-ASUSLaptop-X531FL-S531FL ctrld[7215]: 2023/10/05 21:21:28 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB).>
ott 05 21:21:39 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: Stopping ctrld.service...
ott 05 21:21:39 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: ctrld.service: Deactivated successfully.
ott 05 21:21:39 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: Stopped ctrld.service.
`
And this is the config.toml:
`
[network.0]
    cidrs = ["0.0.0.0/0"]
    name = "Public"

[listener.0]
    ip = "0.0.0.0"
    port = 53

[listener.0.policy]
    name = 'Fallback'
    networks = [
        {"network.0" = ["upstream.0", "upstream.1", "upstream.2", "upstream.3"]}
    ]

[upstream.0]
    bootstrap_ip = "76.76.2.22"
    endpoint = "https://dns.controld.com/xxxxxx"
    name = "Control D - DOH"
    timeout = 200
    type = "doh3"
    ip_stack = "split"

[upstream.1]
    bootstrap_ip = "76.76.2.22"
    endpoint = "https://dns.controld.com/xxxxxx"
    name = "Control D - DOH3"
    timeout = 200
    type = "doh"
    ip_stack = "split"

[upstream.2]
    bootstrap_ip = "76.76.2.22"
    endpoint = "xxxxxxx.dns.controld.com"
    name = "Controld D - DOQ"
    timeout = 200
    type = "doq"
    ip_stack = "split"

[upstream.3]
    bootstrap_ip = "76.76.2.22"
    endpoint = "xxxxxx.dns.controld.com"
    name = "Controld D - DOT"
    timeout = 200
    type = "dot"
    ip_stack = "split"
    `
I'm on Ubuntu 23.04. Obviously i have omitted some value for privacy reasons.
This happens also when install the service with the command _ctrld start_

**Comment by yegors** [comment]
Hi, 

First things first: Your config will cause you a lot of problems, given that the timeout is set so low, also failover scheme you have is rather pointless as it failsover protocols rather than DNS services. 

Please scrap this entire config, and launch `ctrld` using the Automatic Setup 1 liner installer command. Are you experiencing any issues then?

**Comment by AlfaSierra92** [comment]
I'm going to follow your hints. Anyway, after i played a bit, in the meantime, with systemd service configuration, i notice that this entries
`Wants=systemd-networkd-wait-online.service
After=systemd-networkd-wait-online.service
`
makes the issue in my OS. Deleting theme the problem seems resolved.

**Comment by cuonglm** [comment]
@AlfaSierra92 What's your Linux OS distribution?

**Comment by AlfaSierra92** [comment]
> @AlfaSierra92 What's your Linux OS distribution?
Kubuntu 23.04

**Comment by cuonglm** [comment]
> > @AlfaSierra92 What's your Linux OS distribution?
> 
> Kubuntu 23.04

What's the status of `systemd-networkd-wait-online` when `ctrld` hangs? We want to ensure `ctrld` started after `systemd-networkd-wait-online`, otherwise, changes to DNS settings may be restored by it.

**Comment by AlfaSierra92** [comment]
> > > @AlfaSierra92 What's your Linux OS distribution?
> > 
> > 
> > Kubuntu 23.04
> 
> What's the status of `systemd-networkd-wait-online` when `ctrld` hangs? We want to ensure `ctrld` started after `systemd-networkd-wait-online`, otherwise, changes to DNS settings may be restored by it.

This service wait at boot (it seems it is waiting for network connection that is already available) and then it die approximately after 120 sec, in the meantime ctrld wait for it. Anyway i will provide you further details later when i will go to my PC.

**Comment by AlfaSierra92** [comment]
Here `systemd-networkd-wait-online` log:
systemd-networkd-wait-online.service - Wait for Network to be Configured
     Loaded: loaded (/lib/systemd/system/systemd-networkd-wait-online.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Fri 2023-10-06 15:55:53 CEST; 42s ago
       Docs: man:systemd-networkd-wait-online.service(8)
    Process: 3255 ExecStart=/lib/systemd/systemd-networkd-wait-online (code=exited, status=1/FAILURE)
   Main PID: 3255 (code=exited, status=1/FAILURE)
        CPU: 7ms

ott 06 15:53:53 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: Starting systemd-networkd-wait-online.service - Wait for Network to be Configured...
ott 06 15:55:53 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd-networkd-wait-online[3255]: Timeout occurred while waiting for network connectivity.
ott 06 15:55:53 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
ott 06 15:55:53 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
ott 06 15:55:53 antonio-VivoBook-ASUSLaptop-X531FL-S531FL systemd[1]: Failed to start systemd-networkd-wait-online.service - Wait for Network to be Configured.

I have triggered the error by turning off the wifi but also with connection available at boot i have to wait for 2 mins to wait ctrld.service to start again.

**Comment by cuonglm** [comment]
@AlfaSierra92 Thanks for your information.

What do you mean the connection available at boot? Does it mean you have internet access at boot via cable?

Does thing work normally if you don't turn off the wifi then restart your laptop?

Like I said above, `ctrld` has to depend on `systemd-networkd-wait-online` to be able to set DNS correctly, if you actively fool `systemd-networkd-wait-online` to make it in weird state, `ctrld` has to wait anyway. Probably we could reduce the wait time of ctrld from 120s (default in systemd service file) to a lower value?

**Comment by AlfaSierra92** [comment]
Cable or WiFi connected; it seems the same.
If I restart the laptop I have the same behavior.
I tried to reduce the wait time in ctrld.service but it doesn’t work anyway.

**Comment by cuonglm** [comment]
I can reproduce this problem on my Ubuntu 22.04 after running OS updates. It seems that `systemd-networkd-wait-online` failed for some reason, running `/lib/systemd/systemd-networkd-wait-online` binary hangs forever.

**Comment by cuonglm** [comment]
This is fixed in v1.3.2 release.
