### ISSUE TITLE
Allow skipping of router setup

### ISSUE THREAD

**Issue by csmurton** [Control-D-Inc/ctrld#96]
It would be good to provide a configuration option or runtime flag that disables the flow that modifies `dnsmasq` related configuration files at start and stop time, at least on AsusWRT Merlin devices.

The use case here is I am seeing ctrld conflict with YazFi which also makes use of `/jffs/scripts/dnsmasq.postconf` to insert another listening interface to `dnsmasq` (for the Guest Network). It appears that the line at the bottom of `dnsmasq.postconf` which uses cat to add the YazFi related blurb never gets added, or there is a race condition whereby ctrld rewrites postconf or restarts DNSMasq before the changes to the file are committed.

I have tried both removing the entire ctrld block from this file, and also just leaving in the header and footer but it is still overwritten.

In my case I have already customised `/jffs/configs/dnsmasq.conf.add` to insert what ctrld tries to add via postconf, namely:

```
no-resolv
server=127.0.0.1#1234
add-mac
```

This means that any changes it tries to make (and the run of `service restart_dnsmasq`) is at best a no-op, and at worst it causes all clients on my Guest Network to be unable to reach their configured DNS server as it is no longer bound to the appropriate interface.

**Comment by yegors** [comment]
You can already do that, use **ctrld service start** command (instead of just **start**). This will only start a system service on a listener, and you can steer traffic to it however you'd like.

**Comment by csmurton** [comment]
@yegors I just tried this by stopping `ctrld` and then checked that /jffs/scripts/dnsmasq.postconf was missing all of the Control D related setup, then I ran `ctrld service start` but it reinserts the block into this file.

Would appreciate any other pointers; please let me know if you need any debugging info from me.

**Comment by cuonglm** [comment]
@csmurton In the mean time, you can force ctrld starts on a specific interface with port 53. That will skip the router setup process.

@yegors `ctrld service start` only skip setting DNS, not router setup when ctrld is not direct listener.

**Comment by yegors** [comment]
@cuonglm Should add a skip flag then.

**Comment by cuonglm** [comment]
This is fixed in v1.3.2 release.

- `ctrld start` -> install `ctrld` as system service, do DNS setup, do router setup.
- `ctrld service start` -> only install `ctrld` as system service.
