### ISSUE TITLE
Install script downloading v1.3 and not v.1.3.1

### ISSUE THREAD

**Issue by gniting** [Control-D-Inc/ctrld#97]
Using `sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)"'` to install, and post installation, the version remains v.1.3.0 and not v.1.3.1.

This is on pfsense plus.

**Comment by photomme** [comment]
I can confirm the same thing on UDM PRO SE.  After running the script installer, I am still getting v 1.3.0

**Comment by cuonglm** [comment]
The download url has not been updated with new binaries yet.

Sorry for the delay.

**Comment by gniting** [comment]
Thanks for the quick response. Waiting for a ping from you here once its ready to go.

**Comment by cuonglm** [comment]
> Thanks for the quick response. Waiting for a ping from you here once its ready to go.

The download url was updated, please give it a try, thank you.

**Comment by yegors** [comment]
This is updated now.

**Comment by justinbadal** [comment]
Mine is still downloading 1.3.0...

**Comment by justinbadal** [comment]
I updated using your .dev link and it worked, but the link is still not installing 1.3.1.

**Comment by yegors** [comment]
On this page: https://controld.com/status

What code does it show after "Using Control D".

**Comment by justinbadal** [comment]
Control D Troubleshooting - Fri, 13 Oct 2023 01:25:57 UTC
----------------------------------------------------------------------------

Using Control D   |  DAL
Resolver          |  2awnp8a9w8g
DNS Protocol      |  DNS-over-HTTPS
DNS Latency       |  11.78ms
DNS Host          |  dal-h01
DNS Source IP     |  2600:1700:1260:d5ef:d9fa:66ae:9347:6209
Proxy Authorized  |  No
Null Routed       |  No
Proxy Latency     |  34.98ms
Proxy Host        |  mia-h04
Proxy Source IP   |  2600:1700:1260:d5ef:d9fa:66ae:9347:6209

nslookup captive.apple.com errors when I use the install script. 
when I use the .dev, it gives me the correct lookup.

**Comment by yegors** [comment]
Ok, issue identified + resolved. Try the .com installer again.

**Comment by justinbadal** [comment]
Fixed. Thank you.
