### ISSUE TITLE
Feature request - show custom UbiOS device names

### ISSUE THREAD

**Issue by photomme** [Control-D-Inc/ctrld#98]
Hey Controld folks,

NextDns started showing device names in their logs especially when deployed on UDM PRO - the names that you specify in the UDM admin panel, instead of the device name that you specify on device.  This is cleaner way to show the devices that are currently attached to the UDM PRO and use the filtering options.

It wold be nice to add this to CtrlD in the future.

Thanks,

**Comment by yegors** [comment]
Do you mean device aliases? Can you screenshot what you're referring to?

**Comment by photomme** [comment]
Hey Yegors - that is correct.  For example: https://cloud.photom.me/hEoDHsJ2 and https://cloud.photom.me/0cUpIo38 thank you.

**Comment by yegors** [comment]
I'm a bit unfamiliar with this feature, however if you mirror your custom names to the hosts file they will be read by ctrld (v1.3.1)  and preference over "true hostnames" those devices may be advertising. 

Are you using v1.3.1 and are those names mirrored in /etc/hosts on the UDM Pro, or these are stored in some other config file?

**Comment by cuonglm** [comment]
@yegors I think ubios store these mapping in mongodb, we need to read from there to get the mapping set by users.

**Comment by yegors** [comment]
Looks that way: https://github.com/nextdns/nextdns/blob/cd5b7f567b3b74fd1e42ac993e1f86306bca9139/discovery/ubios_linux.go#L82C1-L82C1

**Comment by photomme** [comment]
That is it ;) let me know if you need any additional info

**Comment by yegors** [comment]
This is done and available in v1.3.4
